#include "integration/InfrastructureIndustryIntegration.h"

#include <algorithm>

namespace subspace {

ShipSpatialValidation InfrastructureIndustryIntegration::ValidateShipSpatialContract(const ModularShipDesign& design) const {
    ShipSpatialValidation r;ShipConstructionSystem construction;auto v=construction.Validate(design);for(const auto& e:v.errors)r.errors.push_back(e);double mass=0;for(const auto& m:design.modules){mass+=m.mass;double volume=std::max(1.0,m.mass*0.055);r.exteriorVolume+=volume;switch(m.family){case ShipModuleFamily::MainDrive:case ShipModuleFamily::ManeuverThruster:case ShipModuleFamily::Reactor:case ShipModuleFamily::WeaponHardpoint:case ShipModuleFamily::IndustrialHardpoint:case ShipModuleFamily::DroneBay:r.reservedMachineryVolume+=volume*0.70;break;case ShipModuleFamily::Cargo:case ShipModuleFamily::Crew:case ShipModuleFamily::FieldFabricator:case ShipModuleFamily::Furnace:r.reservedMachineryVolume+=volume*0.45;break;default:r.reservedMachineryVolume+=volume*0.20;break;}}
    r.usableInteriorVolume=std::max(0.0,r.exteriorVolume-r.reservedMachineryVolume);if(r.usableInteriorVolume<r.exteriorVolume*0.12)r.errors.push_back("insufficient usable interior volume after machinery reservations");r.valid=r.errors.empty()&&mass>0;return r;
}

std::uint64_t InfrastructureIndustryIntegration::QueueShip(const ModularShipDesign& design,ShipProductionWorkflowSystem& shipyard,std::unordered_map<int,double>& inventory) const {auto spatial=ValidateShipSpatialContract(design);if(!spatial.valid)return 0;auto id=shipyard.Queue(design);if(!id)return 0;if(!shipyard.Supply(id,inventory))return id;return id;}

StationCommissioningResult InfrastructureIndustryIntegration::CommissionStation(const StationBuildPlan& plan,StationBuilderSystem& builder,std::unordered_map<std::string,double>& inventory) const {
    StationCommissioningResult out;auto validation=builder.Validate(plan);if(!validation.valid)return out;auto bill=builder.MaterialBill(plan);double consumed=0;for(const auto& kv:bill){auto it=inventory.find(kv.first);if(it==inventory.end()||it->second+1e-9<kv.second)return out;}for(const auto& kv:bill){inventory[kv.first]-=kv.second;consumed+=kv.second;}out.structuralMaterialConsumed=consumed;for(const auto& pm:plan.modules){switch(pm.module.type){case StationModuleType::Dock:out.services.refit=true;break;case StationModuleType::Storage:out.services.storage=true;break;case StationModuleType::Repair:out.services.repairHull=out.services.repairModules=true;break;case StationModuleType::Market:out.services.market=true;break;case StationModuleType::Shipyard:out.services.shipyard=true;break;default:break;}}
    PlayerStationDesign design;design.name=plan.name;design.position=plan.placement.position;design.location=plan.placement.kind;for(const auto& m:plan.modules)design.modules.push_back(m.module);StationConstructionSystem construction;out.roles=construction.EmergentRoles(design);out.commissioned=true;return out;
}

bool InfrastructureIndustryIntegration::BeginPlanetaryOperation(std::uint64_t seed,std::uint64_t planetId,const std::string& name,PlanetSurveySystem& surveySystem,PlanetaryIndustrializationSystem& industrial,PlanetaryProductionOperation& op) const {op.survey=surveySystem.Generate(seed,planetId,name);surveySystem.Advance(op.survey,PlanetSurveyStage::IndustrialCertified);if(!op.survey.elevatorViable)return false;return industrial.BindSurvey(op.project,op.survey)&&industrial.SelectAnchor(op.project,op.survey.elevatorAnchorScore)&&industrial.DeployTether(op.project);}

bool InfrastructureIndustryIntegration::BootstrapSpaceElevator(PlanetaryIndustrializationSystem& industrial,PlanetaryProductionOperation& op,std::unordered_map<std::string,double>& inventory) const {if(op.project.stage!=PlanetaryDevelopmentStage::TetherSeeded&&op.project.stage!=PlanetaryDevelopmentStage::ElevatorConstruction)return false;auto bill=industrial.ElevatorBill(op.survey);for(const auto& req:bill){if(inventory[req.commodity]+1e-9<req.required)return false;}for(const auto& req:bill){inventory[req.commodity]-=req.required;industrial.Deliver(op.project,req.commodity,req.required);}if(!industrial.ElevatorComplete(op.project))return false;if(!industrial.UnlockManufacturing(op.project))return false;op.project.colony.planetId=op.survey.planetId;return true;}

bool InfrastructureIndustryIntegration::AddBasicManufacturingNetwork(PlanetaryProductionOperation& op,PlanetaryManufacturingSystem& m) const {if(op.project.stage!=PlanetaryDevelopmentStage::Manufacturing||!op.project.colony.elevatorOnline)return false;PlanetFacility extract{1,PlanetFacilityType::Extractor,"extract_ore",120, -10,10};PlanetFacility refine{2,PlanetFacilityType::Refinery,"refine_alloy",60,-20,20};PlanetFacility store{3,PlanetFacilityType::Storage,"",0,-2,1000};PlanetFacility elevator{4,PlanetFacilityType::SpaceElevator,"",0,-15,500};return m.AddFacility(op.project.colony,extract)&&m.AddFacility(op.project.colony,refine)&&m.AddFacility(op.project.colony,store)&&m.AddFacility(op.project.colony,elevator)&&m.AddRoute(op.project.colony,{1,2,"ore_iron",120})&&m.AddRoute(op.project.colony,{2,3,"structural_alloy",60})&&m.AddRoute(op.project.colony,{3,4,"structural_alloy",60});}

double InfrastructureIndustryIntegration::ExportCommodity(PlanetaryProductionOperation& op,PlanetaryManufacturingSystem& m,const std::string& commodity,double amount,LocalEconomyState& market,LocalEconomySystem& economy) const {double moved=m.ExportToOrbit(op.project.colony,commodity,amount);if(moved<=0)return 0;op.orbitalInventory[commodity]+=moved;economy.ApplySupplyShock(market,commodity,moved);return moved;}

std::vector<SandboxContract> InfrastructureIndustryIntegration::AdvanceStationEconomy(StationPopulationState& p,StationPopulationSystem& ps,LocalEconomyState& market,LocalEconomySystem& economy,double hours) const {ps.Advance(p,hours);std::vector<SandboxContract> out;auto need=[&](const std::string& commodity,double desired,double base){if(!market.commodities.count(commodity))economy.Register(market,commodity,0,desired,base);economy.ApplySupplyShock(market,commodity,-ps.ConsumptionRate(p)*hours);economy.Tick(market,hours);auto c=economy.GenerateContract(market,commodity);if(c.rewardCredits>0)out.push_back(c);};need("food_rations",std::max(50.0,p.population*0.5),8);need("station_supplies",std::max(25.0,p.population*0.2),15);return out;}

} // namespace subspace
