#include "integration/LivingUniverseIntegration.h"

#include <algorithm>

namespace subspace {

CorporationMilestoneReport LivingUniverseIntegration::EvaluateCorporation(CorporationSystem& members,CorporationOperationsSystem& operations,CorporationProgressionSystem& progression,CorporationProgressionState& state,const CorporationAssetLedger& assets,const FleetDoctrineSystem& doctrines,const FleetDoctrine& doctrine,const std::vector<FleetMember>& fleet) const {
    (void)operations;CorporationMilestoneReport r;state.assetsValue=std::max(state.assetsValue,assets.credits);state.ownedShips=std::max(state.ownedShips,static_cast<int>(assets.ships.size()));state.ownedStations=std::max(state.ownedStations,static_cast<int>(assets.stations.size()));state.developedPlanets=std::max(state.developedPlanets,static_cast<int>(assets.planetaryOperations.size()));r.level=progression.Recalculate(state);r.unlocks=state.unlocks;r.payroll=members.Payroll();r.logisticsReadiness=operations.LogisticsReadiness(assets);auto* registered=doctrines.Get(doctrine.id);auto report=doctrines.Evaluate(registered?*registered:doctrine,fleet);r.doctrineReady=report.valid;return r;
}

SectorIntegrationReport LivingUniverseIntegration::AdvanceSector(DynamicSectorState& sector,double hours,SectorSimulationSystem& sim,DynamicFactionSystem& factions,const std::string& factionId,LocalEconomyState& market,LocalEconomySystem& economy,MarketContractSystem& contracts,PersistentUniverseSystem& persistence) const {
    SectorIntegrationReport r;auto events=sim.Advance(sector,hours);r.events=static_cast<int>(events.size());for(const auto& e:events){if(e.type==SectorEventType::Shortage){economy.ApplySupplyShock(market,"station_supplies",-25.0*e.severity);auto c=economy.GenerateContract(market,"station_supplies");c.career=ContractCareer::Logistics;c.title="Emergency sector resupply";contracts.AddContract(c);r.generatedContracts++;persistence.Record(PersistentEventType::MarketShock,sector.id,"station_supplies",e.severity);r.persistentEvents++;r.marketPressure+=e.severity;}else if(e.type==SectorEventType::PirateRaid){SandboxContract c;c.career=ContractCareer::Combat;c.title="Suppress pirate raid";c.faction=factionId;c.rewardCredits=2500+5000*e.severity;contracts.AddContract(c);r.generatedContracts++;persistence.Record(PersistentEventType::StationDamaged,sector.id,"regional_infrastructure",e.severity*10);r.persistentEvents++;}else if(e.type==SectorEventType::Discovery){SandboxContract c;c.career=ContractCareer::Exploration;c.title="Resolve newly detected signature";c.faction=factionId;c.rewardCredits=1800;contracts.AddContract(c);r.generatedContracts++;persistence.Record(PersistentEventType::DiscoveryRecorded,sector.id,"regional_signature",1);r.persistentEvents++;}}
    if(const auto* f=factions.Get(factionId)){auto action=factions.ChooseAction(factionId,sector.piratePressure,sector.resourcePressure);factions.Advance(factionId,action,hours);(void)f;}economy.Tick(market,hours);return r;
}

bool LivingUniverseIntegration::PublishDiscovery(const DeepExplorationSite& site,std::uint64_t id,const AstronomicalPosition& position,SystemNavigationSystem& navigation,PersistentUniverseSystem& persistence,const std::string& region) const {if(site.state!=DeepSiteState::Resolved&&site.state!=DeepSiteState::Exploited)return false;SystemDestination d;d.id=id;d.name=site.id;d.type=SystemDestinationType::Signature;d.position=position;d.discovered=true;d.warpable=true;d.hazardRating=site.danger;if(!navigation.RegisterDestination(d))return false;navigation.AddBookmark(id);persistence.Record(PersistentEventType::DiscoveryRecorded,region,site.id,site.value);return true;}

bool LivingUniverseIntegration::PublishTear(const AnomalousSpacePocket& pocket,const AstronomicalPosition& position,SystemNavigationSystem& navigation) const {if(pocket.id==0||pocket.collapsed)return false;SystemDestination d;d.id=900000000ULL+pocket.id;d.name="Subspace Tear -> "+pocket.destination;d.type=SystemDestinationType::DeepSpace;d.position=position;d.discovered=true;d.warpable=true;d.hazardRating=pocket.hazard;return navigation.RegisterDestination(d);}

RecoveryResult LivingUniverseIntegration::RecordLoss(const std::string& region,const std::string& shipId,double value,const RecoveryPolicy& policy,PersistentUniverseSystem& persistence) const {RecoveryResult r;if(region.empty()||shipId.empty()||value<=0)return r;double coverage=std::clamp(policy.insuranceCoverage,0.0,1.0);double wreck=std::clamp(policy.wreckRecoveryFraction,0.0,1.0);r.insurancePayout=value*coverage;r.recoverableValue=value*wreck;r.netLoss=std::max(0.0,value-r.insurancePayout-r.recoverableValue+policy.rescueFee);persistence.Record(PersistentEventType::ShipDestroyed,region,shipId,value);persistence.Record(PersistentEventType::WreckCreated,region,"wreck:"+shipId,r.recoverableValue);return r;}

void LivingUniverseIntegration::EmbedUniverseLedger(CampaignState& campaign,const PersistentUniverseSystem& persistence) const {campaign.persistentUniverseLedger=persistence.Serialize();}
bool LivingUniverseIntegration::RestoreUniverseLedger(const CampaignState& campaign,PersistentUniverseSystem& persistence) const {return campaign.persistentUniverseLedger.empty()?true:persistence.Deserialize(campaign.persistentUniverseLedger);}

SandboxAcceptanceIIIReport SandboxAcceptanceIIISystem::Evaluate(const SandboxAcceptanceIIIState& s) const {SandboxAcceptanceIIIReport r;auto req=[&](bool v,const char* n){if(v)r.satisfied++;else r.missing.push_back(n);};req(s.physicalCombat,"physical combat/fitting");req(s.physicalDamageRepair,"physical damage/repair");req(s.dronesSensorsEwar,"drones/sensors/EWAR");req(s.systemMapVector,"system map/vector travel");req(s.astronomicalScale,"astronomical presentation");req(s.massiveMiningRegions,"massive mining regions");req(s.shipBuilderProduction,"ship builder/production");req(s.stationOperations,"station operations");req(s.planetarySurveyElevator,"planet survey/elevator");req(s.planetaryManufacturing,"planetary manufacturing");req(s.causalEconomy,"causal economy");req(s.explorationRoutes,"exploration intelligence");req(s.fleetCrewCorporation,"fleet/crew/corporation");req(s.dynamicFactions,"dynamic factions");req(s.sectorCrises,"sector crises/events");req(s.anomalousTravel,"anomalous travel");req(s.persistentRecovery,"persistent recovery");req(s.saveLedger,"save-integrated universe ledger");r.passed=r.satisfied==r.required;return r;}

} // namespace subspace
