#include "appearance/KitbashAppearanceSystem.h"

namespace subspace {
std::vector<AppearanceRegionRule> KitbashAppearanceSystem::DefaultRules(){
    using S=assets::SurfaceSemantic;std::vector<AppearanceRegionRule> r;
    const ShipSpatialRegion regions[]={ShipSpatialRegion::Bow,ShipSpatialRegion::ForwardHull,ShipSpatialRegion::Command,ShipSpatialRegion::MidHull,ShipSpatialRegion::AftHull,ShipSpatialRegion::Port,ShipSpatialRegion::Starboard,ShipSpatialRegion::Dorsal,ShipSpatialRegion::Ventral,ShipSpatialRegion::Propulsion};
    for(const auto region:regions){r.push_back({region,S::HullPrimary,AppearanceChannel::Primary,true,true,true});r.push_back({region,S::HullSecondary,AppearanceChannel::Secondary,true,true,true});r.push_back({region,S::Trim,AppearanceChannel::Accent,true,true,true});r.push_back({region,S::StructuralMetal,AppearanceChannel::Structural,false,true,true});r.push_back({region,S::Armor,AppearanceChannel::Primary,true,true,true});r.push_back({region,S::CanopyGlass,AppearanceChannel::Functional,false,false,true});r.push_back({region,S::EngineHousing,AppearanceChannel::Secondary,true,true,true});r.push_back({region,S::Nozzle,AppearanceChannel::Functional,false,false,true});r.push_back({region,S::ThrusterEmissive,AppearanceChannel::Emissive,false,false,false});r.push_back({region,S::Radiator,AppearanceChannel::Functional,false,false,true});r.push_back({region,S::WeaponMetal,AppearanceChannel::Functional,false,true,true});r.push_back({region,S::Sensor,AppearanceChannel::Functional,false,false,true});r.push_back({region,S::DecalSurface,AppearanceChannel::Primary,true,true,true});r.push_back({region,S::DoNotPaint,AppearanceChannel::Unpainted,false,false,false});}
    return r;
}
AppearancePresetDefinition KitbashAppearanceSystem::BuildFactionPreset(const std::string& faction,const std::string& variant){AppearancePresetDefinition p;p.id=faction+"_"+variant;p.parentId="SUBSPACE_DEFAULT";p.rules=DefaultRules();for(auto&rule:p.rules){if(rule.region==ShipSpatialRegion::Command&&rule.surface==assets::SurfaceSemantic::HullPrimary)rule.channel=AppearanceChannel::Secondary;if(rule.region==ShipSpatialRegion::AftHull&&rule.surface==assets::SurfaceSemantic::HullPrimary)rule.channel=AppearanceChannel::Primary;if((rule.region==ShipSpatialRegion::Port||rule.region==ShipSpatialRegion::Starboard)&&rule.surface==assets::SurfaceSemantic::Trim)rule.channel=AppearanceChannel::Accent;if(rule.region==ShipSpatialRegion::Propulsion&&rule.surface==assets::SurfaceSemantic::HullPrimary)rule.channel=AppearanceChannel::Secondary;}return p;}
AppearanceChannel KitbashAppearanceSystem::Resolve(const AppearancePresetDefinition&p,ShipSpatialRegion region,assets::SurfaceSemantic surface){for(auto it=p.rules.rbegin();it!=p.rules.rend();++it)if(it->region==region&&it->surface==surface)return it->channel;return surface==assets::SurfaceSemantic::StructuralMetal?AppearanceChannel::Structural:AppearanceChannel::Primary;}
bool KitbashAppearanceSystem::MirrorsDecalGlyphs(bool readableText){return !readableText;}
} // namespace subspace
