#include "economy/PlanetaryIndustrySystem.h"
#include <algorithm>
namespace subspace {
namespace {std::uint32_t Mix(std::uint32_t x){x^=x>>16;x*=0x7feb352dU;x^=x>>15;x*=0x846ca68bU;x^=x>>16;return x;}float U(std::uint32_t x){return (Mix(x)&0xffff)/65535.0f;}}
PlanetaryIndustryState PlanetaryIndustrySystem::Generate(const PlanetData&p,int rad,std::uint32_t seed) const {PlanetaryIndustryState s;s.representation=p.industryRepresentation;rad=std::clamp(rad,1,12);for(int q=-rad;q<=rad;++q)for(int r=std::max(-rad,-q-rad);r<=std::min(rad,-q+rad);++r){PiHexData h;h.coord={q,r};h.resource=std::clamp(p.resourceRichness*(.55f+U(seed+q*127+r*313)*.9f),0.0f,1.0f);h.hazard=std::clamp(p.hazardLevel*(.6f+U(seed+q*17+r*43)*.8f),0.0f,1.0f);h.buildability=std::clamp(1.0f-h.hazard*.65f,0.05f,1.0f);h.surveyed=(q==0&&r==0);s.hexes[h.coord]=h;}s.environmentTier=p.hazardLevel>.75f?4:p.hazardLevel>.5f?3:p.hazardLevel>.3f?2:1;return s;}
bool PlanetaryIndustrySystem::Place(PlanetaryIndustryState&s,PiInstallation i) const {auto it=s.hexes.find(i.hex);if(it==s.hexes.end()||!it->second.surveyed||it->second.buildability<.15f)return false;if(s.representation==PlanetIndustryRepresentation::AtmosphericCollectorRing&&i.kind!=PiInstallationKind::AtmosphericCollector&&i.kind!=PiInstallationKind::Storage&&i.kind!=PiInstallationKind::Power&&i.kind!=PiInstallationKind::Logistics)return false;for(const auto&x:s.installations)if(x.hex.q==i.hex.q&&x.hex.r==i.hex.r)return false;if(i.id==0)i.id=s.installations.size()+1;s.installations.push_back(i);return true;}
PiValidation PlanetaryIndustrySystem::Validate(const PlanetaryIndustryState&s,float hazard) const {PiValidation v;bool hasStorage=false,hasLogistics=false;int defenses=0;for(const auto&i:s.installations){if(!i.active)continue;v.production+=std::max(0.0,i.outputPerHour-i.inputPerHour);v.powerBalance+=i.power;if(i.kind==PiInstallationKind::Storage)hasStorage=true;if(i.kind==PiInstallationKind::Logistics)hasLogistics=true;if(i.kind==PiInstallationKind::Defense)++defenses;}if(!hasStorage)v.errors.push_back("planetary industry requires storage");if(!hasLogistics)v.errors.push_back("planetary industry requires logistics");if(v.powerBalance<0)v.errors.push_back("planetary power deficit");if(hazard>.55f&&defenses==0){v.protectedEnough=false;v.errors.push_back("hostile planet requires perimeter defense");}v.valid=v.errors.empty();return v;}
double PlanetaryIndustrySystem::TransferToTether(PlanetaryIndustryState&s,double produced,double hours) const {const double moved=std::max(0.0,std::min(produced,s.tetherThroughputPerHour*std::max(0.0,hours)));s.tetherStorage+=moved;return moved;}
} // namespace subspace
