#include "construction/UniversalConstructionSystem.h"

#include <algorithm>
#include <cctype>
#include <cmath>

namespace subspace {
namespace {
std::string Lower(std::string s){for(char&c:s)c=static_cast<char>(std::tolower(static_cast<unsigned char>(c)));return s;}
bool Has(const std::string&s,const char*t){return s.find(t)!=std::string::npos;}
const ShipyardModuleRecord* Find(const std::vector<ShipyardModuleRecord>&catalog,const std::string&id){for(const auto&r:catalog)if(r.source.moduleId==id)return &r;return nullptr;}
ConstructionBlueprintDomain BpDomain(ConstructionDomain d){switch(d){case ConstructionDomain::Station:return ConstructionBlueprintDomain::Station;case ConstructionDomain::Planetary:return ConstructionBlueprintDomain::Planetary;case ConstructionDomain::Weapon:return ConstructionBlueprintDomain::Weapon;default:return ConstructionBlueprintDomain::Ship;}}
}

ConstructionDomain UniversalConstructionSystem::Domain(ConstructionWorkspaceMode m){switch(m){case ConstructionWorkspaceMode::Ship:return ConstructionDomain::Ship;case ConstructionWorkspaceMode::Station:return ConstructionDomain::Station;case ConstructionWorkspaceMode::Planetary:return ConstructionDomain::Planetary;case ConstructionWorkspaceMode::Weapon:return ConstructionDomain::Weapon;}return ConstructionDomain::Ship;}
const char* UniversalConstructionSystem::ModeName(ConstructionWorkspaceMode m){switch(m){case ConstructionWorkspaceMode::Ship:return "SHIPS";case ConstructionWorkspaceMode::Station:return "STATIONS";case ConstructionWorkspaceMode::Planetary:return "PLANETARY";case ConstructionWorkspaceMode::Weapon:return "WEAPONS";}return "SHIPS";}

KitbashMorphProfile UniversalConstructionSystem::StationMorphProfile(UniversalSizeClass reference,bool structural,bool docking){KitbashMorphProfile p;p.referenceSize=reference;p.minimumSize=UniversalSizeClass::XS;p.maximumSize=UniversalSizeClass::XL;p.preserveMountRegions=true;p.preserveFunctionalRegions=true;if(structural){p.policy=KitbashScalingPolicy::StructuralFree;p.minLengthScale=.30f;p.maxLengthScale=5.0f;p.minWidthScale=.55f;p.maxWidthScale=2.5f;p.minHeightScale=.55f;p.maxHeightScale=2.5f;}else if(docking){p.policy=KitbashScalingPolicy::DiscreteFamily;p.minLengthScale=.85f;p.maxLengthScale=1.25f;p.minWidthScale=.85f;p.maxWidthScale=1.25f;p.minHeightScale=.85f;p.maxHeightScale=1.25f;}else{p.policy=KitbashScalingPolicy::ParametricFunctional;p.minLengthScale=.55f;p.maxLengthScale=2.5f;p.minWidthScale=.55f;p.maxWidthScale=2.2f;p.minHeightScale=.55f;p.maxHeightScale=2.2f;}return p;}

PlanetaryModuleRole UniversalConstructionSystem::InferPlanetaryRole(const UniversalKitbashProfile&profile,const std::string&id0){const std::string id=Lower(id0);for(const auto&r:profile.domainRoles)if(r.domain==ConstructionDomain::Planetary){const std::string x=Lower(r.role);if(Has(x,"defense"))return PlanetaryModuleRole::Defense;if(Has(x,"comm"))return PlanetaryModuleRole::Communications;if(Has(x,"gantry")||Has(x,"struct"))return PlanetaryModuleRole::Foundation;}if(Has(id,"mine")||Has(id,"drill"))return PlanetaryModuleRole::Mining;if(Has(id,"refin"))return PlanetaryModuleRole::Refinery;if(Has(id,"factory")||Has(id,"manufact"))return PlanetaryModuleRole::Industry;if(Has(id,"reactor")||Has(id,"power")||Has(id,"solar"))return PlanetaryModuleRole::Power;if(Has(id,"storage")||Has(id,"warehouse")||Has(id,"tank"))return PlanetaryModuleRole::Storage;if(Has(id,"port")||Has(id,"landing")||Has(id,"elevator"))return PlanetaryModuleRole::Spaceport;if(Has(id,"hab")||Has(id,"residential"))return PlanetaryModuleRole::Habitation;if(Has(id,"research")||Has(id,"lab"))return PlanetaryModuleRole::Research;if(Has(id,"farm")||Has(id,"agri"))return PlanetaryModuleRole::Agriculture;if(Has(id,"road")||Has(id,"logistic")||Has(id,"cargo"))return PlanetaryModuleRole::Logistics;return PlanetaryModuleRole::Utility;}

std::vector<PlanetaryFacilityCapability> UniversalConstructionSystem::RequiredPlanetaryCapabilities(PlanetaryModuleRole role){std::vector<PlanetaryFacilityCapability> r={PlanetaryFacilityCapability::Foundation,PlanetaryFacilityCapability::Power,PlanetaryFacilityCapability::Communications};if(role==PlanetaryModuleRole::Industry||role==PlanetaryModuleRole::Refinery||role==PlanetaryModuleRole::Mining||role==PlanetaryModuleRole::Agriculture||role==PlanetaryModuleRole::Research){r.push_back(PlanetaryFacilityCapability::Production);r.push_back(PlanetaryFacilityCapability::InputStorage);r.push_back(PlanetaryFacilityCapability::OutputStorage);r.push_back(PlanetaryFacilityCapability::LogisticsAccess);}else if(role==PlanetaryModuleRole::Storage||role==PlanetaryModuleRole::Spaceport||role==PlanetaryModuleRole::Logistics){r.push_back(PlanetaryFacilityCapability::InputStorage);r.push_back(PlanetaryFacilityCapability::OutputStorage);r.push_back(PlanetaryFacilityCapability::LogisticsAccess);}return r;}

WeaponAssemblyRole UniversalConstructionSystem::NormalizeWeaponRole(const UniversalKitbashProfile&profile){return profile.weaponRole;}

ConstructionBlueprint UniversalConstructionSystem::FromShipRecipe(const ProceduralShipVisualRecipe&recipe,const std::vector<ShipyardModuleRecord>&catalog,const std::string&blueprintId){ConstructionBlueprint b;b.blueprintId=blueprintId;b.displayName=blueprintId;b.domain=ConstructionBlueprintDomain::Ship;b.factionId=recipe.factionId;b.familyId=recipe.hullFamilyId;b.role=recipe.roleVariantId.empty()?recipe.role:recipe.roleVariantId;b.appearancePresetId=recipe.appearancePresetId;b.attachments=recipe.attachments;b.draft=!recipe.acceptedByArtDirector;b.certified=recipe.acceptedByArtDirector;for(const auto&p:recipe.modules){ConstructionBlueprintModule m;m.assetId=p.moduleId;m.placement=p;m.sourceAssetId=p.moduleId;if(const auto*r=Find(catalog,p.moduleId)){m.size=UniversalKitbashAuthority::FromShipyardSize(r->size);m.role=r->placementRole;}b.modules.push_back(m);}return b;}

ConstructionBlueprintValidation UniversalConstructionSystem::ValidateBlueprint(const ConstructionBlueprint&b){ConstructionBlueprintValidation r;if(b.blueprintId.empty())r.errors.push_back("Blueprint ID is required.");if(b.modules.empty())r.errors.push_back("Blueprint must contain at least one module.");for(const auto&a:b.attachments)if(a.parentModuleIndex>=b.modules.size()||a.childModuleIndex>=b.modules.size())r.errors.push_back("Attachment graph references a missing module.");if(b.domain==ConstructionBlueprintDomain::Ship&&b.familyId.empty())r.warnings.push_back("Ship blueprint has no certified hull-family lineage.");if(b.domain==ConstructionBlueprintDomain::Planetary&&b.role.empty())r.warnings.push_back("Planetary blueprint has no facility role.");r.valid=r.errors.empty();return r;}

KitbashManufacturingRecipe UniversalConstructionSystem::BuildManufacturingRecipe(const UniversalKitbashProfile&profile,ConstructionDomain domain,UniversalSizeClass size,float volume){KitbashManufacturingRecipe r;r.recipeId="manufacture:"+profile.assetId+"@"+UniversalKitbashAuthority::SizeName(size);r.assetId=profile.assetId;r.domain=domain;r.size=size;const float scale=UniversalKitbashAuthority::NominalScale(size);const float v=std::max(.05f,volume*scale*scale*scale);r.estimatedMass=v*7.8f;r.manufacturingHours=std::max(.10f,v*.42f);r.materials.push_back({"STRUCTURAL_ALLOY",r.estimatedMass*.72f});r.materials.push_back({"MACHINE_COMPONENTS",r.estimatedMass*.16f});r.materials.push_back({"ELECTRONICS",r.estimatedMass*.06f});if(profile.propulsionRole!=PropulsionRole::None)r.materials.push_back({"PROPULSION_COMPONENTS",r.estimatedMass*.12f});if(profile.weaponRole!=WeaponAssemblyRole::None)r.materials.push_back({"WEAPON_COMPONENTS",r.estimatedMass*.12f});r.prerequisiteTechnologies={"KITBASH_MANUFACTURING"};return r;}

ReverseEngineeringRecord UniversalConstructionSystem::AnalyzeCapturedAsset(const std::string&assetId,const std::string&faction,const std::string&bp,float progress){ReverseEngineeringRecord r;r.capturedAssetId=assetId;r.sourceFactionId=faction;r.sourceBlueprintId=bp;const float p=std::clamp(progress,0.0f,1.0f);r.hullKnowledge=p;r.moduleKnowledge=std::clamp(p*1.15f,0.0f,1.0f);r.materialKnowledge=std::clamp(p*.90f,0.0f,1.0f);r.manufacturingUnlocked=p>=1.0f;if(r.moduleKnowledge>=.35f)r.learnedAssetIds.push_back(assetId);return r;}

} // namespace subspace
