#include "ui/TacticalContactsSystem.h"
#include <algorithm>
namespace subspace {
bool TacticalContactsSystem::VisibleInPreset(TacticalContactKind k,TacticalContactPreset p){if(p==TacticalContactPreset::All)return true;switch(p){case TacticalContactPreset::Combat:return k==TacticalContactKind::HostileShip||k==TacticalContactKind::FriendlyShip||k==TacticalContactKind::Fleet;case TacticalContactPreset::Mining:return k==TacticalContactKind::Asteroid||k==TacticalContactKind::Station;case TacticalContactPreset::Travel:return k==TacticalContactKind::Station||k==TacticalContactKind::Planet||k==TacticalContactKind::Moon||k==TacticalContactKind::Site;case TacticalContactPreset::Salvage:return k==TacticalContactKind::Wreck||k==TacticalContactKind::Station;case TacticalContactPreset::Exploration:return k==TacticalContactKind::Site||k==TacticalContactKind::Planet||k==TacticalContactKind::Moon;case TacticalContactPreset::Fleet:return k==TacticalContactKind::Fleet||k==TacticalContactKind::FriendlyShip;default:return true;}}
void TacticalContactsSystem::Sort(TacticalContactsModel& m){if(m.freezeSort)return;std::stable_sort(m.rows.begin(),m.rows.end(),[&](const auto&a,const auto&b){if(m.sortColumn=="NAME")return m.sortAscending?a.name<b.name:a.name>b.name;if(m.sortColumn=="THREAT")return m.sortAscending?a.threat<b.threat:a.threat>b.threat;return m.sortAscending?a.range<b.range:a.range>b.range;});}
const char* TacticalContactsSystem::PresetName(TacticalContactPreset p){switch(p){case TacticalContactPreset::Combat:return"COMBAT";case TacticalContactPreset::Mining:return"MINING";case TacticalContactPreset::Travel:return"TRAVEL";case TacticalContactPreset::Salvage:return"SALVAGE";case TacticalContactPreset::Exploration:return"EXPLORE";case TacticalContactPreset::Fleet:return"FLEET";default:return"ALL";}}
const char* TacticalContactsSystem::PresetShortName(TacticalContactPreset p){switch(p){case TacticalContactPreset::Combat:return"CMB";case TacticalContactPreset::Mining:return"MIN";case TacticalContactPreset::Travel:return"TRV";case TacticalContactPreset::Salvage:return"SAL";case TacticalContactPreset::Exploration:return"EXP";case TacticalContactPreset::Fleet:return"FLT";default:return"ALL";}}
TacticalContactsLayout TacticalContactsSystem::Layout(int w,int,int){TacticalContactsLayout l;l.x=float(w)-382.0f;l.y=350.0f;return l;}
TacticalContactPreset TacticalContactsSystem::PresetFromIndex(int i){switch(i){case 0:return TacticalContactPreset::Combat;case 1:return TacticalContactPreset::Mining;case 2:return TacticalContactPreset::Travel;case 3:return TacticalContactPreset::Salvage;case 4:return TacticalContactPreset::Exploration;case 5:return TacticalContactPreset::Fleet;default:return TacticalContactPreset::All;}}
int TacticalContactsSystem::HitTestPreset(const TacticalContactsModel&m,int w,int h,float x,float y){const int visible=std::min<int>(m.maxVisibleRows,static_cast<int>(m.rows.size()));const auto l=Layout(w,h,visible);const float top=l.y+l.titleHeight;if(x<l.x||x>l.x+l.width||y<top||y>top+l.tabHeight)return -1;const float tabWidth=l.width/7.0f;return std::clamp(static_cast<int>((x-l.x)/tabWidth),0,6);}
int TacticalContactsSystem::HitTestRow(const TacticalContactsModel&m,int w,int h,float x,float y){const int visible=std::min<int>(m.maxVisibleRows,static_cast<int>(m.rows.size()));const auto l=Layout(w,h,visible);if(x<l.x||x>l.x+l.width||y<l.RowsY())return -1;const int row=static_cast<int>((y-l.RowsY())/l.rowHeight);return row>=0&&row<visible?row:-1;}
} // namespace subspace
