#include "interior/ApertureHangarAuthoringSystem.h"
#include <algorithm>

namespace subspace {
ApertureDefinition ApertureHangarAuthoringSystem::StandardDoor(const WorldScaleProfile&s){ApertureDefinition a;a.id="standard.player-door";a.kind=ApertureKind::Door;a.openingWidthMeters=s.referenceDoorWidthMeters;a.openingHeightMeters=s.referenceDoorHeightMeters;a.clearanceDepthMeters=std::max(.75f,s.referenceReachMeters);a.articulation.id="door-panel";a.articulation.pressureBoundary=true;return a;}
ApertureDefinition ApertureHangarAuthoringSystem::StandardAirlock(const WorldScaleProfile&s){auto a=StandardDoor(s);a.id="standard.airlock";a.kind=ApertureKind::Airlock;a.clearanceDepthMeters=std::max(1.5f,s.referenceInteriorCellMeters);return a;}
VehicleTransportEnvelope ApertureHangarAuthoringSystem::BaselineVehicle(VehicleEnvelopeKind k){VehicleTransportEnvelope e;e.kind=k;switch(k){case VehicleEnvelopeKind::Hoverbike:e.vehicleSizeMeters={1.0f,2.4f,1.4f};e.requiredBaySizeMeters={1.8f,3.4f,2.4f};e.approachClearanceMeters=.6f;break;case VehicleEnvelopeKind::Mech:e.vehicleSizeMeters={2.2f,2.4f,3.0f};e.requiredBaySizeMeters={3.4f,4.0f,4.2f};break;case VehicleEnvelopeKind::Rover:e.vehicleSizeMeters={2.1f,4.2f,1.8f};e.requiredBaySizeMeters={3.4f,6.0f,2.8f};break;case VehicleEnvelopeKind::Shuttle:e.vehicleSizeMeters={5.0f,9.0f,3.5f};e.requiredBaySizeMeters={7.0f,12.0f,5.5f};e.approachClearanceMeters=2.0f;break;}return e;}
ApertureDefinition ApertureHangarAuthoringSystem::StandardHangarDoor(const VehicleTransportEnvelope&v,const WorldScaleProfile&s){ApertureDefinition a;a.id="standard.hangar-door";a.kind=ApertureKind::HangarDoor;a.openingWidthMeters=v.requiredBaySizeMeters.x;a.openingHeightMeters=std::max(v.requiredBaySizeMeters.z,s.referenceDoorHeightMeters);a.clearanceDepthMeters=std::max(v.approachClearanceMeters,s.referenceInteriorCellMeters);a.vehiclePassable=true;a.playerPassable=true;a.articulation.id="hangar-door-panel";a.articulation.detachablePanel=true;a.articulation.pressureBoundary=true;return a;}
ApertureValidationResult ApertureHangarAuthoringSystem::Validate(const ApertureDefinition&a,const WorldScaleProfile&s){ApertureValidationResult r;r.valid=true;if(a.openingWidthMeters<=0||a.openingHeightMeters<=0){r.valid=false;r.errors.push_back("opening dimensions must be positive");}if(a.playerPassable&&(a.openingWidthMeters<s.referenceShoulderWidthMeters*1.35f||a.openingHeightMeters<s.referencePlayerHeightMeters*1.08f)){r.valid=false;r.errors.push_back("player-passable aperture violates canonical player clearance");}if((a.kind==ApertureKind::Airlock||a.kind==ApertureKind::DockingCollar||a.kind==ApertureKind::HangarDoor)&&!a.pressureSeal&&!a.usesForceField)r.warnings.push_back("pressure-boundary aperture has neither physical seal nor force field");if(a.animated&&a.articulation.axisLocal.length()<.5f){r.valid=false;r.errors.push_back("animated aperture requires a valid articulation axis");}return r;}
ApertureValidationResult ApertureHangarAuthoringSystem::Validate(const HangarDefinition&h,const WorldScaleProfile&s){auto r=Validate(h.aperture,s);if(!h.aperture.vehiclePassable){r.valid=false;r.errors.push_back("hangar aperture must be vehicle-passable");}if(h.capacity==0){r.valid=false;r.errors.push_back("hangar capacity must be at least one");}for(const auto&v:h.supportedVehicles){if(h.aperture.openingWidthMeters+1e-4f<v.requiredBaySizeMeters.x||h.aperture.openingHeightMeters+1e-4f<v.requiredBaySizeMeters.z){r.valid=false;r.errors.push_back("hangar aperture is smaller than a certified vehicle envelope");break;}}return r;}
} // namespace subspace
