#include "assets/CanonicalSurfacePolicySystem.h"

#include <algorithm>
#include <cctype>

namespace subspace::assets {
namespace {
std::string Lower(std::string s){for(auto&c:s)c=static_cast<char>(std::tolower(static_cast<unsigned char>(c)));return s;}
bool Has(const std::string&s,const char*t){return s.find(t)!=std::string::npos;}
}
const char* CanonicalSurfacePolicySystem::SemanticName(SurfaceSemantic s){switch(s){case SurfaceSemantic::Unknown:return "UNKNOWN";case SurfaceSemantic::HullPrimary:return "HULL PRIMARY";case SurfaceSemantic::HullSecondary:return "HULL SECONDARY";case SurfaceSemantic::Trim:return "TRIM";case SurfaceSemantic::StructuralMetal:return "STRUCTURAL METAL";case SurfaceSemantic::Armor:return "ARMOR";case SurfaceSemantic::CanopyGlass:return "CANOPY GLASS";case SurfaceSemantic::EngineHousing:return "ENGINE HOUSING";case SurfaceSemantic::Nozzle:return "NOZZLE";case SurfaceSemantic::ThrusterEmissive:return "THRUSTER EMISSIVE";case SurfaceSemantic::Radiator:return "RADIATOR";case SurfaceSemantic::WeaponMetal:return "WEAPON METAL";case SurfaceSemantic::Sensor:return "SENSOR";case SurfaceSemantic::InteriorVisible:return "INTERIOR VISIBLE";case SurfaceSemantic::DecalSurface:return "DECAL SURFACE";case SurfaceSemantic::DoNotPaint:return "DO NOT PAINT";}return "UNKNOWN";}
SurfaceAuthoringPolicy CanonicalSurfacePolicySystem::Infer(AssetIndex index,const PbrMaterial&m,const std::string&sourceName){SurfaceAuthoringPolicy p;p.materialIndex=index;const std::string n=Lower(m.name+" "+sourceName);if(m.domain==MaterialDomain::Canopy||Has(n,"glass")||Has(n,"canopy")||Has(n,"window")){p.semantic=SurfaceSemantic::CanopyGlass;return p;}if(m.domain==MaterialDomain::ThrusterCore||m.domain==MaterialDomain::EmissiveDetail||Has(n,"emiss")||Has(n,"glow")){p.semantic=SurfaceSemantic::ThrusterEmissive;p.emissiveOverride=true;return p;}if(Has(n,"nozzle")||Has(n,"exhaust")){p.semantic=SurfaceSemantic::Nozzle;return p;}if(Has(n,"radiator")||Has(n,"heat")){p.semantic=SurfaceSemantic::Radiator;return p;}if(m.domain==MaterialDomain::EngineHousing||Has(n,"engine")){p.semantic=SurfaceSemantic::EngineHousing;p.secondaryPaint=true;p.pattern=true;p.decal=true;p.factionLivery=true;return p;}if(Has(n,"trim")||Has(n,"accent")){p.semantic=SurfaceSemantic::Trim;p.trimPaint=true;p.pattern=true;p.decal=true;p.factionLivery=true;return p;}if(Has(n,"armor")){p.semantic=SurfaceSemantic::Armor;p.primaryPaint=true;p.secondaryPaint=true;p.pattern=true;p.decal=true;p.factionLivery=true;return p;}if(Has(n,"struct")||Has(n,"frame")||Has(n,"steel")||Has(n,"metal")){p.semantic=SurfaceSemantic::StructuralMetal;p.secondaryPaint=true;p.decal=true;return p;}if(Has(n,"weapon")||Has(n,"turret")||Has(n,"barrel")){p.semantic=SurfaceSemantic::WeaponMetal;p.secondaryPaint=true;p.decal=true;return p;}if(Has(n,"sensor")||Has(n,"radar")||Has(n,"antenna")||Has(n,"dish")){p.semantic=SurfaceSemantic::Sensor;p.secondaryPaint=true;return p;}if(Has(n,"decal")){p.semantic=SurfaceSemantic::DecalSurface;p.decal=true;p.factionLivery=true;return p;}p.semantic=SurfaceSemantic::HullPrimary;p.primaryPaint=true;p.secondaryPaint=true;p.trimPaint=true;p.pattern=true;p.decal=true;p.factionLivery=true;p.needsReview=m.name.empty();return p;}
std::vector<SurfaceAuthoringPolicy> CanonicalSurfacePolicySystem::Build(const CanonicalAsset&a){std::vector<SurfaceAuthoringPolicy>o;o.reserve(a.materials.size());for(AssetIndex i=0;i<a.materials.size();++i)o.push_back(Infer(i,a.materials[i],a.assetId));return o;}
} // namespace subspace::assets
