#include "rendering/PlanetWeatherSystem.h"
#include <algorithm>
#include <cmath>
namespace subspace {
namespace {float Unit(std::uint32_t& x){x=x*1664525u+1013904223u;return float((x>>8)&0x00ffffffu)/float(0x01000000u);}PlanetStormKind KindFor(PlanetType t,float u){if(t==PlanetType::GasGiant)return PlanetStormKind::GiantVortex;if(t==PlanetType::Oceanic&&u>.55f)return PlanetStormKind::Cyclone;if(t==PlanetType::Desert)return PlanetStormKind::DustStorm;if(t==PlanetType::Volcanic)return PlanetStormKind::AshFront;if(t==PlanetType::Ice)return PlanetStormKind::IceStorm;return PlanetStormKind::ConvectiveCell;}}
PlanetWeatherState PlanetWeatherSystem::Initialize(const PlanetData& p,std::uint32_t seed){PlanetWeatherState s;s.seed=seed?seed:1;s.volatility=std::clamp(.12f+p.hazardLevel*.62f+(p.type==PlanetType::GasGiant?.22f:0.0f),0.05f,1.0f);std::uint32_t r=s.seed;const int count=1+int(std::round(s.volatility*4.0f));for(int i=0;i<count;++i){PlanetStormCell c;c.id=r;c.kind=KindFor(p.type,Unit(r));c.longitude=Unit(r)*6.2831853f;c.latitude=(Unit(r)-.5f)*2.2f;c.radius=.05f+Unit(r)*(.12f+.10f*s.volatility);c.intensity=.25f+Unit(r)*.65f*s.volatility;c.angularVelocity=(Unit(r)-.5f)*.004f+(c.kind==PlanetStormKind::Cyclone?.006f:0.0f);c.lifetimeSeconds=90.0f+Unit(r)*520.0f;s.storms.push_back(c);}s.seed=r;return s;}
void PlanetWeatherSystem::Advance(PlanetWeatherState& s,const PlanetData& p,double dt){if(dt<=0)return;s.simulationSeconds+=dt;for(auto& c:s.storms){c.ageSeconds+=float(dt);const float jet=.00055f*std::cos(c.latitude*2.0f)*(p.type==PlanetType::GasGiant?3.4f:1.0f);c.longitude=std::fmod(c.longitude+float(dt)*(jet+c.angularVelocity),6.2831853f);if(c.longitude<0)c.longitude+=6.2831853f;const float life=std::clamp(c.ageSeconds/std::max(1.0f,c.lifetimeSeconds),0.0f,1.0f);const float envelope=std::sin(life*3.14159265f);c.intensity=std::clamp(c.intensity*(.998f+.002f*envelope),0.0f,1.0f);}s.storms.erase(std::remove_if(s.storms.begin(),s.storms.end(),[](const auto&c){return c.ageSeconds>=c.lifetimeSeconds;}),s.storms.end());if(s.storms.empty())s=Initialize(p,s.seed+17u);}
float PlanetWeatherSystem::CloudFieldOffset(const PlanetWeatherState& s,float latitude,int layer){const float shear=layer==0?1.0f:-.62f;return float(s.simulationSeconds)*(.0009f+.0006f*std::cos(latitude*2.0f))*shear;}
} // namespace subspace
