#include "rendering/SolarPresentationSystem.h"

#include <algorithm>
#include <cmath>

namespace subspace {

SolarLightProfile SolarPresentationSystem::EvaluateLight(const StarData& star,
                                                         const Vector3& starWorld,
                                                         const Vector3& receiverWorld) {
    SolarLightProfile out;
    Vector3 delta=starWorld-receiverWorld;
    const float distance=std::max(100.0f,delta.length());
    out.direction=delta.length()>0.001f?delta.normalized():Vector3{0.0f,0.0f,1.0f};
    // 2400 renderer-world units corresponds roughly to the inner/mid orbital
    // band generated by the current solar-system grammar. This is intentionally
    // gentler than strict inverse-square so outer-system gameplay remains readable.
    out.normalizedDistance=distance/2400.0f;
    const float attenuation=1.0f/(0.32f+std::pow(std::max(0.18f,out.normalizedDistance),1.30f));
    out.diffuseIntensity=std::clamp(star.luminosity*attenuation,0.16f,2.25f);
    out.ambientIntensity=std::clamp(0.014f+0.018f*std::sqrt(out.diffuseIntensity),0.016f,0.055f);
    return out;
}

StarVisualProfile SolarPresentationSystem::VisualFor(const StarData& star) {
    StarVisualProfile out;
    out.worldRadius=std::clamp(star.radius*0.105f,92.0f,190.0f);
    switch(star.starClass){
        case StarClass::RedDwarf: out.photosphereVariation=.88f;out.prominenceStrength=.52f;break;
        case StarClass::Orange: out.photosphereVariation=.80f;out.prominenceStrength=.44f;break;
        case StarClass::Yellow: out.photosphereVariation=.74f;out.prominenceStrength=.38f;break;
        case StarClass::White: out.photosphereVariation=.62f;out.prominenceStrength=.26f;break;
        case StarClass::BlueWhite: out.photosphereVariation=.54f;out.prominenceStrength=.22f;break;
    }
    out.coronaOuterMultiplier=1.48f+star.luminosity*.08f;
    return out;
}

} // namespace subspace
