set(ROOT "${ROOT}")
function(require_contains FILE NEEDLE)
  file(READ "${ROOT}/${FILE}" CONTENT)
  string(FIND "${CONTENT}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Pass523-532 source gate missing '${NEEDLE}' in ${FILE}")
  endif()
endfunction()

function(require_not_contains FILE NEEDLE)
  file(READ "${ROOT}/${FILE}" CONTENT)
  string(FIND "${CONTENT}" "${NEEDLE}" POS)
  if(NOT POS EQUAL -1)
    message(FATAL_ERROR "Pass523-532 source gate found forbidden '${NEEDLE}' in ${FILE}")
  endif()
endfunction()
require_contains("src/station/StationRuntimeQualitySystem.cpp" "primitiveFallbackAllowed")
require_contains("src/procedural/SolarSystemEcologySystem.cpp" "distributionScore")
require_contains("src/application/NativeBattlefieldRenderer.cpp" "surfaceRotationRate")
require_not_contains("src/application/NativeBattlefieldRenderer.cpp" "return CelestialRenderTier::Far;\n    DrawStationActivity")
require_contains("src/navigation/SystemNavigationSystem.cpp" "distance / this ship's achievable Vector top speed")
require_contains("src/interior/ShipInteriorLayoutSystem.cpp" "Materialize")
require_contains("src/interior/InteriorInteractionSystem.cpp" "CYCLE AIRLOCK")
require_contains("src/hangar/UniversalDockedStationSystem.cpp" "availableServiceTypes")
require_contains("src/ships/ModuleCapabilityDamageSystem.cpp" "ShieldGenerator")
require_contains("src/station/StationActivityPresentationSystem.cpp" "approachLanes")
require_contains("src/ui/RuntimeControlContextSystem.cpp" "SHIP INTERIOR")
message(STATUS "Pass523-532 source authority gate passed")
