file(READ "${ROOT}/include/editor/ConstructionSymmetrySystem.h" SYMH)
file(READ "${ROOT}/src/editor/ConstructionSymmetrySystem.cpp" SYMC)
file(READ "${ROOT}/include/editor/ConstructionEditorCameraSystem.h" CAMH)
file(READ "${ROOT}/src/application/NativeGameApplication.cpp" APPC)
file(READ "${ROOT}/src/application/NativeBattlefieldRenderer.cpp" REND)
file(READ "${ROOT}/include/editor/EditorAssetThumbnailSystem.h" THUMBH)
file(READ "${ROOT}/include/rendering/ProceduralVisualVariantSystem.h" VISUALH)
file(READ "${ROOT}/include/platform/NativeWindow.h" WINDOWH)
file(READ "${ROOT}/src/editor/ProjectWideEditorNormalizationSystem.cpp" NORM)

foreach(token "ConstructionSymmetryFrame" "PortStarboard" "ForeAft" "DorsalVentral" "ReflectPlacement" "ReflectSocket")
  string(FIND "${SYMH}${SYMC}" "${token}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Pass655-664 missing symmetry token: ${token}")
  endif()
endforeach()
foreach(token "ConstructionEditorCameraSystem" "FreeFly" "TruckPedestal" "Dolly")
  string(FIND "${CAMH}" "${token}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Pass665-671 missing camera token: ${token}")
  endif()
endforeach()
foreach(token "IsAltDown" "UpdateConstructionCameraKeyboard" "SetEditorView" "ConstructionEditorCameraSystem::Look" "ConstructionEditorCameraSystem::Roll")
  string(FIND "${WINDOWH}${APPC}" "${token}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Pass665-671 missing runtime camera integration: ${token}")
  endif()
endforeach()
foreach(token "mirrorY" "mirrorZ")
  string(FIND "${VISUALH}" "${token}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Pass658-661 missing persisted mirror axis: ${token}")
  endif()
endforeach()
foreach(token "EditorAssetThumbnailSystem" "thrustLabel" "exhaustLabel" "cacheKey")
  string(FIND "${THUMBH}${REND}" "${token}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Pass672-674 missing thumbnail authority: ${token}")
  endif()
endforeach()
foreach(token "ConstructionSymmetrySystem" "ConstructionEditorCameraSystem" "EditorAssetThumbnailSystem")
  string(FIND "${NORM}" "${token}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Project-wide normalization missing: ${token}")
  endif()
endforeach()
message(STATUS "Pass655-674 symmetry/camera/thumbnail source gate PASS")
