if(NOT DEFINED ROOT)
  message(FATAL_ERROR "Pass746R3 source gate requires -DROOT=<engine-root>")
endif()

get_filename_component(PROJECT_ROOT "${ROOT}/.." ABSOLUTE)
set(TOOLS "${PROJECT_ROOT}/SubspaceTools.ps1")
set(CONTROL "${PROJECT_ROOT}/tools/control/SubspaceControlCenter.ps1")
set(ROOT_AUDIT "${PROJECT_ROOT}/scripts/subspace_root_cleanliness_audit.ps1")
set(GITIGNORE "${PROJECT_ROOT}/.gitignore")

foreach(PATH IN ITEMS "${TOOLS}" "${CONTROL}" "${ROOT_AUDIT}" "${GITIGNORE}")
  if(NOT EXISTS "${PATH}")
    message(FATAL_ERROR "Pass746R3 source gate missing file: ${PATH}")
  endif()
endforeach()

file(READ "${TOOLS}" TOOLS_TEXT)
file(READ "${CONTROL}" CONTROL_TEXT)
file(READ "${ROOT_AUDIT}" AUDIT_TEXT)
file(READ "${GITIGNORE}" IGNORE_TEXT)

function(require_text TEXT_VALUE NEEDLE)
  string(FIND "${TEXT_VALUE}" "${NEEDLE}" FOUND_AT)
  if(FOUND_AT EQUAL -1)
    message(FATAL_ERROR "Pass746R3 source gate missing: ${NEEDLE}")
  endif()
endfunction()

require_text("${TOOLS_TEXT}" "Reset-SubspaceConsolePalette")
require_text("${TOOLS_TEXT}" "Remove-SubspaceAnsiSequences")
require_text("${TOOLS_TEXT}" "Write-ChildOutputLine")
require_text("${TOOLS_TEXT}" "Repair-StaleRootBindingResidue")
require_text("${TOOLS_TEXT}" "Removed stale -Root/artifacts residue")
require_text("${TOOLS_TEXT}" "Join-Path $Global:SubspaceRoot \"artifacts\"")
require_text("${TOOLS_TEXT}" "Join-Path $Global:SubspaceRoot \"-Root\"")
require_text("${CONTROL_TEXT}" "console palette recovery present")
require_text("${CONTROL_TEXT}" "child ANSI reset stripping present")
require_text("${AUDIT_TEXT}" "Stale root-binding artifact exists")
require_text("${IGNORE_TEXT}" "/-Root/")

message(STATUS "Pass746R3 Control Center palette/root-cleanliness source gate PASS")
