file(READ "${ROOT}/src/content/ShipyardModuleSystem.cpp" MOD)
file(READ "${ROOT}/src/core/resources/ObjAssetLoader.cpp" OBJ)
file(READ "${ROOT}/src/application/NativeBattlefieldRenderer.cpp" REN)
if(MOD MATCHES "PushAttached\\(recipe, hullIndex, \\\"port\\\", \\\"placement_role\\\"")
  message(FATAL_ERROR "Pass472 forbids placement_role PCG fallbacks")
endif()
if(MOD MATCHES "dp\\.y = std::max")
  message(FATAL_ERROR "Pass472 forbids post-socket engine translation hacks")
endif()
if(NOT MOD MATCHES "Detached Shipyard attachment gap=")
  message(FATAL_ERROR "Pass472 spatial attachment validation missing")
endif()
if(NOT OBJ MATCHES "TokenizeQuoted")
  message(FATAL_ERROR "Pass472 quoted MTL/OBJ path parser missing")
endif()
if(NOT REN MATCHES "Shipyard materials:")
  message(FATAL_ERROR "Pass472 material coverage telemetry missing")
endif()
message(STATUS "Pass472 Shipyard authority source gate passed")
