if(NOT DEFINED ROOT)
  message(FATAL_ERROR "ROOT is required")
endif()
file(READ "${ROOT}/src/ship_editor/ShipyardBuilderSystem.cpp" BUILDER)
file(READ "${ROOT}/include/ship_editor/ShipyardBuilderSystem.h" BUILDER_H)
file(READ "${ROOT}/src/editor/EditorTransformSpaceSystem.cpp" TRANSFORM)
file(READ "${ROOT}/include/editor/ForgeWorkspaceSystem.h" FORGE_H)
file(READ "${ROOT}/src/editor/ForgeWorkspaceSystem.cpp" FORGE)
file(READ "${ROOT}/src/application/NativeGameApplication.cpp" APP)
file(READ "${ROOT}/src/platform/NativeWindow.cpp" WINDOW)
file(READ "${ROOT}/src/ship_editor/ShipyardWorkspaceSystem.cpp" WORKSPACE)
file(READ "${ROOT}/src/ships/ShipClassGenerationAuthoritySystem.cpp" CLASSGEN)
file(READ "${ROOT}/../project.control.json" PROJECT)

function(require_token text token label)
  string(FIND "${text}" "${token}" pos)
  if(pos EQUAL -1)
    message(FATAL_ERROR "Pass1123-1162 missing ${label}: ${token}")
  endif()
endfunction()

require_token("${BUILDER}" "request.seed=model_.seed" "visible seed generator authority")
require_token("${BUILDER}" "Generated deterministic DRAFT" "safe deterministic draft path")
require_token("${BUILDER}" "previous 28x scale cheat remains forbidden" "unsafe scale quarantine")
require_token("${CLASSGEN}" "IsSafeDraft" "draft safety authority")
require_token("${TRANSFORM}" "WorldToAssemblyDelta" "camera/world-space editor translation")
require_token("${TRANSFORM}" "RenderedRootYawRadians" "complete rendered-root input conversion")
require_token("${APP}" "EditorTransformSpaceSystem::RenderedRootYawRadians" "runtime editor transform bridge")
require_token("${BUILDER_H}" "UndoAuthoring" "global authoring undo")
require_token("${BUILDER_H}" "RedoAuthoring" "global authoring redo")
require_token("${BUILDER}" "PushAuthoringSnapshot" "transaction history snapshots")
require_token("${WINDOW}" "InputAction::Undo" "Ctrl+Z native input bridge")
require_token("${WINDOW}" "InputAction::Redo" "redo native input bridge")
require_token("${FORGE_H}" "Native editor thin client" "native Forge/PCC thin-client authority")
require_token("${FORGE}" "PowerShell script command is not assigned to pwsh/PowerShell" "interpreter guard")
require_token("${FORGE}" "command.executable" "declared command executable preservation")
require_token("${WORKSPACE}" "forge_project_tools" "dockable Forge project-tools panel")
require_token("${WORKSPACE}" "\"history\"" "dockable history panel")
require_token("${PROJECT}" "\"version\": \"1162\"" "current project version")
require_token("${PROJECT}" "SUBSPACE-PASS1123-1162-CORE-AUTHORITY-CONVERGENCE" "current project build identity")
require_token("${PROJECT}" "\"embeddedForgePyGui\": false" "no embedded ForgePY GUI architecture")
require_token("${PROJECT}" "\"defaultTransformSpace\": \"view-camera\"" "view-space default editor movement")
message(STATUS "Pass1123-1162 core authority convergence source gate PASS")
