if(NOT DEFINED ROOT)
  message(FATAL_ERROR "ROOT not supplied")
endif()
file(READ "${ROOT}/src/ship_editor/ShipyardBuilderSystem.cpp" BUILDER)
foreach(token "SOCKETS / CONNECTIONS" "const std::size_t pageSize=5" "moduleCardHeight" "uiScale" "WorkspaceAuthoring")
  string(FIND "${BUILDER}" "${token}" pos)
  if(pos EQUAL -1)
    message(FATAL_ERROR "Pass585-594 builder missing ${token}")
  endif()
endforeach()
file(READ "${ROOT}/src/application/NativeBattlefieldRenderer.cpp" RENDERER)
foreach(token "DrawShipyardModuleThumbnail" "Real geometry asset cards" "Floating contextual tooltip" "TEACH PCG / REUSABLE MODULE DEFINITION")
  string(FIND "${RENDERER}" "${token}" pos)
  if(pos EQUAL -1)
    message(FATAL_ERROR "Pass585-594 renderer missing ${token}")
  endif()
endforeach()
message(STATUS "Pass585-594 visible Shipyard UI/socket recovery source gate PASS")
