# Pass1023-1047 source-level regression gate for visible fidelity and authoring UX.
file(READ "${ROOT}/../SubspaceTools.ps1" PCC)
file(READ "${ROOT}/src/rendering/ImportedPlanetVisualSystem.cpp" PLANET)
file(READ "${ROOT}/src/application/NativeBattlefieldRenderer.cpp" RENDERER)
file(READ "${ROOT}/src/application/NativeGameApplication.cpp" APP)
file(READ "${ROOT}/src/ship_editor/KitbashShipBuilderSystem.cpp" KITBASH)
file(READ "${ROOT}/src/ship_editor/ShipyardBuilderSystem.cpp" BUILDER)
file(READ "${ROOT}/src/content/ShipyardModuleSystem.cpp" MODULES)
file(READ "${ROOT}/src/ships/ShipClassGenerationAuthoritySystem.cpp" CLASSGEN)
file(READ "${ROOT}/src/ships/ShipClassRoleSystem.cpp" CLASSROLE)
file(READ "${ROOT}/include/ships/ShipClassRoleSystem.h" CLASSROLE_H)

set(REQUIRED_PCC
    "Planet texture/cloud fidelity pack"
    "materialize_various_planets.py"
    "Invoke-EnsurePlanetVisualAssets")
foreach(TOKEN IN LISTS REQUIRED_PCC)
    if(NOT PCC MATCHES "${TOKEN}")
        message(FATAL_ERROR "PASS1023-1047 planet fidelity gate missing PCC token: ${TOKEN}")
    endif()
endforeach()

if(NOT PLANET MATCHES "profile.surfaceTexture" OR NOT PLANET MATCHES "profile.cloudTextures")
    message(FATAL_ERROR "PASS1023-1047 imported planet readiness does not verify actual surface/cloud payload")
endif()
if(NOT RENDERER MATCHES "InitializeProceduralShipTextures" OR NOT RENDERER MATCHES "ProceduralShipTextureFor")
    message(FATAL_ERROR "PASS1023-1047 missing procedural fallback material authority for untextured ship regions")
endif()
if((NOT RENDERER MATCHES "ASSET BROWSER" AND NOT RENDERER MATCHES "ASSETS") OR NOT RENDERER MATCHES "OUTLINER" OR NOT RENDERER MATCHES "PROPERTIES" OR NOT RENDERER MATCHES "STAGED PART - NOT ATTACHED")
    message(FATAL_ERROR "PASS1023-1047/1340-1465 visible DCC Shipyard shell/staged-state messaging missing")
endif()
if(NOT APP MATCHES "StageCatalogDrag" OR APP MATCHES "_shipyardCatalogPointerDrag[^\n]*CommitCatalogDrag")
    message(FATAL_ERROR "PASS1023-1047 palette release must stage rather than immediately attach")
endif()
if(NOT BUILDER MATCHES "CONFIRM ATTACH" OR NOT BUILDER MATCHES "CycleStagedSnapCandidate" OR NOT BUILDER MATCHES "toolRailX")
    message(FATAL_ERROR "PASS1023-1047 staged snap workflow / viewport tool rail missing")
endif()
if(NOT MODULES MATCHES "DiscoverFlatSnapSurfaces" OR NOT MODULES MATCHES "surface_" OR NOT MODULES MATCHES "gridColumns")
    message(FATAL_ERROR "PASS1023-1047 dense editor snap fields are not derived from measured contact surfaces")
endif()
if(NOT KITBASH MATCHES "SafeUniformScale" OR KITBASH MATCHES "ShipyardModuleSize::XS: return 0.78f")
    message(FATAL_ERROR "PASS1023-1047 legacy kitbash builder still contains inverted XS-XL scale authority")
endif()
if(NOT CLASSGEN MATCHES "TargetLengthMeters" OR NOT CLASSGEN MATCHES "MeasureLengthMeters" OR NOT CLASSGEN MATCHES "CLASS_SIZE_ENVELOPE_V3")
    message(FATAL_ERROR "PASS1023-1047 class generation does not enforce measurable physical hull envelopes")
endif()
if(NOT CLASSROLE_H MATCHES "minimumModules" OR NOT CLASSROLE MATCHES "ShipClass::Capital")
    message(FATAL_ERROR "PASS1023-1047 ship class envelope/module budget authority missing")
endif()
message(STATUS "Pass1023-1047 visual fidelity, class/scale and Blender Shipyard source gate PASS")
