if(NOT DEFINED ROOT)
  message(FATAL_ERROR "Pass746R6 source gate requires -DROOT=<engine-root>")
endif()

get_filename_component(PROJECT_ROOT "${ROOT}/.." ABSOLUTE)
set(TOOLS "${PROJECT_ROOT}/SubspaceTools.ps1")
set(CONTROL "${PROJECT_ROOT}/tools/control/SubspaceControlCenter.ps1")
set(COMMON "${PROJECT_ROOT}/tools/control/ControlCenterCommon.ps1")
set(REGISTRY "${PROJECT_ROOT}/tools/control/ProjectCommandRegistry.ps1")
set(CLI "${PROJECT_ROOT}/tools/control/ProjectOpsCli.py")
set(SOURCE_AUTH "${PROJECT_ROOT}/tools/control/ProjectSourceAuthority.py")
set(SHELL "${PROJECT_ROOT}/tools/control/ProjectShell.py")
set(GIT_REPAIR "${PROJECT_ROOT}/tools/control/RepairGitWorkingCopy.py")
set(QG "${PROJECT_ROOT}/tools/control/WriteQualityGateRecord.ps1")
set(NORMALIZE "${PROJECT_ROOT}/tools/control/NormalizeGitHubAuthority.ps1")
set(PROJECT_CONTROL "${PROJECT_ROOT}/project.control.json")
set(SOURCE_POLICY "${PROJECT_ROOT}/content/architecture/projectops_source_authority_v1.json")

foreach(PATH IN ITEMS "${TOOLS}" "${CONTROL}" "${COMMON}" "${REGISTRY}" "${CLI}" "${SOURCE_AUTH}" "${SHELL}" "${GIT_REPAIR}" "${QG}" "${NORMALIZE}" "${PROJECT_CONTROL}" "${SOURCE_POLICY}")
  if(NOT EXISTS "${PATH}")
    message(FATAL_ERROR "Pass746R6 source gate missing file: ${PATH}")
  endif()
endforeach()

file(READ "${TOOLS}" TOOLS_TEXT)
file(READ "${CONTROL}" CONTROL_TEXT)
file(READ "${COMMON}" COMMON_TEXT)
file(READ "${REGISTRY}" REGISTRY_TEXT)
file(READ "${CLI}" CLI_TEXT)
file(READ "${SOURCE_AUTH}" SOURCE_TEXT)
file(READ "${SHELL}" SHELL_TEXT)
file(READ "${GIT_REPAIR}" REPAIR_TEXT)
file(READ "${QG}" QG_TEXT)
file(READ "${NORMALIZE}" NORMALIZE_TEXT)
file(READ "${PROJECT_CONTROL}" PROJECT_TEXT)
file(READ "${SOURCE_POLICY}" POLICY_TEXT)

function(require_text TEXT_VALUE NEEDLE)
  string(FIND "${TEXT_VALUE}" "${NEEDLE}" FOUND_AT)
  if(FOUND_AT EQUAL -1)
    message(FATAL_ERROR "Pass746R6 source gate missing: ${NEEDLE}")
  endif()
endfunction()

require_text("${REGISTRY_TEXT}" "project.control.json is missing commands")
require_text("${CLI_TEXT}" "No project.control.json found at or above")
require_text("${CLI_TEXT}" "PROJECTOPS_COMMAND_KEY")
require_text("${CLI_TEXT}" "artifacts/logs")
require_text("${SOURCE_TEXT}" "filesystem-owned source authority")
require_text("${SOURCE_TEXT}" "requiredBootstrapPaths")
require_text("${SHELL_TEXT}" "RUN DESTRUCTIVE COMMAND")
require_text("${REPAIR_TEXT}" "Remote history adopted without overwriting working files")
require_text("${COMMON_TEXT}" "Get-ProjectSourceAuthoritySnapshot")
require_text("${QG_TEXT}" "sourceFingerprint")
require_text("${QG_TEXT}" "sourcePathCount")
require_text("${QG_TEXT}" "sourceAuthorityId")
require_text("${CONTROL_TEXT}" "Governed source bytes/path set changed since the GREEN gate")
require_text("${NORMALIZE_TEXT}" "Governed source bytes/path set changed since the GREEN gate")
require_text("${TOOLS_TEXT}" "ProjectOps governed-source authority")
require_text("${TOOLS_TEXT}" "ProjectOps machine API inspect")
require_text("${TOOLS_TEXT}" "Repair/adopt Git working history without replacing source")
require_text("${PROJECT_TEXT}" "\"machineApi\"")
require_text("${PROJECT_TEXT}" "\"sourceAuthority\"")
require_text("${PROJECT_TEXT}" "\"commandRegistry\"")
require_text("${POLICY_TEXT}" "\"projectops.source-authority.subspace.v1\"")

# Generic ProjectOps implementations must not become another Havenwild-specific layer.
foreach(GENERIC_TEXT IN ITEMS "${REGISTRY_TEXT}" "${CLI_TEXT}" "${SOURCE_TEXT}" "${SHELL_TEXT}" "${REPAIR_TEXT}")
  string(FIND "${GENERIC_TEXT}" "Havenwild" HAVENWILD_LEAK)
  if(NOT HAVENWILD_LEAK EQUAL -1)
    message(FATAL_ERROR "Pass746R6 rejected Havenwild-specific naming in generic ProjectOps tooling")
  endif()
endforeach()

message(STATUS "Pass746R6 Havenwild tooling absorption / ProjectOps machine spine source gate PASS")
