if(NOT DEFINED ROOT)
    message(FATAL_ERROR "ROOT is required")
endif()

function(require_text path needle label)
    file(READ "${path}" text)
    string(FIND "${text}" "${needle}" pos)
    if(pos EQUAL -1)
        message(FATAL_ERROR "Pass595-614 source gate: missing ${label}: ${needle} in ${path}")
    endif()
endfunction()

set(builder "${ROOT}/src/ship_editor/ShipyardBuilderSystem.cpp")
set(renderer "${ROOT}/src/application/NativeBattlefieldRenderer.cpp")
set(app "${ROOT}/src/application/NativeGameApplication.cpp")
set(tools "${ROOT}/../SubspaceTools.ps1")
set(manifest "${ROOT}/../content/kitbash/sources.subspace_sources.json")
set(ensure "${ROOT}/../scripts/subspace_ensure_kitbash_sources.ps1")

foreach(path IN ITEMS "${builder}" "${renderer}" "${app}" "${tools}" "${manifest}" "${ensure}")
    if(NOT EXISTS "${path}")
        message(FATAL_ERROR "Pass595-614 source gate: required file missing: ${path}")
    endif()
endforeach()

require_text("${builder}" "MirrorSelectedSubtreeX" "true mirror builder command")
require_text("${builder}" "FREE BUILD / RELEASE TO PLACE DRAFT" "explicit free-build drag mode")
require_text("${builder}" "HandleWheel" "Shipyard scroll ownership")
require_text("${renderer}" "dragGhost" "visible cursor-carried placement ghost")
require_text("${app}" "wheelOwnedByUi" "UI-before-camera mouse wheel routing")
require_text("${tools}" "subspace_ensure_kitbash_sources.ps1" "Full Gate universal kitbash source intake")
require_text("${manifest}" "PINNED_APPROVED_SOURCES_ONLY" "pinned approved source policy")
require_text("${manifest}" "CC0-1.0" "explicit source licensing")
require_text("${ensure}" "PRESERVE_AUTHORED_OBJECTS" "non-destructive authored-source certification")
require_text("${ROOT}/include/content/UniversalKitbashAuthority.h" "ConstructionDomain" "project-wide construction domains")
require_text("${ROOT}/include/content/UniversalKitbashAuthority.h" "StructuralFree" "normalized kitbash scaling policies")
require_text("${ROOT}/include/ships/ShipClassRoleSystem.h" "BuildDefaultHullFamilies" "four-hull-family faction/class authority")
require_text("${ROOT}/include/ships/ShipFunctionalCoreSystem.h" "ShipFunctionalCapability" "mandatory functional ship core")
require_text("${ROOT}/include/appearance/KitbashAppearanceSystem.h" "ShipSpace" "ship-space coherent appearance projection")
require_text("${ROOT}/include/ships/ShipSpatialAssemblySystem.h" "ShipOccupancyBox" "whole-ship occupancy authority")

message(STATUS "Pass595-614 source gate PASS")
