# Pass1098-1122 generation-foundation emergency normalization source gate.
file(READ "${ROOT}/src/ship_editor/ShipyardBuilderSystem.cpp" BUILDER)
file(READ "${ROOT}/src/ships/ShipClassGenerationAuthoritySystem.cpp" CLASSGEN)
file(READ "${ROOT}/include/ships/ShipClassGenerationAuthoritySystem.h" CLASSGEN_H)
file(READ "${ROOT}/src/generator/GeneratorParitySystem.cpp" PARITY)
file(READ "${ROOT}/include/station/StationKitbashVisualSystem.h" STATION_H)

if(BUILDER MATCHES "bool ShipyardBuilderSystem::GenerateVariant\\(\\)\\{[ \t\r\n]*\\+\\+model_\\.seed")
    message(FATAL_ERROR "PASS1098-1122 GENERATE still mutates the seed")
endif()
foreach(TOKEN IN ITEMS "GENERATION REJECTED" "StableRequestIdentity" "request.domain!=GeneratorDomain::Ship" "model_.pcgStudio.request.seed=model_.seed")
    if(NOT BUILDER MATCHES "${TOKEN}")
        message(FATAL_ERROR "PASS1098-1122 builder normalization token missing: ${TOKEN}")
    endif()
endforeach()
foreach(TOKEN IN ITEMS "MeasureBoundsMeters" "MinimumFinalCorrectionScale" "MaximumFinalCorrectionScale" "MaximumGeneratedInstanceScale" "topology/module-family regeneration" "collapsed below minimum 3D height ratio")
    if(NOT CLASSGEN MATCHES "${TOKEN}" AND NOT CLASSGEN_H MATCHES "${TOKEN}")
        message(FATAL_ERROR "PASS1098-1122 class generation integrity token missing: ${TOKEN}")
    endif()
endforeach()
if(CLASSGEN MATCHES "appliedScale>100\\.0f" OR CLASSGEN MATCHES "appliedScale<\\.05f")
    message(FATAL_ERROR "PASS1098-1122 retired 100x whole-ship scale safety window still active")
endif()
if(NOT PARITY MATCHES "StableRequestIdentity" OR NOT PARITY MATCHES "FNV-1a")
    message(FATAL_ERROR "PASS1098-1122 deterministic generator request identity missing")
endif()
if(NOT STATION_H MATCHES "LEGACY_EXTERIOR_STACKING_PREVIEW" OR NOT STATION_H MATCHES "interior/service programming")
    message(FATAL_ERROR "PASS1098-1122 station stacking generator is not quarantined as a compatibility preview")
endif()
message(STATUS "Pass1098-1122 generation foundation emergency normalization source gate PASS")
