// Focused production-integration acceptance suite for Pass266-295.
#include <iostream>
#include <string>
#include <vector>
#include <unordered_map>
#include <algorithm>

#include "integration/CombatShipIntegration.h"
#include "integration/NavigationMiningIntegration.h"
#include "integration/InfrastructureIndustryIntegration.h"
#include "integration/LivingUniverseIntegration.h"
#include "procedural/GalaxyGenerator.h"
#include "combat/SectorCrisisSystem.h"

using namespace subspace;
static int testsPassed=0;static int testsFailed=0;
#define TEST(name,expr) do { if(expr){testsPassed++;std::cout<<"  PASS: "<<name<<"\n";}else{testsFailed++;std::cout<<"  FAIL: "<<name<<" ("<<__FILE__<<":"<<__LINE__<<")\n";} } while(0)

static ProductionCombatShip MakeCombatShip(){ProductionCombatShip s;s.shipId="cadet-cutter";s.capacity.power=500;s.capacity.heat=500;s.capacity.mass=5000;s.capacity.droneBandwidth=8;s.capacity.hardpoints[(int)FittingHardpointSize::Small]=8;s.capacity.hardpoints[(int)FittingHardpointSize::Medium]=4;s.capacity.hardpoints[(int)FittingHardpointSize::Large]=2;s.capacity.hardpoints[(int)FittingHardpointSize::Utility]=8;s.availablePower=500;return s;}

static void TestPass266CombatFittingUnification(){std::cout<<"[Pass266CombatFittingUnification]\n";FittingSystem fitting;AdvancedCombatSystem combat;ShipFailureSystem failures;DroneOperationsSystem drones(8);CombatShipIntegration integration;auto ship=MakeCombatShip();TEST("Pass266 fitted weapon installs through one authority",integration.Install(ship,"autocannon_s","gun1",fitting,combat,failures,drones));TEST("Pass266 install creates physical subsystem",failures.Get("fit:gun1")!=nullptr);TEST("Pass266 installed weapon creates combat runtime",combat.Get("weapon:gun1")!=nullptr);auto shot=integration.Fire(ship,"gun1",combat,failures);TEST("Pass266 fitted weapon is the firing authority",shot.fired&&shot.damage>0&&ship.availablePower<500);}
static void TestPass267PhysicalDamage(){std::cout<<"[Pass267PhysicalDamage]\n";FittingSystem fitting;AdvancedCombatSystem combat;ShipFailureSystem failures;DroneOperationsSystem drones(8);CombatShipIntegration integration;auto ship=MakeCombatShip();integration.Install(ship,"autocannon_s","gun1",fitting,combat,failures,drones);TEST("Pass267 module damage targets installed subsystem",integration.ApplyModuleDamage(ship,"gun1",200,failures));TEST("Pass267 destroyed visible module becomes disabled",failures.Get("fit:gun1")->state==FailureState::Destroyed);auto shot=integration.Fire(ship,"gun1",combat,failures);TEST("Pass267 destroyed weapon cannot fire",!shot.fired&&shot.reason=="weapon subsystem disabled");TEST("Pass267 unrelated equipment ID cannot be damaged",!integration.ApplyModuleDamage(ship,"missing",10,failures));}
static void TestPass268RepairMaintenance(){std::cout<<"[Pass268RepairMaintenance]\n";FittingSystem fitting;AdvancedCombatSystem combat;ShipFailureSystem failures;DroneOperationsSystem drones(8);CombatShipIntegration integration;EngineeringRepairSystem repairs;repairs.SetResources({100,10,1});auto ship=MakeCombatShip();integration.Install(ship,"autocannon_s","gun1",fitting,combat,failures,drones);integration.ApplyModuleDamage(ship,"gun1",40,failures);double before=failures.Get("fit:gun1")->integrity;TEST("Pass268 repair job binds actual installed module",integration.BeginRepair(ship,"gun1",failures,repairs,20));double restored=integration.AdvanceRepair(ship,"gun1",1,repairs,failures);TEST("Pass268 repair work restores failure authority",restored>0&&failures.Get("fit:gun1")->integrity>before);TEST("Pass268 repair consumes physical spare parts",repairs.Resources().spareParts<100);}
static void TestPass269DroneFitting(){std::cout<<"[Pass269DroneFitting]\n";FittingSystem fitting;AdvancedCombatSystem combat;ShipFailureSystem failures;DroneOperationsSystem drones(8);CombatShipIntegration integration;auto ship=MakeCombatShip();TEST("Pass269 fitted mining-drone bay installs",integration.Install(ship,"mining_drone","bay1",fitting,combat,failures,drones));TEST("Pass269 fitted bay creates physical drone asset",drones.Get("drone:bay1")!=nullptr);TEST("Pass269 fitted drone physically launches",drones.Launch("drone:bay1"));TEST("Pass269 deployed mining drone accepts asteroid job",drones.Assign("drone:bay1","asteroid-22"));drones.Tick(2);TEST("Pass269 mining drone accumulates physical cargo",drones.Get("drone:bay1")->cargo>0);}
static void TestPass270SensorsEwar(){std::cout<<"[Pass270SensorsEwar]\n";FittingSystem fitting;AdvancedCombatSystem combat;ShipFailureSystem failures;DroneOperationsSystem drones(8);CombatShipIntegration integration;ElectronicWarfareSystem ewar;auto ship=MakeCombatShip();integration.Install(ship,"survey_scanner","sensor1",fitting,combat,failures,drones);EnvironmentalExposureReport env;env.sensorPenalty=.25;env.propulsionPenalty=.1;ewar.Apply({"jam",EWarEffectType::SensorJam,.5,10,"pirate"});auto report=integration.EvaluateSensors(ship,ewar,env,failures);TEST("Pass270 environmental and EWAR penalties share sensor authority",report.sensorMultiplier<.5);TEST("Pass270 sensor range is derived from resulting capability",report.range<ship.baseSensorRange);integration.ApplyModuleDamage(ship,"sensor1",30,failures);auto damaged=integration.EvaluateSensors(ship,ewar,env,failures);TEST("Pass270 physical sensor damage further reduces scan range",damaged.range<report.range);}

static GalaxySector MakeRichSector(){GalaxyGenerator g(44021);g.planetProbability=1.0f;g.eventStageProbability=0.0f;g.minPointsOfInterest=6;g.maxPointsOfInterest=6;return g.GenerateSector(2,3,0);}
static void TestPass271SystemMapProduction(){std::cout<<"[Pass271SystemMapProduction]\n";auto sector=MakeRichSector();SystemNavigationSystem nav;NavigationMiningIntegration integration;auto map=integration.BuildMapAndNavigation(sector,nav);TEST("Pass271 system map contains generated celestial/navigation content",!map.nodes.empty());TEST("Pass271 map registration populates shared navigation authority",nav.GetDiscovered().size()>=1);std::size_t known=0;for(auto&n:map.nodes)if(n.known)known++;TEST("Pass271 known map nodes remain intelligence-filtered",known>0);}
static void TestPass272VectorTravelProduction(){std::cout<<"[Pass272VectorTravelProduction]\n";auto sector=MakeRichSector();SystemNavigationSystem nav;NavigationMiningIntegration integration;auto map=integration.BuildMapAndNavigation(sector,nav);std::uint64_t id=0;for(auto&n:map.nodes)if(n.known&&n.warpable){id=n.id;break;}AstronomicalPosition from;auto plan=integration.PlanVector(nav,from,id,8e9,1e9);TEST("Pass272 vector plan resolves shared map destination",id!=0&&plan.valid);VectorTravelSystem travel;VectorTravelSession session;TEST("Pass272 vector travel begins from valid plan",travel.Begin(session,plan));for(int i=0;i<1000&&travel.InTransit(session);++i)travel.Update(session,5);TEST("Pass272 align-charge-cruise-decelerate reaches completion",session.stage==VectorTravelStage::Complete);}
static void TestPass273AstronomicalPresentationIII(){std::cout<<"[Pass273AstronomicalPresentationIII]\n";auto sector=MakeRichSector();NavigationMiningIntegration integration;auto scene=integration.EvaluateLocalCelestials(sector,{0,0,0});TEST("Pass273 local flight renders at most one major celestial disc",scene.majorDiscs.size()<=1);if(!sector.planets.empty()){CelestialEnvironmentSystem celestial;auto profile=celestial.ProfileFor(sector.planets.front());TEST("Pass273 planet presentation remains at least 2.8x baseline",profile.radiusMultiplier>=2.8f);TEST("Pass273 giant local celestial may exceed viewport width",profile.maximumScreenFraction>=1.5f);}else TEST("Pass273 generated acceptance sector contains planets",false);}
static void TestPass274MassiveMiningRegions(){std::cout<<"[Pass274MassiveMiningRegions]\n";BeltMacroRegion belt;belt.id="outer-belt";belt.seed=8877;belt.conceptualCellCount=1500000;belt.conceptualLengthMeters=4e12;belt.localAsteroidBudget=24;RegionStreamingSystem streaming;NavigationMiningIntegration integration;auto state=integration.EnterBelt(belt,{10,20},streaming);TEST("Pass274 huge belt materializes only local asteroid budget",!state.materialized.asteroids.empty()&&state.materialized.asteroids.size()<=24);TEST("Pass274 entered belt cell is permanently surveyed",streaming.IsSurveyed("outer-belt",{10,20}));auto node=state.materialized.asteroids.front().id;TEST("Pass274 local asteroid depletion is persistent",integration.MineNode(state,node,streaming)&&streaming.IsDepleted(node));auto next=integration.NextUnsurveyed(state,streaming,19);TEST("Pass274 player can warp to another unsurveyed belt region",!(next==state.cell));}
static void TestPass275GameplayAcceptanceIII(){std::cout<<"[Pass275GameplayAcceptanceIII]\n";SandboxAcceptanceIIISystem acceptance;SandboxAcceptanceIIIState s;s.physicalCombat=s.physicalDamageRepair=s.dronesSensorsEwar=s.systemMapVector=s.astronomicalScale=s.massiveMiningRegions=true;auto r=acceptance.Evaluate(s);TEST("Pass275 gameplay milestone recognizes completed flight/combat/navigation pillars",r.satisfied==6);TEST("Pass275 does not falsely certify incomplete corporation sandbox",!r.passed&&r.required==18);}

static std::unordered_map<int,double> HugeShipMaterials(){std::unordered_map<int,double> i;for(int n=0;n<32;n++)i[n]=1e7;return i;}
static void TestPass276ShipBuilderProductionII(){std::cout<<"[Pass276ShipBuilderProductionII]\n";InfrastructureIndustryIntegration integration;ShipConstructionSystem construction;auto design=construction.StarterProspector();auto spatial=integration.ValidateShipSpatialContract(design);TEST("Pass276 starter blueprint passes production spatial validation",spatial.valid);ShipProductionWorkflowSystem yard;auto inv=HugeShipMaterials();auto job=integration.QueueShip(design,yard,inv);TEST("Pass276 validated blueprint creates real shipyard job",job!=0&&yard.Get(job)!=nullptr);TEST("Pass276 supplied shipyard job advances beyond waiting materials",yard.Get(job)->state!=ShipyardJobState::WaitingMaterials);}
static void TestPass277InteriorExteriorContract(){std::cout<<"[Pass277InteriorExteriorContract]\n";InfrastructureIndustryIntegration integration;ShipConstructionSystem construction;auto design=construction.StarterScrapper();auto r=integration.ValidateShipSpatialContract(design);TEST("Pass277 exterior volume is explicitly measured",r.exteriorVolume>0);TEST("Pass277 engines/reactor/drone machinery reserve internal volume",r.reservedMachineryVolume>0);TEST("Pass277 usable interior remains distinct from exterior envelope",r.usableInteriorVolume>0&&r.usableInteriorVolume<r.exteriorVolume);}
static StationBuildPlan MakeStationPlan(bool services){StationBuildPlan p;p.name="Frontier Hub";p.placement.kind=StationLocationKind::DeepSpace;p.placement.hasPermission=true;StationBuilderSystem b;b.AddModule(p,{StationModuleType::Core,"core",100,0,0},{0,0});b.AddModule(p,{StationModuleType::Power,"power",80,100,0},{1,0});b.AddModule(p,{StationModuleType::Dock,"dock",60,-10,50},{2,0});if(services){b.AddModule(p,{StationModuleType::Market,"market",60,-8,20},{3,0});b.AddModule(p,{StationModuleType::Repair,"repair",60,-8,10},{4,0});b.AddModule(p,{StationModuleType::Shipyard,"yard",120,-30,100},{5,0});}return p;}
static std::unordered_map<std::string,double> HugeStationMaterials(){return{{"structural_alloy",1e6},{"industrial_electronics",1e6},{"reactor_components",1e6},{"precision_machinery",1e6},{"weapon_components",1e6}};}
static void TestPass278StationBuilderProductionII(){std::cout<<"[Pass278StationBuilderProductionII]\n";StationBuilderSystem builder;auto p=MakeStationPlan(false);auto v=builder.Validate(p);TEST("Pass278 free-space station modules form connected build",v.valid);InfrastructureIndustryIntegration integration;auto inv=HugeStationMaterials();auto result=integration.CommissionStation(p,builder,inv);TEST("Pass278 station construction consumes real material bill",result.commissioned&&result.structuralMaterialConsumed>0);TEST("Pass278 commissioned core/dock emerges as usable outpost",!result.roles.empty());}
static void TestPass279StationOperations(){std::cout<<"[Pass279StationOperations]\n";StationBuilderSystem builder;auto p=MakeStationPlan(true);InfrastructureIndustryIntegration integration;auto inv=HugeStationMaterials();auto result=integration.CommissionStation(p,builder,inv);TEST("Pass279 operational station commissions full service modules",result.commissioned);TEST("Pass279 shipyard module activates shipyard service",result.services.shipyard);TEST("Pass279 market and repair services share station module authority",result.services.market&&result.services.repairHull&&result.services.repairModules);}
static bool BeginViablePlanet(PlanetaryProductionOperation& op,PlanetSurveySystem& survey,PlanetaryIndustrializationSystem& industrial,InfrastructureIndustryIntegration& integration){for(std::uint64_t seed=1;seed<200;seed++)if(integration.BeginPlanetaryOperation(seed,77,"Aurelia",survey,industrial,op))return true;return false;}
static void TestPass280PlanetSurveyProduction(){std::cout<<"[Pass280PlanetSurveyProduction]\n";PlanetSurveySystem s;auto r=s.Generate(22,8,"Prospect");s.Advance(r,PlanetSurveyStage::Detailed);TEST("Pass280 detailed survey exposes physical planet stats",r.gravityG>0&&r.temperatureK>0);TEST("Pass280 survey records resources before investment",r.resources.metals>=0&&r.resources.rareEarths>=0);TEST("Pass280 industrial value requires surveyed planetary data",s.IndustrialValue(r)>=0);}
static void TestPass281SpaceElevatorProduction(){std::cout<<"[Pass281SpaceElevatorProduction]\n";InfrastructureIndustryIntegration integration;PlanetSurveySystem survey;PlanetaryIndustrializationSystem industrial;PlanetaryProductionOperation op;TEST("Pass281 viable planet advances survey->anchor->tether",BeginViablePlanet(op,survey,industrial,integration));std::unordered_map<std::string,double> inv;for(auto&req:industrial.ElevatorBill(op.survey))inv[req.commodity]=req.required+10;TEST("Pass281 delivered BOM completes physical space elevator",integration.BootstrapSpaceElevator(industrial,op,inv));TEST("Pass281 completed elevator unlocks Planetary Manufacturing",op.project.stage==PlanetaryDevelopmentStage::Manufacturing&&op.project.colony.elevatorOnline);}
static void TestPass282PlanetaryManufacturingII(){std::cout<<"[Pass282PlanetaryManufacturingII]\n";InfrastructureIndustryIntegration integration;PlanetSurveySystem survey;PlanetaryIndustrializationSystem industrial;PlanetaryManufacturingSystem manufacturing;PlanetaryProductionOperation op;BeginViablePlanet(op,survey,industrial,integration);std::unordered_map<std::string,double> inv;for(auto&req:industrial.ElevatorBill(op.survey))inv[req.commodity]=req.required;integration.BootstrapSpaceElevator(industrial,op,inv);TEST("Pass282 planetary industrial network is built only after elevator",integration.AddBasicManufacturingNetwork(op,manufacturing));TEST("Pass282 extraction/refining/storage/elevator facilities share one colony",op.project.colony.facilities.size()==4);TEST("Pass282 manufacturing routes carry explicit commodities",manufacturing.RouteThroughput(op.project.colony,"structural_alloy")>0);}
static void TestPass283PlanetaryOrbitalExport(){std::cout<<"[Pass283PlanetaryOrbitalExport]\n";InfrastructureIndustryIntegration integration;PlanetSurveySystem survey;PlanetaryIndustrializationSystem industrial;PlanetaryManufacturingSystem manufacturing;PlanetaryProductionOperation op;BeginViablePlanet(op,survey,industrial,integration);std::unordered_map<std::string,double> inv;for(auto&req:industrial.ElevatorBill(op.survey))inv[req.commodity]=req.required;integration.BootstrapSpaceElevator(industrial,op,inv);integration.AddBasicManufacturingNetwork(op,manufacturing);op.project.colony.inventory["structural_alloy"]=500;LocalEconomySystem economy;LocalEconomyState market;market.id="orbital_hub";economy.Register(market,"structural_alloy",10,100,25);double before=market.commodities["structural_alloy"].stock;double moved=integration.ExportCommodity(op,manufacturing,"structural_alloy",80,market,economy);TEST("Pass283 elevator exports real colony inventory",moved>0&&op.orbitalInventory["structural_alloy"]==moved);TEST("Pass283 orbital export changes causal market supply",market.commodities["structural_alloy"].stock>before);}
static void TestPass284MarketNpcEconomyIntegration(){std::cout<<"[Pass284MarketNpcEconomyIntegration]\n";InfrastructureIndustryIntegration integration;StationPopulationSystem popsys;StationPopulationState pop;pop.stationId="hub";pop.population=500;pop.capacity=800;pop.jobs=400;pop.food=5;pop.supplies=5;pop.serviceCapacity=400;LocalEconomyState market;market.id="hub_market";LocalEconomySystem economy;auto contracts=integration.AdvanceStationEconomy(pop,popsys,market,economy,4);TEST("Pass284 station population creates causal commodity demand",market.commodities.count("food_rations")&&market.commodities.count("station_supplies"));TEST("Pass284 shortages generate actual procurement contracts",contracts.size()>=1);TEST("Pass284 price histories advance with local consumption",market.commodities["food_rations"].priceHistory.size()>=2);}
static void TestPass285InfrastructureAcceptance(){std::cout<<"[Pass285InfrastructureAcceptance]\n";SandboxAcceptanceIIISystem a;SandboxAcceptanceIIIState s;s.shipBuilderProduction=s.stationOperations=s.planetarySurveyElevator=s.planetaryManufacturing=s.causalEconomy=true;auto r=a.Evaluate(s);TEST("Pass285 infrastructure milestone exposes five integrated pillars",r.satisfied==5);TEST("Pass285 infrastructure alone cannot certify full sandbox",!r.passed);}

static void TestPass286FleetCommandProductionII(){std::cout<<"[Pass286FleetCommandProductionII]\n";CorporationOperationsSystem ops;auto wing=ops.CreateWing("Belt Team",FleetWingRole::Mining);TEST("Pass286 creates persistent fleet wing",wing!=0);TEST("Pass286 assigns owned ships to wing",ops.AssignShip(wing,101)&&ops.AssignShip(wing,102));TEST("Pass286 standing mining order is stored on wing",ops.IssueStandingOrder(wing,FleetStandingOrder::MineArea,700)&&ops.GetWing(wing)->order==FleetStandingOrder::MineArea);}
static void TestPass287CrewCaptainProgression(){std::cout<<"[Pass287CrewCaptainProgression]\n";CorporationSystem corp;auto captain=corp.Hire("Mara Venn",CrewSpecialty::FleetOfficer,62,850);TEST("Pass287 hires skilled fleet captain",captain!=0&&corp.Get(captain)->skill==62);TEST("Pass287 captain can be assigned real ship",corp.AssignShip(captain,101)&&corp.Get(captain)->assignedShip==101);TEST("Pass287 permissions are explicit co-op/corporation authority",corp.SetPermission(captain,CorporationPermission::FleetCommand,true)&&corp.HasPermission(captain,CorporationPermission::FleetCommand));TEST("Pass287 salaries contribute to corporation payroll",corp.Payroll()==850);}
static void TestPass288CorporationOperationsII(){std::cout<<"[Pass288CorporationOperationsII]\n";CorporationSystem members;members.Hire("Captain",CrewSpecialty::FleetOfficer,70,900);CorporationOperationsSystem ops;CorporationProgressionSystem progression;CorporationProgressionState state;state.corporationId="cadet-corp";state.assetsValue=2e6;state.ownedShips=6;state.ownedStations=2;state.developedPlanets=1;FleetDoctrineSystem doctrines;FleetDoctrine doctrine;doctrine.id="balanced";doctrine.desiredCombatFraction=.4;doctrine.desiredSupportFraction=.2;doctrine.desiredIndustrialFraction=.2;doctrines.Register(doctrine);std::vector<FleetMember> fleet={{1,"flag",FleetRole::Flagship,1,true},{2,"escort",FleetRole::Combat,1,true},{3,"support",FleetRole::Support,1,true},{4,"miner",FleetRole::Mining,1,true}};CorporationAssetLedger assets;assets.credits=2e6;assets.ships={1,2,3,4,5,6};assets.stations={10,11};assets.planetaryOperations={20};LivingUniverseIntegration integration;auto report=integration.EvaluateCorporation(members,ops,progression,state,assets,doctrines,doctrine,fleet);TEST("Pass288 corporation level derives from owned infrastructure",report.level>=2);TEST("Pass288 fleet doctrine validates corporation fleet",report.doctrineReady);TEST("Pass288 logistics readiness derives from shared asset ledger",report.logisticsReadiness>0);}
static void TestPass289NpcFactionSimulationII(){std::cout<<"[Pass289NpcFactionSimulationII]\n";DynamicFactionSystem factions;DynamicFactionState f;f.id="union";f.resources=150;f.industry=80;f.military=70;factions.Register(f);DynamicSectorState sector;sector.id="frontier";sector.resourcePressure=.8;sector.piratePressure=.2;SectorSimulationSystem sim;LocalEconomyState market;market.id="frontier";LocalEconomySystem economy;economy.Register(market,"station_supplies",20,100,20);MarketContractSystem contracts;PersistentUniverseSystem persistence;LivingUniverseIntegration integration;double before=factions.Get("union")->resources;auto report=integration.AdvanceSector(sector,1,sim,factions,"union",market,economy,contracts,persistence);TEST("Pass289 NPC faction executes strategy during sector simulation",factions.Get("union")->resources!=before);TEST("Pass289 faction activity and sector activity share living economy tick",sector.tick==1&&report.events>=1);}
static void TestPass290DynamicWorldEvents(){std::cout<<"[Pass290DynamicWorldEvents]\n";DynamicFactionSystem factions;DynamicFactionState f;f.id="union";f.resources=120;f.military=80;factions.Register(f);DynamicSectorState sector;sector.id="danger";sector.piratePressure=.9;sector.resourcePressure=.9;sector.security=.3;SectorSimulationSystem sim;LocalEconomyState market;market.id="danger";LocalEconomySystem economy;economy.Register(market,"station_supplies",10,100,20);MarketContractSystem contracts;PersistentUniverseSystem persistence;LivingUniverseIntegration integration;auto r=integration.AdvanceSector(sector,1,sim,factions,"union",market,economy,contracts,persistence);TEST("Pass290 dangerous region emits multiple systemic events",r.events>=2);TEST("Pass290 world events generate player-facing contracts",r.generatedContracts>=2);TEST("Pass290 consequences are written to persistent universe",r.persistentEvents>=2&&persistence.EventCount()>=2);}
static void TestPass291SectorCrisisProduction(){std::cout<<"[Pass291SectorCrisisProduction]\n";SectorCrisisSystem crisis;auto id=crisis.Create(SectorCrisisType::LogisticsCollapse,"Outer Belt Supply Crisis",100);TEST("Pass291 sector crisis is persistent multi-career objective",id!=0);crisis.Contribute(id,CrisisContribution::Mining,25);crisis.Contribute(id,CrisisContribution::Logistics,25);crisis.Contribute(id,CrisisContribution::Combat,25);TEST("Pass291 mining/logistics/combat contributions accumulate together",crisis.Get(id)->progress==75&&!crisis.Get(id)->completed);crisis.Contribute(id,CrisisContribution::Manufacturing,25);TEST("Pass291 noncombat industry can complete regional crisis",crisis.Get(id)->completed);}
static void TestPass292DeepExplorationII(){std::cout<<"[Pass292DeepExplorationII]\n";DeepExplorationSystem deep;DeepExplorationSite site;site.id="vault-17";site.type=DeepSiteType::DataVault;site.scanDifficulty=1;site.danger=.4;site.value=4200;deep.Register(site);deep.Detect("vault-17");deep.Scan("vault-17",10,2);SystemNavigationSystem nav;PersistentUniverseSystem persistence;LivingUniverseIntegration integration;AstronomicalPosition pos;pos.localX=8e9;pos.localY=-3e9;TEST("Pass292 resolved discovery publishes into navigation intelligence",integration.PublishDiscovery(*deep.Get("vault-17"),8801,pos,nav,persistence,"outer"));TEST("Pass292 discovery becomes persistent bookmark",!nav.GetBookmarks().empty());TEST("Pass292 exploration result persists in universe history",persistence.EventCount()==1);}
static void TestPass293SubspaceTearNetwork(){std::cout<<"[Pass293SubspaceTearNetwork]\n";AnomalousSpaceSystem anomalies;auto id=anomalies.Open(AnomalousSpaceType::SubspaceTear,"Sector 12:4",.8,12,5000,.55);SystemNavigationSystem nav;LivingUniverseIntegration integration;AstronomicalPosition pos;pos.localX=9e9;TEST("Pass293 active Subspace tear publishes temporary route",integration.PublishTear(*anomalies.Get(id),pos,nav));auto destinations=nav.GetDiscovered();TEST("Pass293 temporary route appears in discovered navigation",destinations.size()==1&&destinations.front().hazardRating>.5);TEST("Pass293 tear traversal consumes stability/mass authority",anomalies.Traverse(id,1000));anomalies.Tick(13);TEST("Pass293 expired tear collapses instead of permanent shortcut",anomalies.Get(id)->collapsed);}
static void TestPass294PersistenceRecoveryInsuranceII(){std::cout<<"[Pass294PersistenceRecoveryInsuranceII]\n";PersistentUniverseSystem universe;LivingUniverseIntegration integration;RecoveryPolicy policy;policy.insuranceCoverage=.6;policy.wreckRecoveryFraction=.2;policy.rescueFee=500;auto result=integration.RecordLoss("belt-a","ship-44",100000,policy,universe);TEST("Pass294 ship loss produces insurance payout",result.insurancePayout==60000);TEST("Pass294 loss leaves recoverable wreck value",result.recoverableValue==20000&&universe.IsDestroyed("ship-44"));CampaignState campaign;integration.EmbedUniverseLedger(campaign,universe);CampaignPersistenceSystem persistence;SaveGameData save;persistence.WriteToSave(campaign,save);CampaignState loaded;TEST("Pass294 campaign save carries persistent universe ledger",persistence.ReadFromSave(save,loaded)&&!loaded.persistentUniverseLedger.empty());PersistentUniverseSystem restored;TEST("Pass294 restored save recreates destruction history",integration.RestoreUniverseLedger(loaded,restored)&&restored.IsDestroyed("ship-44"));}
static void TestPass295MajorSandboxAcceptanceIII(){std::cout<<"[Pass295MajorSandboxAcceptanceIII]\n";SandboxAcceptanceIIISystem a;SandboxAcceptanceIIIState s;auto missing=a.Evaluate(s);TEST("Pass295 full sandbox acceptance fails closed when integration missing",!missing.passed&&missing.missing.size()==18);s.physicalCombat=s.physicalDamageRepair=s.dronesSensorsEwar=s.systemMapVector=s.astronomicalScale=s.massiveMiningRegions=s.shipBuilderProduction=s.stationOperations=s.planetarySurveyElevator=s.planetaryManufacturing=s.causalEconomy=s.explorationRoutes=s.fleetCrewCorporation=s.dynamicFactions=s.sectorCrises=s.anomalousTravel=s.persistentRecovery=s.saveLedger=true;auto pass=a.Evaluate(s);TEST("Pass295 corporation-scale sandbox closes all eighteen production pillars",pass.passed&&pass.satisfied==18&&pass.missing.empty());s.causalEconomy=false;auto fail=a.Evaluate(s);TEST("Pass295 acceptance detects broken cross-system economy",!fail.passed&&fail.satisfied==17);TEST("Pass295 acceptance remains explicit eighteen-pillar production contract",pass.required==18);}

int main(){
 TestPass266CombatFittingUnification();TestPass267PhysicalDamage();TestPass268RepairMaintenance();TestPass269DroneFitting();TestPass270SensorsEwar();
 TestPass271SystemMapProduction();TestPass272VectorTravelProduction();TestPass273AstronomicalPresentationIII();TestPass274MassiveMiningRegions();TestPass275GameplayAcceptanceIII();
 TestPass276ShipBuilderProductionII();TestPass277InteriorExteriorContract();TestPass278StationBuilderProductionII();TestPass279StationOperations();TestPass280PlanetSurveyProduction();
 TestPass281SpaceElevatorProduction();TestPass282PlanetaryManufacturingII();TestPass283PlanetaryOrbitalExport();TestPass284MarketNpcEconomyIntegration();TestPass285InfrastructureAcceptance();
 TestPass286FleetCommandProductionII();TestPass287CrewCaptainProgression();TestPass288CorporationOperationsII();TestPass289NpcFactionSimulationII();TestPass290DynamicWorldEvents();
 TestPass291SectorCrisisProduction();TestPass292DeepExplorationII();TestPass293SubspaceTearNetwork();TestPass294PersistenceRecoveryInsuranceII();TestPass295MajorSandboxAcceptanceIII();
 std::cout<<"\n=== Pass266-295 Summary: "<<testsPassed<<" passed, "<<testsFailed<<" failed ===\n";return testsFailed?1:0;
}
