if(NOT DEFINED ROOT)
  message(FATAL_ERROR "ROOT is required")
endif()

function(require_text file needle label)
  file(READ "${file}" body)
  string(FIND "${body}" "${needle}" at)
  if(at EQUAL -1)
    message(FATAL_ERROR "Pass497-500 source gate missing ${label}: ${needle}")
  endif()
endfunction()

set(APP "${ROOT}/src/application/NativeGameApplication.cpp")
set(RENDERER "${ROOT}/src/application/NativeBattlefieldRenderer.cpp")
set(BUILDER "${ROOT}/src/ship_editor/ShipyardBuilderSystem.cpp")
set(ORIENT "${ROOT}/src/ship_editor/ShipyardOrientationConstraintSystem.cpp")
set(MODULES "${ROOT}/src/content/ShipyardModuleSystem.cpp")
set(CLASSIFICATION "${ROOT}/include/content/ShipyardSbsClassification.generated.h")
set(TAXONOMY "${ROOT}/src/content/ShipyardPartTaxonomySystem.cpp")

require_text("${APP}" "ddx*ddx+ddy*ddy>=64.0f" "8-pixel catalog drag threshold")
require_text("${APP}" "_shipyardCatalogPointerCandidate" "click-versus-drag candidate state")
require_text("${RENDERER}" "ShipyardPaintZoneSystem::ForMaterial" "semantic material-zone renderer")
require_text("${RENDERER}" "RED MARKER = MOUNT FACE" "selected root-face diagnostic legend")
require_text("${RENDERER}" "candidate.source.moduleId==placement.moduleId" "selected root socket lookup")
require_text("${BUILDER}" "SyncCatalogSelectionToPlaced" "placed/catalog selection synchronization")
require_text("${BUILDER}" "Wing root must attach to a port/starboard hull socket" "wing lateral attachment hard validation")
require_text("${ORIENT}" "ProjectedHalfExtents" "geometry-envelope wing orientation validation")
require_text("${ORIENT}" "Wing is vertically oriented" "vertical-wing rejection")
require_text("${MODULES}" "preferred==\"ventral\"" "preferred wing root-face consumption")
require_text("${CLASSIFICATION}" "{\"miscfinhanger\",\"wing\",\"WING\",97,\"wing/fin-name\",\"LATERAL_STRUCTURE\",true,true,false,\"ventral\",1.00f}" "user-verified wing149 root authority")
require_text("${TAXONOMY}" "dorsalfin" "explicit-only fin taxonomy")

message(STATUS "Pass497-500 Shipyard visual-authority source gate PASS")
