// Forward-facing production acceptance suite for Pass296-315.
#include <iostream>
#include <cmath>
#include <string>

#include "rendering/ForwardSpacePresentationSystem.h"
#include "rendering/CelestialEnvironmentSystem.h"
#include "navigation/TravelArrivalSystem.h"
#include "navigation/SystemNavigationSystem.h"
#include "navigation/VectorTravelSystem.h"
#include "interior/ShipEmbodimentSystem.h"
#include "hangar/DockingExperienceSystem.h"
#include "ui/ProductionInterfaceSystem.h"
#include "procedural/GalaxyGenerator.h"

using namespace subspace;
static int testsPassed=0;static int testsFailed=0;
#define TEST(name,expr) do { if(expr){testsPassed++;std::cout<<"  PASS: "<<name<<"\n";}else{testsFailed++;std::cout<<"  FAIL: "<<name<<" ("<<__FILE__<<":"<<__LINE__<<")\n";} } while(0)

static GalaxySector MakePresentationSector(){GalaxyGenerator g(920315);g.planetProbability=1.0f;g.eventStageProbability=0.0f;g.minPointsOfInterest=6;g.maxPointsOfInterest=6;auto s=g.GenerateSector(4,-2,0);if(!s.planets.empty()){s.planets.front().hasRings=true;s.planets.front().type=PlanetType::GasGiant;}return s;}

static void TestPass296SpaceBackdrop(){std::cout<<"[Pass296SpaceBackdrop]\n";auto sector=MakePresentationSector();ForwardSpacePresentationSystem p;auto bg=p.ForSector(sector);TEST("Pass296 backdrop has ultra-distant stellar layer",bg.ultraDistantStars>=170);TEST("Pass296 backdrop has denser distant stellar layer",bg.distantStars>bg.ultraDistantStars);TEST("Pass296 backdrop reserves local parallax stars",bg.localStars>=90);TEST("Pass296 galactic band remains deliberately subtle",bg.galacticBandStrength>0.0f&&bg.galacticBandStrength<0.20f);TEST("Pass296 local particulate remains restrained",bg.localDust<0.10f);}
static void TestPass297SystemVisualIdentity(){std::cout<<"[Pass297SystemVisualIdentity]\n";ForwardSpacePresentationSystem p;GalaxySector red;red.hasStar=true;red.star.starClass=StarClass::RedDwarf;red.star.colorR=1;red.star.colorB=.3f;red.star.luminosity=.45f;GalaxySector blue=red;blue.star.starClass=StarClass::BlueWhite;blue.star.colorR=.55f;blue.star.colorB=1;blue.star.luminosity=2.5f;auto r=p.ForSector(red),b=p.ForSector(blue);TEST("Pass297 warm and blue systems produce different color bias",r.warmBias>b.warmBias);TEST("Pass297 luminosity affects exposure",b.exposure>r.exposure);TEST("Pass297 exposure stays bounded for readable HUD",b.exposure<=1.22f&&r.exposure>=.82f);}
static void TestPass298ShipHullLanguage(){std::cout<<"[Pass298ShipHullLanguage]\n";ForwardSpacePresentationSystem p;auto industrial=p.ForShip("Industrial Miner",true,.25f);auto combat=p.ForShip("Combat Frigate",false,.25f);TEST("Pass298 industrial silhouette is broader than combat hull",industrial.widthScale>combat.widthScale);TEST("Pass298 industrial hull exposes more machinery",industrial.machineryExposure>combat.machineryExposure);TEST("Pass298 role identity is explicit",industrial.identity=="INDUSTRIAL"&&combat.identity=="COMBAT");TEST("Pass298 close player hull receives high plating breakup",industrial.platingBreakup>=.78f);}
static void TestPass299ShipMaterialsSurfaceDetail(){std::cout<<"[Pass299ShipMaterialsSurfaceDetail]\n";ForwardSpacePresentationSystem p;auto salvage=p.ForShip("Salvage Cutter",false,.20f);auto explorer=p.ForShip("Pathfinder Explorer",false,.20f);TEST("Pass299 salvage hull exposes industrial machinery",salvage.machineryExposure>.6f);TEST("Pass299 exploration hull is visually cleaner",explorer.machineryExposure<salvage.machineryExposure);TEST("Pass299 close ships keep LOD0 surface detail",salvage.lod==0);TEST("Pass299 navigation-light authority remains visible",salvage.navigationLights>0.0f);}
static void TestPass300FunctionalShipVisuals(){std::cout<<"[Pass300FunctionalShipVisuals]\n";ForwardSpacePresentationSystem p;auto combat=p.ForShip("Defender Combat",true,.22f);auto hauler=p.ForShip("Heavy Hauler",false,.22f);TEST("Pass300 combat drive presentation is stronger",combat.thrusterGlow>hauler.thrusterGlow);TEST("Pass300 player navigation lighting is full strength",combat.navigationLights==1.0f);TEST("Pass300 hauler visual length communicates cargo role",hauler.lengthScale>1.2f);}
static void TestPass301ShipClassLod(){std::cout<<"[Pass301ShipClassLod]\n";ForwardSpacePresentationSystem p;TEST("Pass301 hangar/inspection range uses LOD0",p.ForShip("Industrial",true,.30f).lod==0);TEST("Pass301 normal flight can use LOD1",p.ForShip("Industrial",true,.07f).lod==1);TEST("Pass301 tactical fleet range uses LOD2",p.ForShip("Industrial",true,.02f).lod==2);TEST("Pass301 extreme range uses LOD3",p.ForShip("Industrial",true,.005f).lod==3);}

static void TestPass302StationPresentationContext(){std::cout<<"[Pass302StationPresentationContext]\n";ProductionInterfaceSystem ui;auto m=ui.Build(ProductionContextKind::Station,"Axiom Orbital",ShipEmbodimentMode::CockpitControl,DockingExperienceStage::Undocked,false);TEST("Pass302 station has a production context title",m.contextTitle=="Axiom Orbital");TEST("Pass302 station exposes approach/dock actions",m.contextActions.size()>=4&&m.contextActions[0]=="APPROACH"&&m.contextActions[1]=="REQUEST DOCK");TEST("Pass302 station context does not replace flight scanner",m.showScanner);}
static void TestPass303PoiDestinationSemantics(){std::cout<<"[Pass303PoiDestinationSemantics]\n";auto sector=MakePresentationSector();SystemDestination d;d.id=313;d.name="Derelict Refinery";d.type=SystemDestinationType::SalvageSite;d.position.localX=sector.pointsOfInterest.empty()?1e8:sector.pointsOfInterest.front().position.x*1e6;d.position.localY=sector.pointsOfInterest.empty()?2e8:sector.pointsOfInterest.front().position.y*1e6;TravelArrivalSystem arrival;auto a=arrival.Resolve(d,sector,18);TEST("Pass303 POI resolves real local-scene identity",a.valid&&a.localSceneId.find("Derelict Refinery")!=std::string::npos);TEST("Pass303 POI arrival is not target center",std::fabs(a.arrivalWorld.x-a.focalWorld.x)+std::fabs(a.arrivalWorld.y-a.focalWorld.y)>1.0f);TEST("Pass303 POI retains meaningful local final approach",a.finalApproachSeconds>3.0);}
static void TestPass304VectorRetuning(){std::cout<<"[Pass304VectorRetuning]\n";SystemNavigationSystem nav;SystemDestination near;near.id=22;near.name="Near Planet";near.type=SystemDestinationType::Planet;near.position.localX=4e10;nav.RegisterDestination(near);SystemDestination far=near;far.id=23;far.name="Outer Planet";far.position.localX=3e11;nav.RegisterDestination(far);auto nearPlan=nav.PlanWarp({},22,4e9,1e9);auto farPlan=nav.PlanWarp({},23,4e9,1e9);auto slowPlan=nav.PlanWarp({},23,2e9,1e9);auto fastPlan=nav.PlanWarp({},23,8e9,1e9);TEST("Pass304 long in-system charge remains a short anticipation beat",farPlan.valid&&farPlan.chargeSeconds<=2.4);TEST("Pass304 routine charge never becomes instant",farPlan.chargeSeconds>=.85);TEST("Pass304 farther Vector destination takes longer at the same ship top speed",farPlan.cruiseSeconds>nearPlan.cruiseSeconds);TEST("Pass304 faster ship completes the same Vector route sooner",fastPlan.cruiseSeconds<farPlan.cruiseSeconds&&farPlan.cruiseSeconds<slowPlan.cruiseSeconds);TEST("Pass304 Vector cruise is distance divided by ship Vector top speed",std::fabs(farPlan.cruiseSeconds-(farPlan.distanceMeters/farPlan.topSpeedMetersPerSecond))<.001);}
static void TestPass305VectorTunnel(){std::cout<<"[Pass305VectorTunnel]\n";ForwardSpacePresentationSystem p;auto charge=p.VectorVisual(VectorTravelStage::Charging,.70);auto cruise=p.VectorVisual(VectorTravelStage::Cruise,.55);auto exit=p.VectorVisual(VectorTravelStage::Decelerating,.75);TEST("Pass305 charging begins stellar distortion",charge.distortion>0&&charge.starStretch>0);TEST("Pass305 cruise enables full star stretching",cruise.starStretch>=.99f);TEST("Pass305 cruise renders compressed-space tunnel",cruise.tunnelOpacity>.5f);TEST("Pass305 deceleration reveals destination scene",exit.exitReveal>.5f);}
static void TestPass306SafeOrbitalArrival(){std::cout<<"[Pass306SafeOrbitalArrival]\n";auto sector=MakePresentationSector();TEST("Pass306 acceptance sector has planet",!sector.planets.empty());if(sector.planets.empty())return;auto& planet=sector.planets.front();SystemDestination d;d.id=55;d.name=planet.name;d.type=SystemDestinationType::Planet;d.position.localX=planet.position.x*1e6;d.position.localY=planet.position.y*1e6;TravelArrivalSystem arrival;auto a=arrival.Resolve(d,sector,18);CelestialEnvironmentSystem cel;float radius=cel.WorldRadius(planet);float dx=a.arrivalWorld.x-a.focalWorld.x,dy=a.arrivalWorld.y-a.focalWorld.y;float dist=std::sqrt(dx*dx+dy*dy);TEST("Pass306 planet Vector destination resolves orbital environment",a.environment==ArrivalEnvironment::PlanetOrbit);TEST("Pass306 arrival remains outside rendered planet surface",dist>radius);TEST("Pass306 ringed giant arrival also avoids dense ring",a.safeFromDenseRing);TEST("Pass306 orbital arrival points ship toward planet",std::isfinite(a.arrivalYaw));}

static void TestPass307ExplicitCockpitExit(){std::cout<<"[Pass307ExplicitCockpitExit]\n";ShipEmbodimentSystem e;TEST("Pass307 starts seated at cockpit controls",e.IsPiloting());TEST("Pass307 explicit cockpit exit enters on-foot mode",e.ExitCockpit(99)&&e.IsOnFoot());TEST("Pass307 exiting controls retains owning ship",e.Avatar().shipId==99);}
static void TestPass308TopDownInteriorMovement(){std::cout<<"[Pass308TopDownInteriorMovement]\n";ShipEmbodimentSystem e;e.ExitCockpit(99);auto before=e.Avatar().localPosition;e.Move(1,1,.25);auto after=e.Avatar().localPosition;TEST("Pass308 WASD-style movement changes interior avatar position",after.x!=before.x&&after.y!=before.y);for(int i=0;i<100;i++)e.Move(1,1,.1);TEST("Pass308 interior movement remains inside ship bounds",e.Avatar().localPosition.x<=1.75f&&e.Avatar().localPosition.y<=2.15f);TEST("Pass308 on-foot mode is independent of ship piloting",!e.IsPiloting());}
static void TestPass309PhysicalInteriorReturn(){std::cout<<"[Pass309PhysicalInteriorReturn]\n";ShipEmbodimentSystem e;e.ExitCockpit(99);e.Move(-1,1,.25);TEST("Pass309 cannot take controls away from command seat",!e.TakeControls());e=ShipEmbodimentSystem{};e.ExitCockpit(99);TEST("Pass309 player spawns beside command seat",std::fabs(e.Avatar().localPosition.y-1.45f)<.01f);TEST("Pass309 cockpit interaction returns ship control",e.TakeControls()&&e.IsPiloting());}
static void TestPass310CutawaySeparation(){std::cout<<"[Pass310CutawaySeparation]\n";ShipEmbodimentSystem e;TEST("Pass310 camera zoom can never reveal interior",!e.ZoomMayRevealInterior(100.0f));e.SetInspection(true);TEST("Pass310 cutaway is explicit inspection mode",e.Mode()==ShipEmbodimentMode::CutawayInspection);e.SetInspection(false);TEST("Pass310 leaving inspection returns cockpit control",e.Mode()==ShipEmbodimentMode::CockpitControl);e.ExitCockpit(1);e.SetInspection(true);TEST("Pass310 inspection cannot override on-foot interior",e.Mode()==ShipEmbodimentMode::InteriorOnFoot);}

static void TestPass311DockingFlow(){std::cout<<"[Pass311DockingFlow]\n";DockingExperienceSystem dock;DockingExperienceState s;Vector3 station{100,100,0},ship{100,70,0};TEST("Pass311 docking request assigns valid approach",dock.Request(s,7,station,ship,true)&&s.stage==DockingExperienceStage::Requested);auto next=dock.Update(s,ship,.1);TEST("Pass311 docking advances into approach corridor",s.stage==DockingExperienceStage::Approach);TEST("Pass311 autodock moves ship toward assigned approach",next.y>ship.y);}
static void TestPass312HangarExperience(){std::cout<<"[Pass312HangarExperience]\n";DockingExperienceSystem dock;DockingExperienceState s;Vector3 station{0,0,0},ship{0,-30,0};dock.Request(s,7,station,ship,true);for(int i=0;i<200&&s.stage!=DockingExperienceStage::Docked;i++)ship=dock.Update(s,ship,.10);TEST("Pass312 docking capture reaches hangar state",s.stage==DockingExperienceStage::Docked);ShipEmbodimentSystem e;TEST("Pass312 docked ship enters 360-inspection hangar embodiment",e.EnterDockedHangar(9)&&e.Mode()==ShipEmbodimentMode::DockedHangar);TEST("Pass312 player may board same ship interior while docked",e.BoardInterior(9)&&e.IsOnFoot());TEST("Pass312 docked state supports explicit undock request",dock.RequestUndock(s)&&s.stage==DockingExperienceStage::Undocking);}
static void TestPass313UnifiedGui(){std::cout<<"[Pass313UnifiedGui]\n";ProductionInterfaceSystem ui;auto flight=ui.Build(ProductionContextKind::None,"",ShipEmbodimentMode::CockpitControl,DockingExperienceStage::Undocked,false);auto interior=ui.Build(ProductionContextKind::None,"",ShipEmbodimentMode::InteriorOnFoot,DockingExperienceStage::Undocked,false);auto hangar=ui.Build(ProductionContextKind::None,"",ShipEmbodimentMode::DockedHangar,DockingExperienceStage::Docked,false);TEST("Pass313 one UI authority labels flight mode",flight.modeLabel=="FLIGHT");TEST("Pass313 same UI authority labels interior mode",interior.modeLabel=="SHIP INTERIOR");TEST("Pass313 same UI authority labels hangar mode",hangar.modeLabel=="STATION HANGAR");TEST("Pass313 interior suppresses flight scanner and module rack",!interior.showScanner&&!interior.showModuleRack);}
static void TestPass314ContextHud(){std::cout<<"[Pass314ContextHud]\n";ProductionInterfaceSystem ui;auto planet=ui.Build(ProductionContextKind::Planet,"Helios IV",ShipEmbodimentMode::CockpitControl,DockingExperienceStage::Undocked,false);auto asteroid=ui.Build(ProductionContextKind::Asteroid,"rock",ShipEmbodimentMode::CockpitControl,DockingExperienceStage::Undocked,false);auto vector=ui.Build(ProductionContextKind::None,"",ShipEmbodimentMode::CockpitControl,DockingExperienceStage::Undocked,true);TEST("Pass314 selected planet exposes orbit/survey context",planet.contextActions.size()>=3&&planet.contextActions[1]=="SURVEY");TEST("Pass314 selected asteroid exposes mining context",asteroid.contextActions.size()>=3&&asteroid.contextActions[2]=="MINE");TEST("Pass314 Vector transit has dedicated HUD state",vector.modeLabel=="VECTOR TRANSIT");TEST("Pass314 normal flight advertises explicit cockpit exit",!planet.statusLines.empty()&&planet.statusLines.front().find("I EXIT COCKPIT")!=std::string::npos);}
static void TestPass315ForwardFacingAcceptance(){std::cout<<"[Pass315ForwardFacingAcceptance]\n";ForwardSpacePresentationSystem visuals;auto sector=MakePresentationSector();auto sky=visuals.ForSector(sector);auto ship=visuals.ForShip("Industrial",true,.25f);SystemNavigationSystem nav;SystemDestination poi;poi.id=1001;poi.name="Surveyed Wreck";poi.type=SystemDestinationType::SalvageSite;poi.position.localX=8e10;poi.position.localY=-2e10;nav.RegisterDestination(poi);auto plan=nav.PlanWarp({},poi.id,4e9,1e8);VectorTravelSystem travel;VectorTravelSession session;travel.Begin(session,plan);for(int i=0;i<1000&&travel.InTransit(session);++i)travel.Update(session,.1);TravelArrivalSystem arrivals;auto arrival=arrivals.Resolve(poi,sector,18);ShipEmbodimentSystem embodiment;embodiment.ExitCockpit(1);ProductionInterfaceSystem ui;auto hud=ui.Build(ProductionContextKind::Site,poi.name,embodiment.Mode(),DockingExperienceStage::Undocked,false);TEST("Pass315 forward slice includes polished space authority",sky.distantStars>200);TEST("Pass315 forward slice includes refined ship authority",ship.platingBreakup>.7f);TEST("Pass315 forward slice completes visible Vector travel",session.stage==VectorTravelStage::Complete);TEST("Pass315 forward slice exits at real POI approach envelope",arrival.valid&&arrival.finalApproachSeconds>0);TEST("Pass315 forward slice includes embodied ship interior",embodiment.IsOnFoot());TEST("Pass315 forward slice exposes player-facing POI interaction",hud.contextActions.size()>=3);}

int main(){
 TestPass296SpaceBackdrop();TestPass297SystemVisualIdentity();TestPass298ShipHullLanguage();TestPass299ShipMaterialsSurfaceDetail();TestPass300FunctionalShipVisuals();
 TestPass301ShipClassLod();TestPass302StationPresentationContext();TestPass303PoiDestinationSemantics();TestPass304VectorRetuning();TestPass305VectorTunnel();
 TestPass306SafeOrbitalArrival();TestPass307ExplicitCockpitExit();TestPass308TopDownInteriorMovement();TestPass309PhysicalInteriorReturn();TestPass310CutawaySeparation();
 TestPass311DockingFlow();TestPass312HangarExperience();TestPass313UnifiedGui();TestPass314ContextHud();TestPass315ForwardFacingAcceptance();
 std::cout<<"\n=== Pass296-315 Summary: "<<testsPassed<<" passed, "<<testsFailed<<" failed ===\n";return testsFailed?1:0;
}
