if(NOT DEFINED ROOT)
  message(FATAL_ERROR "ROOT is required")
endif()

function(read_required rel out)
  set(path "${ROOT}/${rel}")
  if(NOT EXISTS "${path}")
    message(FATAL_ERROR "Pass555-584 source gate missing ${rel}")
  endif()
  file(READ "${path}" text)
  set(${out} "${text}" PARENT_SCOPE)
endfunction()

read_required("include/station/StationModuleRole.h" station_role)
read_required("include/station/StationConstructionSystem.h" station_construct)
read_required("include/station/ModularStationAssemblySystem.h" modular_station)
read_required("include/station/StationKitbashVisualSystem.h" station_visual_h)
read_required("src/station/StationKitbashVisualSystem.cpp" station_visual_cpp)
read_required("src/station/StationRuntimeQualitySystem.cpp" station_quality)
read_required("src/application/NativeBattlefieldRenderer.cpp" renderer)
read_required("include/assets/CanonicalAsset.h" canonical_asset)
read_required("src/ui/GameUiFramework.cpp" game_ui)
read_required("include/editor/ProjectWideEditorNormalizationSystem.h" normalization_h)
read_required("CMakeLists.txt" cmake_text)

if(station_construct MATCHES "enum class StationModuleType")
  message(FATAL_ERROR "duplicate StationModuleType enum remains")
endif()
if(modular_station MATCHES "enum class StationModuleFunction")
  message(FATAL_ERROR "duplicate StationModuleFunction enum remains")
endif()
if(NOT station_role MATCHES "using StationModuleType = StationModuleRole" OR NOT station_role MATCHES "using StationModuleFunction = StationModuleRole")
  message(FATAL_ERROR "station compatibility aliases do not resolve to StationModuleRole")
endif()
if(NOT station_visual_h MATCHES "std::vector<VisualAssemblyAttachment> attachments" OR NOT station_visual_h MATCHES "primaryDockLocal")
  message(FATAL_ERROR "station visual recipe lacks normalized attachment graph/dock anchor")
endif()
if(NOT station_visual_cpp MATCHES "out.attachments.push_back" OR NOT station_visual_cpp MATCHES "requiredPieces")
  message(FATAL_ERROR "station generator does not build connected grammar-backed assemblies")
endif()
if(NOT station_quality MATCHES "RelatedByJoint" OR NOT station_quality MATCHES "overlapConflicts")
  message(FATAL_ERROR "station QA does not distinguish attached overlap from unrelated collisions")
endif()
if(renderer MATCHES "DrawStationDockingReadability\(p,-6.45f\)" OR renderer MATCHES "DrawStationDockingReadability\(p,-5.65f\)")
  message(FATAL_ERROR "fixed station docking marker offsets remain in runtime renderer")
endif()
if(NOT renderer MATCHES "recipe.primaryDockLocal")
  message(FATAL_ERROR "runtime station docking readability is not anchored to generated recipe")
endif()
if(NOT canonical_asset MATCHES "enum class SurfaceSemantic" OR NOT canonical_asset MATCHES "surfacePolicies")
  message(FATAL_ERROR "CanonicalAsset is missing project-wide surface semantic authority")
endif()
if(NOT game_ui MATCHES "SubspaceUiTheme::Dark")
  message(FATAL_ERROR "GameUiFramework still owns a parallel design-token authority")
endif()
if(NOT cmake_text MATCHES "src/normalization/\\*.cpp")
  message(FATAL_ERROR "normalization source lane is not part of the engine build")
endif()

message(STATUS "Pass555-584 project-wide editor/station source gate PASS")
