if(NOT DEFINED ROOT)
    message(FATAL_ERROR "ROOT is required")
endif()
function(require_text path needle label)
    file(READ "${path}" text)
    string(FIND "${text}" "${needle}" pos)
    if(pos EQUAL -1)
        message(FATAL_ERROR "Pass615-654 source gate: missing ${label}: ${needle} in ${path}")
    endif()
endfunction()
function(forbid_text path needle label)
    file(READ "${path}" text)
    string(FIND "${text}" "${needle}" pos)
    if(NOT pos EQUAL -1)
        message(FATAL_ERROR "Pass615-654 source gate: forbidden duplicate ${label}: ${needle} in ${path}")
    endif()
endfunction()
set(runtime "${ROOT}/src/ships/ShipPcgRuntimeClosureSystem.cpp")
set(builder "${ROOT}/src/ship_editor/ShipyardBuilderSystem.cpp")
set(renderer "${ROOT}/src/application/NativeBattlefieldRenderer.cpp")
set(classrole "${ROOT}/include/ships/ShipClassRoleSystem.h")
set(classauth "${ROOT}/include/ships/ShipClassSystem.h")
set(construction "${ROOT}/include/construction/UniversalConstructionSystem.h")
set(review "${ROOT}/include/content/KitbashReviewCatalogSystem.h")
set(normalization "${ROOT}/src/editor/ProjectWideEditorNormalizationSystem.cpp")
foreach(path IN ITEMS "${runtime}" "${builder}" "${renderer}" "${classrole}" "${classauth}" "${construction}" "${review}" "${normalization}")
    if(NOT EXISTS "${path}")
        message(FATAL_ERROR "Pass615-654 source gate: required file missing: ${path}")
    endif()
endforeach()
require_text("${runtime}" "RepairCandidate" "whole-ship runtime retry/repair authority")
require_text("${runtime}" "BuildExhaustClearance" "propulsion exhaust clearance authority")
require_text("${builder}" "targetModuleSize" "live XS-XL Shipyard placement size")
require_text("${builder}" "CycleConstructionMode" "universal construction-mode selector")
require_text("${builder}" "ClampPlacementToMorphProfile" "morph-profile constrained scaling")
require_text("${renderer}" "ShipPcgRuntimeClosureSystem::RepairCandidate" "one runtime certification lane for generated recipes")
require_text("${construction}" "ConstructionBlueprint" "universal construction blueprint")
require_text("${construction}" "PlanetaryModuleRole" "planetary factory/module vocabulary")
require_text("${review}" "KitbashContentCertificationSummary" "Full Gate kitbash content certification summary")
require_text("${normalization}" "ShipClassAuthority" "project-wide ship-class normalization audit")
require_text("${normalization}" "ShipRoleAuthority" "project-wide ship-role normalization audit")
forbid_text("${classrole}" "enum class ShipClass" "ShipClass authority")
forbid_text("${classrole}" "enum class ShipRole" "ShipRole authority")
require_text("${classauth}" "enum class ShipClass" "single canonical ShipClass enum")
require_text("${classauth}" "enum class ShipRole" "single canonical ShipRole enum")
message(STATUS "Pass615-654 source gate PASS")
