if(NOT DEFINED ROOT)
  message(FATAL_ERROR "Pass746R4 source gate requires -DROOT=<engine-root>")
endif()

get_filename_component(PROJECT_ROOT "${ROOT}/.." ABSOLUTE)
set(TOOLS "${PROJECT_ROOT}/SubspaceTools.ps1")
set(CONTROL "${PROJECT_ROOT}/tools/control/SubspaceControlCenter.ps1")
set(NORMALIZE "${PROJECT_ROOT}/tools/control/NormalizeGitHubAuthority.ps1")
set(COMMON "${PROJECT_ROOT}/tools/control/ProjectOpsCommon.psm1")
set(TREESTAGE "${PROJECT_ROOT}/tools/control/UniversalTreeStage.psm1")
set(CONTRACT "${PROJECT_ROOT}/content/architecture/universal_tree_stage_v1.json")
set(PROJECT_CONTROL "${PROJECT_ROOT}/project.control.json")

foreach(PATH IN ITEMS "${TOOLS}" "${CONTROL}" "${NORMALIZE}" "${COMMON}" "${TREESTAGE}" "${CONTRACT}" "${PROJECT_CONTROL}")
  if(NOT EXISTS "${PATH}")
    message(FATAL_ERROR "Pass746R4 source gate missing file: ${PATH}")
  endif()
endforeach()

file(READ "${TOOLS}" TOOLS_TEXT)
file(READ "${CONTROL}" CONTROL_TEXT)
file(READ "${NORMALIZE}" NORMALIZE_TEXT)
file(READ "${COMMON}" COMMON_TEXT)
file(READ "${TREESTAGE}" TREESTAGE_TEXT)
file(READ "${CONTRACT}" CONTRACT_TEXT)
file(READ "${PROJECT_CONTROL}" PROJECT_CONTROL_TEXT)

function(require_text TEXT_VALUE NEEDLE)
  string(FIND "${TEXT_VALUE}" "${NEEDLE}" FOUND_AT)
  if(FOUND_AT EQUAL -1)
    message(FATAL_ERROR "Pass746R4 source gate missing: ${NEEDLE}")
  endif()
endfunction()

require_text("${TREESTAGE_TEXT}" "function Invoke-UniversalTreeStage")
require_text("${TREESTAGE_TEXT}" "robocopy")
require_text("${TREESTAGE_TEXT}" "0..7 = success")
require_text("${TREESTAGE_TEXT}" "portable-filesystem")
require_text("${TREESTAGE_TEXT}" "$robocopyArgs")
require_text("${TREESTAGE_TEXT}" "$robocopyArgs.ToArray()")
require_text("${TOOLS_TEXT}" "Import-Module $Global:UniversalTreeStageModule")
require_text("${TOOLS_TEXT}" "Invoke-ProjectTreeStage")
# PASS_CLEANCLONE_REPOSITORY_LIFECYCLE_GATE_NORMALIZATION_R5
# Certify repository lifecycle capabilities and dispatch wiring instead of
# obsolete menu numbering/helper names from the earlier Root Utility.
require_text("${TOOLS_TEXT}" "function Show-SourceControlMenu")
require_text("${TOOLS_TEXT}" "repo-authority-prepare")
require_text("${TOOLS_TEXT}" "git-commit-green")
require_text("${TOOLS_TEXT}" "git-push")
require_text("${TOOLS_TEXT}" "repo-authority-audit")
require_text("${TOOLS_TEXT}" "git-repair")
require_text("${TOOLS_TEXT}" "repo-authority-publish")
require_text("${NORMALIZE_TEXT}" "Repository authority PREPARED.")
require_text("${NORMALIZE_TEXT}" "Publish last GREEN normalized main.")
require_text("${TOOLS_TEXT}" "Current operation      : $currentOperation")
require_text("${NORMALIZE_TEXT}" "Invoke-ProjectOpsGovernedTreeStage")
require_text("${COMMON_TEXT}" "Invoke-UniversalTreeStage")
require_text("${COMMON_TEXT}" "Sync-ProjectOpsStageToSourceAuthority")
require_text("${NORMALIZE_TEXT}" "Run-Git -Working $temp -GitArgs")
require_text("${NORMALIZE_TEXT}" "Run-Git -Working $repo -GitArgs")
require_text("${PROJECT_CONTROL_TEXT}" "\"treeStage\"")
require_text("${CONTRACT_TEXT}" "\"projectops.tree-stage.v1\"")

string(FIND "${NORMALIZE_TEXT}" " -Args @(" OLD_ARGS)
if(NOT OLD_ARGS EQUAL -1)
  message(FATAL_ERROR "Pass746R4 rejected stale Run-Git -Args binding")
endif()

# `$args` is a PowerShell automatic variable. A typed declaration here makes
# module import fail before the Control Center can re-enter after patch intake.
string(FIND "${TREESTAGE_TEXT}" "List[string]]$args" RESERVED_ARGS_TYPED)
string(FIND "${TREESTAGE_TEXT}" "$args.Add(" RESERVED_ARGS_MUTATION)
if(NOT RESERVED_ARGS_TYPED EQUAL -1 OR NOT RESERVED_ARGS_MUTATION EQUAL -1)
  message(FATAL_ERROR "Pass746R4 rejected reserved PowerShell automatic variable $args in TreeStage")
endif()

string(FIND "${TOOLS_TEXT}" "function Show-RepositoryLifecycleMenu" RETIRED_REPOSITORY_LIFECYCLE_HELPER)
if(NOT RETIRED_REPOSITORY_LIFECYCLE_HELPER EQUAL -1)
  message(FATAL_ERROR "Pass746R4 rejected retired Show-RepositoryLifecycleMenu helper")
endif()

message(STATUS "Pass746R4 ProjectOps TreeStage / Git authority flow source gate PASS (delegated ProjectOps authority)")
