if(NOT DEFINED ROOT)
  message(FATAL_ERROR "Pass746R6R1 source gate requires -DROOT=<engine-root>")
endif()

get_filename_component(PROJECT_ROOT "${ROOT}/.." ABSOLUTE)
set(TOOLS "${PROJECT_ROOT}/SubspaceTools.ps1")
set(COMMON "${PROJECT_ROOT}/tools/control/ProjectOpsCommon.psm1")
set(COMPAT "${PROJECT_ROOT}/tools/control/ControlCenterCommon.ps1")
set(ROOT_AUDIT "${PROJECT_ROOT}/tools/control/ProjectOpsRootAudit.ps1")
set(ROOT_AUDIT_WRAPPER "${PROJECT_ROOT}/scripts/subspace_root_cleanliness_audit.ps1")
set(MAINTENANCE "${PROJECT_ROOT}/tools/control/ProjectOpsMaintenance.ps1")
set(NORMALIZATION_AUDIT "${PROJECT_ROOT}/tools/control/ProjectOpsNormalizationAudit.ps1")
set(REGISTRY "${PROJECT_ROOT}/tools/control/ProjectCommandRegistry.ps1")
set(NORMALIZE "${PROJECT_ROOT}/tools/control/NormalizeGitHubAuthority.ps1")
set(CONTROL "${PROJECT_ROOT}/tools/control/SubspaceControlCenter.ps1")
set(PROJECT_CONTROL "${PROJECT_ROOT}/project.control.json")
set(SOURCE_POLICY "${PROJECT_ROOT}/content/architecture/projectops_source_authority_v1.json")
set(SOURCE_IMPL "${PROJECT_ROOT}/tools/control/ProjectSourceAuthority.py")
set(DONOR "${PROJECT_ROOT}/content/architecture/projectops_havenwild_absorption_v2.json")

foreach(PATH IN ITEMS "${TOOLS}" "${COMMON}" "${COMPAT}" "${ROOT_AUDIT}" "${ROOT_AUDIT_WRAPPER}"
                      "${MAINTENANCE}" "${NORMALIZATION_AUDIT}" "${REGISTRY}" "${NORMALIZE}" "${CONTROL}"
                      "${PROJECT_CONTROL}" "${SOURCE_POLICY}" "${SOURCE_IMPL}" "${DONOR}")
  if(NOT EXISTS "${PATH}")
    message(FATAL_ERROR "Pass746R6R1 source gate missing file: ${PATH}")
  endif()
endforeach()

file(READ "${TOOLS}" TOOLS_TEXT)
file(READ "${COMMON}" COMMON_TEXT)
file(READ "${COMPAT}" COMPAT_TEXT)
file(READ "${ROOT_AUDIT_WRAPPER}" WRAPPER_TEXT)
file(READ "${MAINTENANCE}" MAINT_TEXT)
file(READ "${NORMALIZATION_AUDIT}" NORMALIZATION_AUDIT_TEXT)
file(READ "${REGISTRY}" REGISTRY_TEXT)
file(READ "${NORMALIZE}" NORMALIZE_TEXT)
file(READ "${CONTROL}" CONTROL_TEXT)
file(READ "${PROJECT_CONTROL}" PROJECT_TEXT)
file(READ "${SOURCE_POLICY}" SOURCE_TEXT)
file(READ "${SOURCE_IMPL}" SOURCE_IMPL_TEXT)
file(READ "${DONOR}" DONOR_TEXT)

function(require_text TEXT_VALUE NEEDLE)
  string(FIND "${TEXT_VALUE}" "${NEEDLE}" FOUND_AT)
  if(FOUND_AT EQUAL -1)
    message(FATAL_ERROR "Pass746R6R1 source gate missing: ${NEEDLE}")
  endif()
endfunction()

require_text("${TOOLS_TEXT}" "ProjectOpsCommon.psm1")
require_text("${TOOLS_TEXT}" "Invoke-ProjectOpsGovernedTreeStage")
require_text("${TOOLS_TEXT}" "Invoke-ProjectOpsRootPolicyMigration")
require_text("${TOOLS_TEXT}" "Remove-ProjectOpsTransientCaches")
require_text("${TOOLS_TEXT}" "Invoke-ProjectOpsCommandRegistryMenu")
require_text("${TOOLS_TEXT}" "projectops-repair")
require_text("${COMMON_TEXT}" "function Invoke-ProjectOpsGovernedTreeStage")
require_text("${COMMON_TEXT}" "function Get-ProjectOpsCommandRegistry")
require_text("${COMMON_TEXT}" "function Invoke-ProjectOpsRootPolicyMigration")
require_text("${COMMON_TEXT}" "Sync-ProjectOpsStageToSourceAuthority")
require_text("${COMMON_TEXT}" "policy.ignoreNamePatterns")
require_text("${COMPAT_TEXT}" "Compatibility adapter")
require_text("${WRAPPER_TEXT}" "ProjectOpsRootAudit.ps1")
require_text("${MAINT_TEXT}" "Remove-ProjectOpsTransientCaches")
require_text("${NORMALIZATION_AUDIT_TEXT}" "PROJECTOPS NORMALIZATION AUDIT")
require_text("${NORMALIZATION_AUDIT_TEXT}" "repository staging has no parallel root source lists")
require_text("${REGISTRY_TEXT}" "Get-ProjectOpsCommandRegistry")
require_text("${NORMALIZE_TEXT}" "Invoke-ProjectOpsGovernedTreeStage")
require_text("${PROJECT_TEXT}" "\"rootPolicy\"")
require_text("${PROJECT_TEXT}" "\"maintenance.repair\"")
require_text("${PROJECT_TEXT}" "\"audit.normalization\"")
require_text("${PROJECT_TEXT}" "ProjectOpsCommon.psm1")
require_text("${SOURCE_TEXT}" "docs/passes/")
require_text("${SOURCE_TEXT}" "tools/control/ProjectOpsCommon.psm1")
require_text("${SOURCE_TEXT}" "\"pythonCachesForbidden\": true")
require_text("${SOURCE_TEXT}" "\"ignoreNamePatterns\"")
require_text("${SOURCE_IMPL_TEXT}" "fnmatch.fnmatch")
require_text("${DONOR_TEXT}" "projectops.havenwild-absorption.subspace.v2")
require_text("${DONOR_TEXT}" "No second source-enumeration policy")

# Retired parallel source enumeration must not come back in repository staging.
foreach(OLD_TOKEN IN ITEMS "$rootFiles" "$rootDirs" "Copy-NormalizedDirectory" "Test-ExcludedRelative")
  string(FIND "${NORMALIZE_TEXT}" "${OLD_TOKEN}" OLD_AT)
  if(NOT OLD_AT EQUAL -1)
    message(FATAL_ERROR "Pass746R6R1 rejected parallel repository source authority: ${OLD_TOKEN}")
  endif()
endforeach()

# Root/control PowerShell may not assign to automatic $args and may not use the
# invalid colon interpolation that broke R6 re-entry.
foreach(TEXT_TO_SCAN IN ITEMS "${TOOLS_TEXT}" "${COMMON_TEXT}" "${COMPAT_TEXT}" "${MAINT_TEXT}" "${REGISTRY_TEXT}" "${NORMALIZE_TEXT}" "${CONTROL_TEXT}")
  string(REGEX MATCH "(^|[\r\n])[ \t]*\\$args[ \t]*=" RESERVED_ARGS_ASSIGN "${TEXT_TO_SCAN}")
  if(RESERVED_ARGS_ASSIGN)
    message(FATAL_ERROR "Pass746R6R1 rejected assignment to PowerShell automatic variable $args")
  endif()
  string(FIND "${TEXT_TO_SCAN}" "$LASTEXITCODE:" BAD_EXIT_INTERPOLATION)
  if(NOT BAD_EXIT_INTERPOLATION EQUAL -1)
    message(FATAL_ERROR "Pass746R6R1 rejected invalid $LASTEXITCODE: interpolation")
  endif()
endforeach()

file(GLOB_RECURSE CONTROL_PYC RELATIVE "${PROJECT_ROOT}" "${PROJECT_ROOT}/tools/control/*.pyc")
file(GLOB_RECURSE CONTROL_CACHE RELATIVE "${PROJECT_ROOT}" "${PROJECT_ROOT}/tools/control/__pycache__/*")
if(CONTROL_PYC OR CONTROL_CACHE)
  message(FATAL_ERROR "Pass746R6R1 rejected generated Python bytecode/cache under tools/control")
endif()

message(STATUS "Pass746R6R1 Havenwild root-tooling refactor source gate PASS")
