if(NOT EXISTS "${APP_SOURCE}")
  message(FATAL_ERROR "Pass468 app source missing: ${APP_SOURCE}")
endif()
file(READ "${APP_SOURCE}" APP_TEXT)
string(FIND "${APP_TEXT}" "HandleFrontendActions();" FRONT_CALL)
string(FIND "${APP_TEXT}" "HandleGlobalActions();" GLOBAL_CALL)
if(FRONT_CALL LESS 0 OR GLOBAL_CALL LESS 0)
  message(FATAL_ERROR "Pass468 could not locate frontend/global input calls")
endif()
if(NOT FRONT_CALL LESS GLOBAL_CALL)
  message(FATAL_ERROR "Pass468 regression: global input router runs before frontend")
endif()
string(FIND "${APP_TEXT}" "if(!inGame)return; // frontend must be the sole pointer-input owner outside gameplay" GUARD)
if(GUARD LESS 0)
  message(FATAL_ERROR "Pass468 frontend pointer-ownership guard missing")
endif()
message(STATUS "Pass468 frontend pointer routing gate passed")
