file(READ "${ROOT}/src/ship_editor/ShipyardBuilderSystem.cpp" BUILDER)
file(READ "${ROOT}/src/application/NativeGameApplication.cpp" APP)
file(READ "${ROOT}/src/application/NativeBattlefieldRenderer.cpp" RENDER)
file(READ "${ROOT}/src/ship_editor/ShipyardSocketOverrideSystem.cpp" OVERRIDE)
foreach(token "BeginSelectedSocketTransform" "TranslateSelectedSocket" "RotateSelectedSocket" "ReflowRecipeAttachments" "Cannot delete socket while an attachment uses it")
  string(FIND "${BUILDER}" "${token}" at)
  if(at EQUAL -1)
    message(FATAL_ERROR "Pass533B source gate missing socket authoring token: ${token}")
  endif()
endforeach()
foreach(token "_shipyardPointerTransform" "TranslateSelectedSocket" "RotateSelectedSocket" "SaveCurrentShipyardSocketOverrides" "LoadCurrentShipyardSocketOverrides")
  string(FIND "${APP}" "${token}" at)
  if(at EQUAL -1)
    message(FATAL_ERROR "Pass533B source gate missing in-game socket edit integration: ${token}")
  endif()
endforeach()
foreach(token "socketEdit" "selectedSocketIndex" "socket.dirX")
  string(FIND "${RENDER}" "${token}" at)
  if(at EQUAL -1)
    message(FATAL_ERROR "Pass533B source gate missing 3D socket authoring overlay: ${token}")
  endif()
endforeach()
string(FIND "${OVERRIDE}" "SUBSPACE_SHIPYARD_SOCKET_OVERRIDES_V1" format_at)
if(format_at EQUAL -1)
  message(FATAL_ERROR "Pass533B source gate missing versioned persistent socket override format")
endif()
