if(NOT DEFINED ROOT)
  message(FATAL_ERROR "Pass746R5 source gate requires -DROOT=<engine-root>")
endif()

get_filename_component(PROJECT_ROOT "${ROOT}/.." ABSOLUTE)
set(TOOLS "${PROJECT_ROOT}/SubspaceTools.ps1")
set(CONTROL "${PROJECT_ROOT}/tools/control/SubspaceControlCenter.ps1")
set(NORMALIZE "${PROJECT_ROOT}/tools/control/NormalizeGitHubAuthority.ps1")
set(QG "${PROJECT_ROOT}/tools/control/WriteQualityGateRecord.ps1")
set(ROOT_AUDIT "${PROJECT_ROOT}/scripts/subspace_root_cleanliness_audit.ps1")
set(INSTALLER "${PROJECT_ROOT}/scripts/install_subspace_root_utility.ps1")
set(PROJECT_CONTROL "${PROJECT_ROOT}/project.control.json")
set(CONTRACT "${PROJECT_ROOT}/content/architecture/universal_artifact_layout_v1.json")

foreach(PATH IN ITEMS "${TOOLS}" "${CONTROL}" "${NORMALIZE}" "${QG}" "${ROOT_AUDIT}" "${INSTALLER}" "${PROJECT_CONTROL}" "${CONTRACT}")
  if(NOT EXISTS "${PATH}")
    message(FATAL_ERROR "Pass746R5 source gate missing file: ${PATH}")
  endif()
endforeach()

file(READ "${TOOLS}" TOOLS_TEXT)
file(READ "${CONTROL}" CONTROL_TEXT)
file(READ "${NORMALIZE}" NORMALIZE_TEXT)
file(READ "${QG}" QG_TEXT)
file(READ "${ROOT_AUDIT}" AUDIT_TEXT)
file(READ "${INSTALLER}" INSTALLER_TEXT)
file(READ "${PROJECT_CONTROL}" PROJECT_TEXT)
file(READ "${CONTRACT}" CONTRACT_TEXT)

function(require_text TEXT_VALUE NEEDLE)
  string(FIND "${TEXT_VALUE}" "${NEEDLE}" FOUND_AT)
  if(FOUND_AT EQUAL -1)
    message(FATAL_ERROR "Pass746R5 source gate missing: ${NEEDLE}")
  endif()
endfunction()

require_text("${TOOLS_TEXT}" "Join-Path $Global:ArtifactRoot \"debug\"")
require_text("${TOOLS_TEXT}" "Join-Path $Global:ArtifactRoot \"source\"")
require_text("${TOOLS_TEXT}" "Join-Path $Global:ArtifactRoot \"assets\"")
require_text("${TOOLS_TEXT}" "Join-Path $Global:ArtifactRoot \"snapshots\\source\"")
require_text("${TOOLS_TEXT}" "Join-Path $Global:ArtifactRoot \"gates\\quality\"")
require_text("${TOOLS_TEXT}" "Join-Path $Global:ArtifactRoot \"logs\"")
require_text("${TOOLS_TEXT}" "Join-Path $Global:ArtifactRoot \"temp\"")
require_text("${TOOLS_TEXT}" "function Invoke-LegacyArtifactLayoutMigration")
require_text("${TOOLS_TEXT}" "function Open-DebugHandoffFolder")
require_text("${TOOLS_TEXT}" "/select,")
require_text("${TOOLS_TEXT}" "Drag that ZIP directly into the ChatGPT conversation.")
require_text("${CONTROL_TEXT}" "Join-Path $artifactRoot 'baselines'")
require_text("${CONTROL_TEXT}" "Join-Path $artifactRoot 'audits'")
require_text("${NORMALIZE_TEXT}" "artifacts\\temp\\repository-normalization")
require_text("${NORMALIZE_TEXT}" "$PSNativeCommandUseErrorActionPreference=$false")
require_text("${QG_TEXT}" "artifacts\\gates\\quality")
require_text("${AUDIT_TEXT}" "Legacy generated-output root exists outside artifacts")
require_text("${INSTALLER_TEXT}" "artifacts\\root-utility\\LATEST_ROOT_UTILITY_INSTALL.txt")
require_text("${PROJECT_TEXT}" "\"artifactLayout\"")
require_text("${CONTRACT_TEXT}" "\"projectops.artifact-layout.v1\"")

string(FIND "${TOOLS_TEXT}" "$Global:DebugBundleRoot = Join-Path $Global:SubspaceRoot \"dist\\debug\"" OLD_DEBUG)
string(FIND "${TOOLS_TEXT}" "$Global:SourceBundleRoot = Join-Path $Global:SubspaceRoot \"dist\\source\"" OLD_SOURCE)
string(FIND "${TOOLS_TEXT}" "$Global:AssetBundleRoot = Join-Path $Global:SubspaceRoot \"dist\\assets\"" OLD_ASSETS)
string(FIND "${TOOLS_TEXT}" "$Global:LogsRoot = Join-Path $Global:SubspaceRoot \"logs\"" OLD_LOGS)
if(NOT OLD_DEBUG EQUAL -1 OR NOT OLD_SOURCE EQUAL -1 OR NOT OLD_ASSETS EQUAL -1 OR NOT OLD_LOGS EQUAL -1)
  message(FATAL_ERROR "Pass746R5 rejected legacy canonical artifact-root assignments")
endif()

message(STATUS "Pass746R5 artifact authority / failure handoff source gate PASS")
