file(READ "${ROOT}/src/application/NativeBattlefieldRenderer.cpp" REN)
file(READ "${ROOT}/src/application/NativeGameApplication.cpp" APP)
file(READ "${ROOT}/src/content/ShipyardModuleSystem.cpp" MOD)
file(READ "${ROOT}/src/ship_editor/ShipBlueprintLibrarySystem.cpp" BP)
file(READ "${ROOT}/src/ship_editor/ShipyardDesignExchangeSystem.cpp" EX)
file(READ "${ROOT}/include/rendering/PlanetPresentationSystem.h" PLANET)
file(READ "${ROOT}/../tools/blender/SubspaceShipyard/__init__.py" BLENDER)

if(NOT REN MATCHES "RecipeForwardVisualYawRadians")
  message(FATAL_ERROR "Pass473 renderer does not consume recipe visual-forward authority")
endif()
if(NOT REN MATCHES "DrawShipyardSelectionOverlay")
  message(FATAL_ERROR "Pass473 selected-module viewport highlight missing")
endif()
if(NOT REN MATCHES "PickShipyardModule")
  message(FATAL_ERROR "Pass473 Shipyard viewport picking missing")
endif()
if(NOT APP MATCHES "ShipyardBuilderCommand::SelectPlaced,picked")
  message(FATAL_ERROR "Pass473 viewport pick is not synchronized back to the assembled-module selection")
endif()
if(NOT MOD MATCHES "Mirrored pair orientation mismatch")
  message(FATAL_ERROR "Pass473 mirror forward-orientation validation missing")
endif()
if(NOT BP MATCHES "ORIENTATION ")
  message(FATAL_ERROR "Pass473 native blueprint orientation persistence missing")
endif()
if(NOT EX MATCHES "canonicalForward")
  message(FATAL_ERROR "Pass473 Blender/design exchange orientation metadata missing")
endif()
if(NOT REN MATCHES "visible reinforcement")
  message(FATAL_ERROR "Pass473 visible procedural cloud reinforcement missing")
endif()
if(NOT REN MATCHES "wantsClouds")
  message(FATAL_ERROR "Pass473 imported clouds may still suppress visible weather")
endif()
if(NOT PLANET MATCHES "g2\\*g2\\*g")
  message(FATAL_ERROR "Pass473 atmosphere limb was not tightened")
endif()
if(NOT BLENDER MATCHES "mirrorX")
  message(FATAL_ERROR "Pass473 Blender interchange does not preserve true mirrored-module handedness")
endif()
message(STATUS "Pass473 orientation / selection / cloud source gate passed")
