#include "ships/CapitalConstructionSystem.h"
#include <algorithm>
namespace subspace {
std::uint64_t CapitalConstructionSystem::Start(CapitalHullType h,const std::unordered_map<std::string,double>& mats,double work){if(mats.empty()||work<=0)return 0;auto id=nextId_++;CapitalBuildJob j;j.id=id;j.hull=h;j.required=mats;j.workRemaining=work;j.totalWork=work;jobs_[id]=j;return id;}
double CapitalConstructionSystem::Deliver(std::uint64_t id,const std::string& m,double a){auto it=jobs_.find(id);if(it==jobs_.end()||a<=0)return 0;auto req=it->second.required.find(m);if(req==it->second.required.end())return 0;double need=std::max(0.0,req->second-it->second.delivered[m]);double d=std::min(need,a);it->second.delivered[m]+=d;return d;}
bool CapitalConstructionSystem::MaterialsReady(std::uint64_t id) const {auto it=jobs_.find(id);if(it==jobs_.end())return false;for(auto& req:it->second.required){auto d=it->second.delivered.find(req.first);if(d==it->second.delivered.end()||d->second+1e-9<req.second)return false;}return true;}
double CapitalConstructionSystem::Advance(std::uint64_t id,double work){auto it=jobs_.find(id);if(it==jobs_.end()||work<=0||!MaterialsReady(id)||it->second.complete)return 0;double done=std::min(work,it->second.workRemaining);it->second.workRemaining-=done;double completeFraction=it->second.totalWork>0?1.0-it->second.workRemaining/it->second.totalWork:1.0;if(it->second.workRemaining<=0){it->second.workRemaining=0;it->second.stage=CapitalBuildStage::Complete;it->second.complete=true;}else {if(completeFraction>0.8)it->second.stage=CapitalBuildStage::Commissioning;else if(completeFraction>0.6)it->second.stage=CapitalBuildStage::Fitting;else if(completeFraction>0.4)it->second.stage=CapitalBuildStage::Systems;else if(completeFraction>0.2)it->second.stage=CapitalBuildStage::Propulsion;}return done;}
const CapitalBuildJob* CapitalConstructionSystem::Get(std::uint64_t id) const {auto it=jobs_.find(id);return it==jobs_.end()?nullptr:&it->second;}
}
