#include "ships/FittingSystem.h"

#include <algorithm>

namespace subspace {
FittingSystem::FittingSystem(){auto add=[&](const char*id,const char*n,EquipmentCategory c,FittingHardpointSize s,double p,double h,double m,double r,double t){equipment_[id]={id,n,c,s,p,h,m,r,t};};add("autocannon_s","Light Autocannon",EquipmentCategory::Kinetic,FittingHardpointSize::Small,8,10,22,1400,1.0);add("railgun_m","Medium Railgun",EquipmentCategory::Kinetic,FittingHardpointSize::Medium,24,28,65,5200,.35);add("beam_m","Focused Beam",EquipmentCategory::Energy,FittingHardpointSize::Medium,30,32,58,3600,.6);add("missile_s","Guided Missile Rack",EquipmentCategory::Missile,FittingHardpointSize::Small,10,7,28,6500,.5);add("torpedo_l","Heavy Torpedo Tube",EquipmentCategory::Missile,FittingHardpointSize::Large,32,16,120,11000,.15);add("point_defense_s","Point Defense Turret",EquipmentCategory::PointDefense,FittingHardpointSize::Small,9,8,24,900,1.8);add("mining_laser_s","Mining Laser",EquipmentCategory::Mining,FittingHardpointSize::Small,12,16,26,900,.4);add("strip_miner_m","Strip Mining Turret",EquipmentCategory::Mining,FittingHardpointSize::Medium,28,38,74,1300,.22);add("salvage_beam_s","Salvage Beam",EquipmentCategory::Salvage,FittingHardpointSize::Small,10,12,24,700,.5);add("tractor_s","Tractor Array",EquipmentCategory::Tractor,FittingHardpointSize::Utility,7,5,18,1200,.7);add("combat_drone","Combat Drone Bay",EquipmentCategory::CombatDrone,FittingHardpointSize::Utility,12,8,42,4200,.7);add("mining_drone","Mining Drone Bay",EquipmentCategory::MiningDrone,FittingHardpointSize::Utility,10,7,40,2500,.5);add("salvage_drone","Salvage Drone Bay",EquipmentCategory::SalvageDrone,FittingHardpointSize::Utility,10,7,40,2200,.5);add("repair_drone","Repair Drone Bay",EquipmentCategory::RepairDrone,FittingHardpointSize::Utility,14,10,44,1800,.4);add("cargo_drone","Cargo Drone Bay",EquipmentCategory::CargoDrone,FittingHardpointSize::Utility,8,5,38,3000,.3);add("jammer_s","Sensor Jammer",EquipmentCategory::EWar,FittingHardpointSize::Utility,18,10,20,5000,.2);add("target_painter","Target Painter",EquipmentCategory::EWar,FittingHardpointSize::Utility,9,6,14,6000,.5);add("remote_repair","Remote Repair Projector",EquipmentCategory::FleetSupport,FittingHardpointSize::Utility,20,25,35,2200,.4);add("shield_s","Shield Generator",EquipmentCategory::Shield,FittingHardpointSize::Utility,22,14,60,0,0);add("survey_scanner","Deep Survey Scanner",EquipmentCategory::Sensor,FittingHardpointSize::Utility,8,4,18,20000,0);}
const EquipmentDefinitionNative* FittingSystem::Get(const std::string&id)const{auto it=equipment_.find(id);return it==equipment_.end()?nullptr:&it->second;}
std::vector<EquipmentDefinitionNative> FittingSystem::Catalog()const{std::vector<EquipmentDefinitionNative>o;for(const auto&kv:equipment_)o.push_back(kv.second);return o;}
FittingResult FittingSystem::CanInstall(const FittingCapacity& c,const std::vector<std::string>& fitted,const std::string& id)const{auto*d=Get(id);if(!d)return{false,"unknown equipment"};double p=0,h=0,m=0;std::unordered_map<int,int> used;for(const auto&f:fitted){auto*x=Get(f);if(!x)continue;p+=x->power;h+=x->heat;m+=x->mass;++used[static_cast<int>(x->size)];}p+=d->power;h+=d->heat;m+=d->mass;++used[static_cast<int>(d->size)];if(p>c.power)return{false,"power capacity exceeded"};if(h>c.heat)return{false,"heat capacity exceeded"};if(m>c.mass)return{false,"mass envelope exceeded"};auto cap=c.hardpoints.find(static_cast<int>(d->size));if(cap==c.hardpoints.end()||used[static_cast<int>(d->size)]>cap->second)return{false,"hardpoint unavailable"};return{true,{}};}
} // namespace subspace
