#include "ships/ShipConstructionSystem.h"

#include <algorithm>

namespace subspace {
namespace {
ShipModuleBlueprintNative M(const char* id,ShipModuleFamily f,double mass,double power,std::initializer_list<MaterialRequirement> mats){ShipModuleBlueprintNative m;m.id=id;m.family=f;m.mass=mass;m.powerDraw=power;m.materials=mats;return m;}
}
ShipBillOfMaterials ShipConstructionSystem::BuildBill(const ModularShipDesign& d) const { ShipBillOfMaterials b;for(const auto& m:d.modules){b.totalMass+=m.mass;b.totalPowerDraw+=m.powerDraw;b.totalHeat+=m.heat;for(const auto& r:m.materials)b.quantities[static_cast<int>(r.material)]+=r.quantity;}b.constructionMinutes=std::max(2.0,b.totalMass/40.0+static_cast<double>(d.modules.size())*.35);return b; }
ShipConstructionValidation ShipConstructionSystem::Validate(const ModularShipDesign& d) const { ShipConstructionValidation v;auto has=[&](ShipModuleFamily f){return std::any_of(d.modules.begin(),d.modules.end(),[&](const auto&m){return m.family==f;});};for(auto req:{ShipModuleFamily::Command,ShipModuleFamily::MainDrive,ShipModuleFamily::ManeuverThruster,ShipModuleFamily::Reactor,ShipModuleFamily::Cargo,ShipModuleFamily::Furnace,ShipModuleFamily::FieldFabricator})if(!has(req))v.errors.push_back("missing required module family "+std::to_string(static_cast<int>(req)));int maneuver=0;for(const auto&m:d.modules)if(m.family==ShipModuleFamily::ManeuverThruster)++maneuver;if(maneuver<4)v.warnings.push_back("limited maneuvering authority");v.valid=v.errors.empty();return v; }
ModularShipDesign ShipConstructionSystem::StarterProspector() const { ModularShipDesign d;d.name="Prospector Cutter";d.modules={M("command",ShipModuleFamily::Command,90,6,{{ConstructionMaterial::StructuralSteel,40},{ConstructionMaterial::Electronics,8}}),M("drive",ShipModuleFamily::MainDrive,130,18,{{ConstructionMaterial::StructuralSteel,55},{ConstructionMaterial::Motors,8}}),M("reactor",ShipModuleFamily::Reactor,120,-80,{{ConstructionMaterial::StructuralSteel,35},{ConstructionMaterial::Copper,18},{ConstructionMaterial::Capacitors,4}}),M("cargo",ShipModuleFamily::Cargo,80,1,{{ConstructionMaterial::StructuralSteel,45}}),M("furnace",ShipModuleFamily::Furnace,65,8,{{ConstructionMaterial::StructuralSteel,25},{ConstructionMaterial::CeramicComposite,8}}),M("fabricator",ShipModuleFamily::FieldFabricator,55,10,{{ConstructionMaterial::StructuralSteel,20},{ConstructionMaterial::Electronics,6},{ConstructionMaterial::Motors,3}}),M("industrial",ShipModuleFamily::IndustrialHardpoint,25,2,{{ConstructionMaterial::StructuralSteel,12}})};for(int i=0;i<4;++i)d.modules.push_back(M(("rcs"+std::to_string(i)).c_str(),ShipModuleFamily::ManeuverThruster,12,3,{{ConstructionMaterial::StructuralSteel,4},{ConstructionMaterial::Motors,1}}));return d; }
ModularShipDesign ShipConstructionSystem::StarterScrapper() const {auto d=StarterProspector();d.name="Scrapper Cutter";d.modules.push_back(M("salvage_drone_bay",ShipModuleFamily::DroneBay,36,6,{{ConstructionMaterial::StructuralSteel,14},{ConstructionMaterial::Electronics,4},{ConstructionMaterial::Motors,2}}));return d; }
std::string ShipConstructionSystem::MaterialName(ConstructionMaterial m){switch(m){case ConstructionMaterial::StructuralSteel:return"Structural Steel";case ConstructionMaterial::TitaniumAlloy:return"Titanium Alloy";case ConstructionMaterial::CeramicComposite:return"Ceramic Composite";case ConstructionMaterial::RadiationComposite:return"Radiation Composite";case ConstructionMaterial::Copper:return"Copper";case ConstructionMaterial::Electronics:return"Electronics";case ConstructionMaterial::Motors:return"Motors";case ConstructionMaterial::Capacitors:return"Capacitors";case ConstructionMaterial::Optics:return"Optics";case ConstructionMaterial::Superconductor:return"Superconductor";case ConstructionMaterial::Polymer:return"Polymer";case ConstructionMaterial::RareMetals:return"Rare Metals";}return"Unknown";}
} // namespace subspace
