#include "ships/ShipProfileDirector.h"
#include <algorithm>
#include <cmath>

namespace subspace {
namespace {std::uint32_t Mix(std::uint32_t x){x^=x>>16;x*=0x7feb352dU;x^=x>>15;x*=0x846ca68bU;x^=x>>16;return x?x:1;} float Unit(std::uint32_t x){return (Mix(x)&0xffff)/65535.0f;}}
const char* ShipProfileDirector::CockpitName(CockpitFamily f){switch(f){case CockpitFamily::Wedge:return"Wedge";case CockpitFamily::ArmoredBridge:return"Armored Bridge";case CockpitFamily::RecessedMilitary:return"Recessed Military";case CockpitFamily::IndustrialTower:return"Industrial Tower";case CockpitFamily::InterceptorCanopy:return"Interceptor Canopy";case CockpitFamily::SplitCommand:return"Split Command";case CockpitFamily::SensorForward:return"Sensor Forward";default:return"Heavy Command Deck";}}
ShipProfileGrammar ShipProfileDirector::Build(ShipRoleProfile role,std::uint32_t seed) const {ShipProfileGrammar g;g.role=role;static const char* makers[]={"HELIX","IRONWORKS","ORBITAL FORGE","NOMAD","IRON DOMINION","VANGUARD"};g.manufacturer=makers[Mix(seed)%6];const int cockpitBase=int(Mix(seed+19)%8);g.cockpit=static_cast<CockpitFamily>(cockpitBase);switch(role){case ShipRoleProfile::Combat:g={role,g.cockpit,g.manufacturer,.20f,.43f,.13f,.24f,.48f,.22f,.02f,true,0};break;case ShipRoleProfile::Hauler:g={role,g.cockpit,g.manufacturer,.11f,.24f,.44f,.21f,.58f,.15f,.04f,false,0};break;case ShipRoleProfile::Mining:g={role,g.cockpit,g.manufacturer,.13f,.30f,.34f,.23f,.64f,.25f,.10f,true,0};break;case ShipRoleProfile::Salvage:g={role,g.cockpit,g.manufacturer,.14f,.31f,.32f,.23f,.62f,.30f,.24f,true,0};break;case ShipRoleProfile::Industrial:g={role,g.cockpit,g.manufacturer,.12f,.34f,.31f,.23f,.60f,.22f,.10f,false,0};break;case ShipRoleProfile::Exploration:g={role,g.cockpit,g.manufacturer,.23f,.37f,.18f,.22f,.36f,.28f,.04f,true,0};break;case ShipRoleProfile::Carrier:g={role,g.cockpit,g.manufacturer,.12f,.48f,.20f,.20f,.78f,.34f,.06f,true,0};break;case ShipRoleProfile::Patrol:g={role,g.cockpit,g.manufacturer,.21f,.41f,.14f,.24f,.43f,.22f,.02f,false,0};break;default:g={role,g.cockpit,g.manufacturer,.18f,.40f,.20f,.22f,.46f,.20f,.06f,false,0};break;}g.widthToLength=std::clamp(g.widthToLength+(Unit(seed+5)-.5f)*.08f,.28f,.86f);g.negativeSpace=std::clamp(g.negativeSpace+(Unit(seed+9)-.5f)*.08f,.10f,.42f);std::vector<std::string> e;Validate(g,&e);g.profileScore=100-int(e.size())*12;return g;}
bool ShipProfileDirector::Validate(const ShipProfileGrammar& g,std::vector<std::string>* errors) const {std::vector<std::string> e;const float total=g.noseRatio+g.hullRatio+g.utilityRatio+g.propulsionRatio;if(std::fabs(total-1.0f)>.03f)e.push_back("profile ratios do not close");if(g.noseRatio<.08f)e.push_back("command section buried");if(g.propulsionRatio<.16f)e.push_back("propulsion silhouette too small");if(g.negativeSpace<.10f)e.push_back("silhouette lacks negative space");if(g.widthToLength<.25f||g.widthToLength>.9f)e.push_back("profile aspect invalid");if(g.asymmetry>.30f)e.push_back("asymmetry exceeds visual balance");if(errors)*errors=e;return e.empty();}
} // namespace subspace
