#include "world/PlanetWorldEngineSystem.h"

#include <algorithm>
#include <cmath>

namespace subspace {
namespace {
float Hash01(std::uint64_t seed,int x,int y,int salt){std::uint64_t h=seed^std::uint64_t(std::uint32_t(x))*0x9E3779B185EBCA87ULL^std::uint64_t(std::uint32_t(y))*0xC2B2AE3D27D4EB4FULL^std::uint64_t(salt+1)*0x165667B19E3779F9ULL;h^=h>>33;h*=0xff51afd7ed558ccdULL;h^=h>>33;h*=0xc4ceb9fe1a85ec53ULL;h^=h>>33;return float(h&0xFFFFFFULL)/float(0xFFFFFFULL);}
float Smooth(float t){return t*t*(3.0f-2.0f*t);}
float Noise2(std::uint64_t seed,float x,float y,float frequency,int salt){const float fx=x*frequency,fy=y*frequency;const int ix=int(std::floor(fx)),iy=int(std::floor(fy));const float tx=Smooth(fx-float(ix)),ty=Smooth(fy-float(iy));const float a=Hash01(seed,ix,iy,salt),b=Hash01(seed,ix+1,iy,salt),c=Hash01(seed,ix,iy+1,salt),d=Hash01(seed,ix+1,iy+1,salt);const float ab=a+(b-a)*tx,cd=c+(d-c)*tx;return (ab+(cd-ab)*ty)*2.0f-1.0f;}
float Falloff(const TerraformOperation&o,float x,float y){const float dx=x-o.center.x,dy=y-o.center.y,d=std::sqrt(dx*dx+dy*dy);if(d>=o.radiusMeters)return 0;const float t=1.0f-d/std::max(.001f,o.radiusMeters);const float exponent=std::clamp(1.0f+o.falloff*3.0f,1.0f,4.0f);return std::pow(t,exponent);}
}

float PlanetWorldEngineSystem::BaseHeight(const PlanetWorldDefinition&w,float x,float y){const float macro=Noise2(w.seed,x,y,w.macroFrequency,3);const float ridges=std::fabs(Noise2(w.seed,x,y,w.macroFrequency*2.7f,11))*2.0f-1.0f;const float detail=Noise2(w.seed,x,y,w.detailFrequency,29);float h=(macro*.70f+ridges*.22f+detail*.08f)*w.elevationAmplitudeMeters;h*=1.0f-std::clamp(w.erosionStrength,0.0f,1.0f)*.18f;return h;}
float PlanetWorldEngineSystem::TerraformDeltaAt(const TerraformDeltaLayer&layer,float x,float y){float d=0;for(const auto&o:layer.operations){const float f=Falloff(o,x,y);if(f<=0)continue;switch(o.type){case TerraformOperationType::Raise:case TerraformOperationType::Fill:d+=std::fabs(o.strengthMeters)*f;break;case TerraformOperationType::Lower:case TerraformOperationType::Excavation:d-=std::fabs(o.strengthMeters)*f;break;case TerraformOperationType::Flatten:{const float current=d;d+=(o.targetHeightMeters-current)*f;break;}case TerraformOperationType::Terrace:{const float step=std::max(.25f,std::fabs(o.strengthMeters));d=(std::round(d/step)*step)*f+d*(1.0f-f);break;}default:break;}}return d;}
TerrainSample PlanetWorldEngineSystem::Sample(const PlanetWorldDefinition&w,const TerraformDeltaLayer&layer,float x,float y){TerrainSample s;s.localPosition={x,y,0};s.baseHeightMeters=BaseHeight(w,x,y);float d=0;for(const auto&o:layer.operations){const float f=Falloff(o,x,y);if(f<=0)continue;switch(o.type){case TerraformOperationType::Flatten:d+=(o.targetHeightMeters-(s.baseHeightMeters+d))*f;break;case TerraformOperationType::Raise:case TerraformOperationType::Fill:d+=std::fabs(o.strengthMeters)*f;break;case TerraformOperationType::Lower:case TerraformOperationType::Excavation:d-=std::fabs(o.strengthMeters)*f;break;case TerraformOperationType::Terrace:{const float step=std::max(.25f,std::fabs(o.strengthMeters));const float target=std::round((s.baseHeightMeters+d)/step)*step;d+=(target-(s.baseHeightMeters+d))*f;break;}default:break;}if((o.type==TerraformOperationType::MaterialPaint||o.type==TerraformOperationType::BiomePaint)&&!o.materialId.empty()&&f>.5f){if(o.type==TerraformOperationType::MaterialPaint)s.surfaceMaterial=o.materialId;else s.biome=o.materialId;}}
s.terraformDeltaMeters=d;s.finalHeightMeters=s.baseHeightMeters+d;s.moisture=std::clamp(w.moisture+Noise2(w.seed,x,y,w.macroFrequency*.7f,41)*.22f,0.0f,1.0f);s.temperatureKelvin=w.temperatureKelvin-s.finalHeightMeters*.0065f;if(s.biome=="Barren"){if(s.finalHeightMeters<w.seaLevelMeters&&w.hasHydrosphere)s.biome="Ocean";else if(s.temperatureKelvin<250)s.biome="Ice";else if(s.moisture>.65f)s.biome="Wetland";else if(s.moisture>.42f)s.biome="Temperate";else if(s.moisture<.18f)s.biome="Desert";else s.biome="Steppe";}return s;}
PlanetTerrainChunk PlanetWorldEngineSystem::BuildChunk(const PlanetWorldDefinition&w,const TerraformDeltaLayer&layer,Vector3 origin,float size,std::uint32_t resolution){PlanetTerrainChunk c;c.origin=origin;c.sizeMeters=std::max(1.0f,size);c.resolution=std::clamp<std::uint32_t>(resolution,2,513);c.sourceRevision=layer.revision;c.id=w.planetId+".chunk."+std::to_string(int(std::floor(origin.x/c.sizeMeters)))+"."+std::to_string(int(std::floor(origin.y/c.sizeMeters)));c.heights.reserve(std::size_t(c.resolution)*c.resolution);for(std::uint32_t y=0;y<c.resolution;++y)for(std::uint32_t x=0;x<c.resolution;++x){const float fx=float(x)/float(c.resolution-1),fy=float(y)/float(c.resolution-1);c.heights.push_back(Sample(w,layer,origin.x+fx*c.sizeMeters,origin.y+fy*c.sizeMeters).finalHeightMeters);}return c;}
bool PlanetWorldEngineSystem::ApplyOperation(TerraformDeltaLayer&layer,TerraformOperation o){if(o.radiusMeters<=0)return false;if(o.id==0)o.id=layer.revision+1;layer.operations.push_back(std::move(o));++layer.revision;return true;}
FoundationGradePlan PlanetWorldEngineSystem::PlanFoundationGrade(const PlanetWorldDefinition&w,const TerraformDeltaLayer&layer,Vector3 center,Vector3 footprint,const std::string&owner){FoundationGradePlan p;const float hx=std::max(1.0f,std::fabs(footprint.x)*.5f),hy=std::max(1.0f,std::fabs(footprint.y)*.5f);float sum=0,minH=1e30f,maxH=-1e30f;constexpr int n=5;for(int iy=0;iy<n;++iy)for(int ix=0;ix<n;++ix){const float x=center.x-hx+2*hx*float(ix)/float(n-1),y=center.y-hy+2*hy*float(iy)/float(n-1);const float h=Sample(w,layer,x,y).finalHeightMeters;sum+=h;minH=std::min(minH,h);maxH=std::max(maxH,h);}p.targetHeightMeters=sum/float(n*n);p.estimatedSlope=(maxH-minH)/std::max(1.0f,std::max(hx*2,hy*2));const float area=(hx*2)*(hy*2);p.excavationCubicMeters=std::max(0.0f,maxH-p.targetHeightMeters)*area*.35f;p.fillCubicMeters=std::max(0.0f,p.targetHeightMeters-minH)*area*.35f;TerraformOperation op;op.type=TerraformOperationType::Flatten;op.center=center;op.radiusMeters=std::sqrt(hx*hx+hy*hy);op.targetHeightMeters=p.targetHeightMeters;op.strengthMeters=maxH-minH;op.ownerFactionId=owner;op.gameplayAuthorized=false;p.operations.push_back(op);if(p.estimatedSlope>.30f)p.warnings.push_back("Foundation grade is steep and should require heavy excavation equipment");if(!w.terraformable)p.warnings.push_back("World definition does not permit runtime terraforming");p.valid=w.terraformable;return p;}
const char* PlanetWorldEngineSystem::BrushName(WorldBrushMode m){switch(m){case WorldBrushMode::Raise:return "RAISE";case WorldBrushMode::Lower:return "LOWER";case WorldBrushMode::Smooth:return "SMOOTH";case WorldBrushMode::Flatten:return "FLATTEN";case WorldBrushMode::Terrace:return "TERRACE";case WorldBrushMode::Erode:return "ERODE";case WorldBrushMode::Noise:return "NOISE";case WorldBrushMode::PaintSurface:return "SURFACE";case WorldBrushMode::PaintBiome:return "BIOME";case WorldBrushMode::PaintResource:return "RESOURCE";case WorldBrushMode::River:return "RIVER";case WorldBrushMode::Lake:return "LAKE";case WorldBrushMode::Canal:return "CANAL";}return "WORLD";}
const char* PlanetWorldEngineSystem::TerraformName(TerraformOperationType t){switch(t){case TerraformOperationType::Raise:return "RAISE";case TerraformOperationType::Lower:return "LOWER";case TerraformOperationType::Flatten:return "FLATTEN";case TerraformOperationType::Smooth:return "SMOOTH";case TerraformOperationType::Terrace:return "TERRACE";case TerraformOperationType::Excavation:return "EXCAVATE";case TerraformOperationType::Fill:return "FILL";case TerraformOperationType::MaterialPaint:return "MATERIAL";case TerraformOperationType::BiomePaint:return "BIOME";case TerraformOperationType::ResourceOverride:return "RESOURCE";case TerraformOperationType::WaterLevel:return "WATER";case TerraformOperationType::Canal:return "CANAL";}return "TERRAFORM";}

} // namespace subspace
