#include "station/StationWorkspaceSystem.h"
#include "station/StationModuleRole.h"
#include <algorithm>

namespace subspace {
EditorWorkspaceDescriptor StationWorkspaceSystem::Descriptor(){return{EditorWorkspaceKind::StationBuilder,"station_builder","Station Builder","Build, operate and author connected modular stations using the shared Subspace editor shell.",true,true};}
std::vector<EditorAssetCard> StationWorkspaceSystem::BuildAssetCards(const std::vector<StationKitbashPiece>& pieces){std::vector<EditorAssetCard>out;out.reserve(pieces.size());for(const auto&p:pieces){EditorAssetCard c;c.assetId=p.id;c.displayName=p.displayName;c.category=p.structural?"STRUCTURE":StationModuleRoleName(p.function);c.previewKey=p.sourceModuleId;c.subtitle=StationModuleRoleName(p.function);c.tags={p.structural?"structural":"functional",p.radialFriendly?"radial":"linear"};c.enabled=p.generatorEligible;c.disabledReason=p.generatorEligible?"":"No certified source geometry is available for this logical station piece";if(!p.generatorEligible)c.badge="REVIEW";out.push_back(std::move(c));}return out;}
std::vector<EditorOutlinerNode> StationWorkspaceSystem::BuildOutliner(const StationKitbashVisualRecipe&r){std::vector<EditorOutlinerNode>out;out.push_back({"station.root","",r.identity,"Station",true,false});for(std::size_t i=0;i<r.modules.size();++i){std::string parent="station.root";for(const auto&a:r.attachments)if(a.childModuleIndex==i){parent="station.module."+std::to_string(a.parentModuleIndex);break;}const std::string label=i<r.logicalPieceIds.size()?r.logicalPieceIds[i]:r.modules[i].moduleId;out.push_back({"station.module."+std::to_string(i),parent,label,"StationModule",true,false});}return out;}
std::vector<EditorPropertySection> StationWorkspaceSystem::BuildInspector(const StationKitbashVisualRecipe&r,std::size_t i,StationWorkspaceMode mode,bool advanced){std::vector<EditorPropertySection>out;EditorPropertySection summary{"summary","Summary",false,false,{}};summary.properties.push_back({"identity","Station",EditorPropertyType::ReadOnly,r.identity,"","station.summary",true,false});summary.properties.push_back({"grammar","Grammar",EditorPropertyType::ReadOnly,r.grammarId,"","station.grammar",true,false});summary.properties.push_back({"modules","Modules",EditorPropertyType::ReadOnly,std::to_string(r.modules.size()),"","station.modules",true,false});out.push_back(std::move(summary));if(i<r.modules.size()){EditorPropertySection sel{"selection","Selected Module",false,false,{}};sel.properties.push_back({"module","Source",EditorPropertyType::ReadOnly,r.modules[i].moduleId,"","station.source",true,false});if(i<r.logicalPieceIds.size())sel.properties.push_back({"piece","Piece",EditorPropertyType::ReadOnly,r.logicalPieceIds[i],"","station.piece",true,false});sel.properties.push_back({"position","Position",EditorPropertyType::ReadOnly,std::to_string(r.modules[i].x)+", "+std::to_string(r.modules[i].y)+", "+std::to_string(r.modules[i].z),"","station.position",true,false});out.push_back(std::move(sel));}if(mode==StationWorkspaceMode::Authoring||advanced){EditorPropertySection graph{"graph","Assembly Graph",false,true,{}};graph.properties.push_back({"connected","Connected",EditorPropertyType::ReadOnly,r.connectedGraph?"YES":"NO","","station.connected",true,true});graph.properties.push_back({"attachments","Attachments",EditorPropertyType::ReadOnly,std::to_string(r.attachments.size()),"","station.attachments",true,true});graph.properties.push_back({"dock","Dock Anchor",EditorPropertyType::ReadOnly,r.usedDedicatedDock?"CONNECTED":"MISSING","","station.dock",true,true});out.push_back(std::move(graph));}return out;}
EditorHelpRegistry StationWorkspaceSystem::BuildHelpRegistry(){EditorHelpRegistry h;h.Register({"station.summary","STATION SUMMARY","High-level station identity and current generated grammar.","The Station Builder uses the same project-wide editor shell as Shipyard. Build mode keeps raw attachment metadata hidden.",""});h.Register({"station.grammar","DESIGN GRAMMAR","The deterministic station layout family used by PCG.","Each station archetype owns structural and functional requirements. Authoring can promote approved station exemplars into reusable design families.",""});h.Register({"station.connected","CONNECTED GRAPH","Whether every visual station module reaches the root through a certified attachment.","Generated stations fail certification when any visual module is floating or unrelated to the root graph.",""});h.Register({"station.dock","DOCK ANCHOR","The physical docking interface generated as part of the station.","Docking markers and approach readability follow this generated module instead of a fixed screen/world offset.",""});return h;}
} // namespace subspace
