#include "station/StationEcologySystem.h"
#include <algorithm>

namespace subspace {
namespace {std::uint64_t Mix(std::uint64_t x){x^=x>>30;x*=0xbf58476d1ce4e5b9ULL;x^=x>>27;x*=0x94d049bb133111ebULL;x^=x>>31;return x?x:1;}}
const char* StationEcologySystem::ArchetypeName(StationArchetype t){switch(t){case StationArchetype::TradeHub:return"Trade Hub";case StationArchetype::IndustrialRefinery:return"Industrial Refinery";case StationArchetype::MiningDepot:return"Mining Depot";case StationArchetype::Shipyard:return"Shipyard";case StationArchetype::Military:return"Military Installation";case StationArchetype::Research:return"Research Station";case StationArchetype::TetherTerminal:return"Orbital Tether";case StationArchetype::FrontierOutpost:return"Frontier Outpost";case StationArchetype::AsteroidStation:return"Asteroid Station";default:return"Corporate Headquarters";}}
GeneratedStationProfile StationEcologySystem::BuildAsteroidStation(std::uint64_t seed,int tier) const {GeneratedStationProfile s;s.id=Mix(seed);s.name="HOLLOWROCK "+std::to_string(s.id%900+100);s.archetype=StationArchetype::AsteroidStation;s.orbitClass=StationOrbitClass::AsteroidEmbedded;s.asteroidEmbedded=true;s.defenseTier=std::max(1,tier/2);s.services={"Dock","Storage","Refinery","Market","Repair","Fuel"};s.serviceCount=int(s.services.size());return s;}
std::vector<GeneratedStationProfile> StationEcologySystem::BuildStartingSystem(std::uint64_t seed,int pop,bool belt) const {std::vector<GeneratedStationProfile> out;GeneratedStationProfile primary;primary.id=Mix(seed+1);primary.name="Axiom Prime";primary.archetype=pop>=3?StationArchetype::TradeHub:StationArchetype::FrontierOutpost;primary.orbitClass=StationOrbitClass::HighPlanet;primary.services={"Dock","Market","Fitting","Cargo","Repair","Fuel"};primary.serviceCount=int(primary.services.size());out.push_back(primary);GeneratedStationProfile tether;tether.id=Mix(seed+2);tether.name="Orbital Tether Alpha";tether.archetype=StationArchetype::TetherTerminal;tether.orbitClass=StationOrbitClass::Synchronous;tether.services={"Dock","Planetary Industry","Tether Storage","Logistics","Repair"};tether.serviceCount=int(tether.services.size());out.push_back(tether);if(belt)out.push_back(BuildAsteroidStation(seed+3,std::max(1,pop)));return out;}
} // namespace subspace
