#include "station/StationBuilderSystem.h"

#include <algorithm>
#include <cmath>

namespace subspace {
StationGridCoord StationBuilderSystem::Snap(double x,double y,double g) const {g=std::max(.25,g);return{static_cast<int>(std::llround(x/g)),static_cast<int>(std::llround(y/g))};}
bool StationBuilderSystem::AddModule(StationBuildPlan&p,const StationModuleNative&m,StationGridCoord grid,int rot){for(const auto&x:p.modules)if(x.grid==grid)return false;StationPlacedModule placed;placed.instanceId=nextId_++;placed.module=m;placed.grid=grid;placed.rotationQuarterTurns=((rot%4)+4)%4;p.modules.push_back(placed);return true;}
bool StationBuilderSystem::RemoveModule(StationBuildPlan&p,std::uint64_t id){auto it=std::remove_if(p.modules.begin(),p.modules.end(),[&](const auto&m){return m.instanceId==id;});if(it==p.modules.end())return false;p.modules.erase(it,p.modules.end());return true;}
StationBuildValidation StationBuilderSystem::Validate(const StationBuildPlan&p) const {StationBuildValidation v;StationConstructionSystem base;auto place=base.ValidatePlacement(p.placement);if(!place.valid)v.errors.push_back(place.reason);bool core=false,dock=false,power=false;for(const auto&m:p.modules){v.structuralMaterial+=m.module.structuralMaterial;v.netPower+=m.module.powerNet;v.storage+=m.module.storage;core|=m.module.type==StationModuleType::Core;dock|=m.module.type==StationModuleType::Dock;power|=m.module.type==StationModuleType::Power&&m.module.powerNet>0;}if(!core)v.errors.push_back("station core required");if(!power)v.errors.push_back("positive power module required");if(!dock)v.warnings.push_back("station has no docking access");if(v.netPower<0)v.errors.push_back("station power deficit");if(!p.modules.empty()){std::vector<bool>seen(p.modules.size(),false);std::vector<std::size_t>open{0};seen[0]=true;for(std::size_t q=0;q<open.size();++q){const auto&g=p.modules[open[q]].grid;for(std::size_t i=0;i<p.modules.size();++i){if(seen[i])continue;const auto&h=p.modules[i].grid;if(std::abs(g.x-h.x)+std::abs(g.y-h.y)==1){seen[i]=true;open.push_back(i);}}}if(std::find(seen.begin(),seen.end(),false)!=seen.end())v.errors.push_back("station modules must form one connected structure");}v.valid=v.errors.empty();return v;}
std::unordered_map<std::string,double> StationBuilderSystem::MaterialBill(const StationBuildPlan&p) const {std::unordered_map<std::string,double>b;for(const auto&m:p.modules){b["structural_alloy"]+=m.module.structuralMaterial;b["industrial_electronics"]+=std::max(2.0,m.module.structuralMaterial*.045);if(m.module.type==StationModuleType::Power)b["reactor_components"]+=m.module.structuralMaterial*.08;if(m.module.type==StationModuleType::Shipyard)b["precision_machinery"]+=m.module.structuralMaterial*.18;if(m.module.type==StationModuleType::Defense)b["weapon_components"]+=m.module.structuralMaterial*.12;}return b;}
} // namespace subspace
