# R193: player scale, small-ship certification and Pilot 6DOF source gate.
if(NOT DEFINED ROOT)
  message(FATAL_ERROR "R193 requires -DROOT=<engine root>")
endif()
function(r193_read rel out)
  set(path "${ROOT}/${rel}")
  if(NOT EXISTS "${path}")
    message(FATAL_ERROR "R193 missing required source: ${rel}")
  endif()
  file(READ "${path}" text)
  set(${out} "${text}" PARENT_SCOPE)
endfunction()
function(r193_req text token why)
  string(FIND "${text}" "${token}" pos)
  if(pos EQUAL -1)
    message(FATAL_ERROR "R193 BLOCKED: ${why}: missing '${token}'")
  endif()
endfunction()

r193_read("include/character/PlayerModelSourceAuthoritySystem.h" PLAYER)
r193_read("include/interior/SmallShipInteriorValidationSystem.h" SMALL)
r193_read("src/input/PlayerControlSystem.cpp" CONTROL)
r193_read("src/application/NativeGameApplication.cpp" APP)
r193_read("src/application/NativeBattlefieldRenderer.cpp" RENDER)
r193_read("tests/r189_strategy_fps_cutover_tests.cpp" FLIGHT_TEST)
r193_read("tests/r193_player_scale_smallship_tests.cpp" SCALE_TEST)

r193_req("${PLAYER}" "naturalHeightIsScaleAuthority" "real player must own human scale")
r193_req("${PLAYER}" "WithPlayerHeight(out.measuredHeightMeters" "measured model height must drive WorldScaleProfile")
r193_req("${SMALL}" "SmallShipInteriorTier::Cutter" "Cutter certification tier")
r193_req("${SMALL}" "SmallShipInteriorTier::Shuttle" "Shuttle certification tier")
r193_req("${SMALL}" "SmallShipInteriorTier::Corvette" "Corvette certification tier")
r193_req("${SMALL}" "connectedWalkableCount != layout.carve.walkableModuleCount" "cohesive interior requirement")
r193_req("${CONTROL}" "yaw/pitch are transient mouse-rate demands" "direct Pilot mouse torque path")
r193_req("${APP}" "RotateShipLocalToWorld" "full 6DOF first-person camera basis")
r193_req("${APP}" "R193_FULL_SHIP_ATTITUDE" "camera cutover marker")
r193_req("${RENDER}" "the playable interior is ship-local in all three attitude axes" "full interior attitude")
r193_req("${RENDER}" "if(frame.hasFirstPersonPose)" "seated cockpit renders physical interior")
r193_req("${FLIGHT_TEST}" "level W is nose-forward without accidental vertical thrust" "forward-axis regression")
r193_req("${FLIGHT_TEST}" "Q is roll-left" "Q roll regression")
r193_req("${FLIGHT_TEST}" "E is roll-right" "E roll regression")
r193_req("${FLIGHT_TEST}" "mouse-right produces immediate right-yaw torque" "mouse steering regression")
r193_req("${SCALE_TEST}" "player is not arbitrarily rescaled to 1.80m" "natural player scale test")
r193_req("${SCALE_TEST}" "one-room cutter is the first certified interior rung" "small-ship first rung")

message(STATUS "R193 player-scale / small-ship / Pilot 6DOF source gate PASS")
