# R192: starter interior interaction / FPS mouse direction source certification.
if(NOT DEFINED ROOT)
  message(FATAL_ERROR "R192 requires -DROOT=<engine root>")
endif()
function(r192_read rel out)
  set(path "${ROOT}/${rel}")
  if(NOT EXISTS "${path}")
    message(FATAL_ERROR "R192 missing required source: ${rel}")
  endif()
  file(READ "${path}" text)
  set(${out} "${text}" PARENT_SCOPE)
endfunction()
function(r192_req text token why)
  string(FIND "${text}" "${token}" pos)
  if(pos EQUAL -1)
    message(FATAL_ERROR "R192 STARTER INTERIOR BLOCKED: ${why}: missing '${token}'")
  endif()
endfunction()

r192_read("include/input/MouseLookProfileSystem.h" MOUSE)
r192_read("include/interior/StarterShipInteriorSceneSystem.h" SCENE_H)
r192_read("src/interior/StarterShipInteriorSceneSystem.cpp" SCENE_CPP)
r192_read("src/application/NativeGameApplication.cpp" APP)
r192_read("src/application/NativeBattlefieldRenderer.cpp" RENDER)
r192_read("tests/r189_strategy_fps_cutover_tests.cpp" TESTS)

r192_req("${MOUSE}" "return {-rawDx*0.0026f,-rawDy*0.0026f}" "rightward FPS mouse yaw correction")
r192_req("${MOUSE}" "PilotHead" "cockpit freelook direction authority")
r192_req("${SCENE_H}" "StarterInteriorFixture" "physical starter fixture contract")
r192_req("${SCENE_H}" "ResolveFixtureCollision" "fixture locomotion collision")
r192_req("${SCENE_CPP}" "InteriorFixtureKind::HelmSeat" "physical helm fixture")
r192_req("${SCENE_CPP}" "InteriorFixtureKind::FleetCommandTerminal" "physical fleet console fixture")
r192_req("${SCENE_CPP}" "InteriorFixtureKind::CargoTerminal" "cargo fixture")
r192_req("${SCENE_CPP}" "InteriorFixtureKind::EngineeringPanel" "engineering fixture")
r192_req("${SCENE_CPP}" "InteriorFixtureKind::Airlock" "airlock fixture")
r192_req("${APP}" "ExecuteInteriorInteraction()" "reticle interaction dispatch")
r192_req("${APP}" "TakeControlsAt" "visible helm to Pilot transition")
r192_req("${APP}" "gameplay modes are entered through physical fixtures" "global Tab mode-cycle retirement")
r192_req("${RENDER}" "DrawStarterInteriorFixtures" "starter cabin furnishing render")
r192_req("${RENDER}" "ON FOOT / SHIP INTERIOR" "separate OnFoot HUD")
r192_req("${RENDER}" "starterInteriorPrompt" "contextual FPS interaction prompt")
r192_req("${TESTS}" "rightward raw mouse produces rightward FPS yaw" "mouse inversion regression test")
r192_req("${TESTS}" "starter FPS spawn faces the physical helm" "starter helm acceptance test")

message(STATUS "R192 starter interior / interaction / mouse-look source gate PASS")
