cmake_minimum_required(VERSION 3.20)
get_filename_component(ROOT "${CMAKE_CURRENT_LIST_DIR}/../../.." ABSOLUTE)
file(READ "${ROOT}/SubspaceTools.ps1" PCC)
file(READ "${ROOT}/scripts/subspace_planetary_command_r158_r177_apply.ps1" VERIFY)

function(require_token TEXT TOKEN WHAT)
  string(FIND "${${TEXT}}" "${TOKEN}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "R184 missing ${WHAT}: ${TOKEN}")
  endif()
endfunction()
function(forbid_token TEXT TOKEN WHAT)
  string(FIND "${${TEXT}}" "${TOKEN}" POS)
  if(NOT POS EQUAL -1)
    message(FATAL_ERROR "R184 retired ${WHAT} returned: ${TOKEN}")
  endif()
endfunction()

require_token(PCC "\"run-studio\"" "September 30 Studio action surface")
require_token(PCC "function Assert-NativeLinkOutputsReady" "September 30 native-link protection")
require_token(PCC "Invoke-StudioR82R2GateRepairIfRequired" "September 30 Studio R82R2 orchestration")
require_token(PCC "Independent Studio window/render smoke" "September 30 independent Studio smoke")
require_token(PCC "function Invoke-PlanetaryCommandCanonicalVerification" "PCC semantic verifier function")
require_token(PCC "Invoke-PlanetaryCommandCanonicalVerification" "native build verifier invocation")
require_token(PCC "subspace_planetary_command_r158_r177_apply.ps1" "verification-only compatibility entrypoint")
require_token(PCC "historical text replay is retired" "explicit replay retirement status")
require_token(VERIFY "historical 17-transform text migration is retired after R179" "verification-only script contract")
require_token(VERIFY "R179 canonical Planetary Command source is already materialized" "canonical semantic success contract")
forbid_token(PCC "package is installed but guarded source materialization is pending" "R177R1 pending-materialization branch")
forbid_token(PCC "expected one certified preimage" "R177R1/R177R2 preimage transformer")
forbid_token(PCC "indentation-normalized" "R177R2 whitespace matcher")
message(STATUS "R184 PCC Planetary Command orchestration source gate PASS")
