# PASS1163-1202 - embodied flight / authoring foundation certification.
get_filename_component(PROJECT_ROOT "${ROOT}/.." ABSOLUTE)
set(PLAYER "${PROJECT_ROOT}/engine/src/input/PlayerControlSystem.cpp")
set(INPUT_H "${PROJECT_ROOT}/engine/include/input/InputState.h")
set(EMBODY "${PROJECT_ROOT}/engine/src/interior/ShipEmbodimentSystem.cpp")
set(FPS "${PROJECT_ROOT}/engine/src/rendering/FirstPersonViewSystem.cpp")
set(PROJECTION "${PROJECT_ROOT}/engine/src/rendering/StrategicViewProjection.cpp")
set(PLAYTEST "${PROJECT_ROOT}/engine/src/ship_editor/ShipyardPlaytestSystem.cpp")
set(APERTURE "${PROJECT_ROOT}/engine/src/interior/ApertureHangarAuthoringSystem.cpp")
set(WORKSPACE "${PROJECT_ROOT}/engine/src/ship_editor/ShipyardWorkspaceSystem.cpp")
set(SHIELD_H "${PROJECT_ROOT}/engine/include/rendering/ConformalShieldSurfaceSystem.h")
set(SAFETY "${PROJECT_ROOT}/engine/src/ship_editor/ShipyardBuildSafetySystem.cpp")
foreach(P IN ITEMS "${PLAYER}" "${INPUT_H}" "${EMBODY}" "${FPS}" "${PROJECTION}" "${PLAYTEST}" "${APERTURE}" "${WORKSPACE}" "${SHIELD_H}" "${SAFETY}")
  if(NOT EXISTS "${P}")
    message(FATAL_ERROR "PASS1163-1202 required file missing: ${P}")
  endif()
endforeach()
file(READ "${PLAYER}" PLAYER_TEXT)
file(READ "${INPUT_H}" INPUT_TEXT)
file(READ "${EMBODY}" EMBODY_TEXT)
file(READ "${FPS}" FPS_TEXT)
file(READ "${PROJECTION}" PROJECTION_TEXT)
file(READ "${PLAYTEST}" PLAYTEST_TEXT)
file(READ "${APERTURE}" APERTURE_TEXT)
file(READ "${WORKSPACE}" WORKSPACE_TEXT)
file(READ "${SHIELD_H}" SHIELD_TEXT)
file(READ "${SAFETY}" SAFETY_TEXT)
function(require_token TEXT_VAR TOKEN LABEL)
  string(FIND "${${TEXT_VAR}}" "${TOKEN}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "PASS1163-1202 ${LABEL} missing token: ${TOKEN}")
  endif()
endfunction()
require_token(PLAYER_TEXT "RotateEulerXYZ" "full 3D flight")
require_token(PLAYER_TEXT "FlightThrustUp" "vertical thrust")
require_token(PLAYER_TEXT "pitchTorqueRatio" "pitch torque")
require_token(PLAYER_TEXT "rollTorqueRatio" "roll torque")
require_token(INPUT_TEXT "FlightRollRight" "semantic 6DOF input")
require_token(EMBODY_TEXT "lookPitchRadians" "on-foot FPS look")
require_token(FPS_TEXT "BuildOnFootLocal" "first-person camera")
require_token(PROJECTION_TEXT "ScreenToEditorFocusPlane" "construction pointer projection")
require_token(PLAYTEST_TEXT "RemoteFleetCommand" "Shipyard Play bridge")
require_token(APERTURE_TEXT "StandardHangarDoor" "hangar/aperture authoring")
require_token(WORKSPACE_TEXT "PrimaryWorkspaces" "professional Shipyard workspace")
require_token(WORKSPACE_TEXT "apertures_hangars" "Apertures & Hangars panel")
require_token(SHIELD_TEXT "requireSingleClosedComponent" "cohesive shield envelope")
require_token(SAFETY_TEXT "FlightPitchUp" "Shipyard 6DOF input suppression")
message(STATUS "PASS1163-1202 embodied authoring foundation authority certified")
