cmake_minimum_required(VERSION 3.20)
get_filename_component(ROOT "${CMAKE_CURRENT_LIST_DIR}/../../.." ABSOLUTE)
file(READ "${ROOT}/engine/include/ship_editor/ShipyardBuilderSystem.h" BUILDER_H)
file(READ "${ROOT}/engine/include/ship_editor/ShipyardTransformSystem.h" TX_H)
file(READ "${ROOT}/engine/include/ship_editor/ShipyardTransformSpacePolicy.h" POLICY)
file(READ "${ROOT}/engine/src/ship_editor/ShipyardTransformSystem.cpp" TX_CPP)
file(READ "${ROOT}/engine/src/ship_editor/ShipyardBuilderSystem.cpp" BUILDER_CPP)
file(READ "${ROOT}/engine/src/studio/StudioAxisGizmo.cpp" GIZMO)
file(READ "${ROOT}/engine/include/studio/StudioTransformViewBasis.h" VIEW_BASIS)
file(READ "${ROOT}/engine/src/application/NativeBattlefieldRenderer.cpp" RENDERER)
file(READ "${ROOT}/engine/src/studio/StudioApplication.cpp" APP)
file(READ "${ROOT}/engine/include/studio/StudioTransformMoveDelta.h" MOVE_DELTA)

function(require_token TEXT TOKEN WHAT)
  string(FIND "${${TEXT}}" "${TOKEN}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "R43-R52 missing ${WHAT}: ${TOKEN}")
  endif()
endfunction()

require_token(BUILDER_H "transformSpace = ShipyardTransformSpace::Ship" "PARENT startup default")
require_token(TX_H "space = ShipyardTransformSpace::Ship" "transaction PARENT default")
require_token(POLICY "return \"PARENT\"" "PARENT public name")
require_token(POLICY "return \"OBJECT\"" "OBJECT public name")
require_token(POLICY "return \"VIEW\"" "VIEW public name")
require_token(POLICY "if(tool==ShipyardTransformTool::Scale)return ShipyardTransformSpace::Local" "OBJECT-local Scale")
require_token(BUILDER_CPP "ShipyardTransformSpacePolicy::Next" "explicit transform-space cycle")
require_token(BUILDER_CPP "SCALE / OBJECT W-L-H" "visible local-scale status")
require_token(TX_CPP "tx.space==ShipyardTransformSpace::Local" "OBJECT move semantics")
# R82R1 upgraded the transaction from unmirrored ApplyAssemblyRotation to
# mirror-aware AssemblyLocal(tx.before,true). Both represent the documented
# historical R43 transition; the newer branch is required by the R82R1 gate.
string(FIND "${TX_CPP}" "ApplyAssemblyRotation" ORIGINAL_OBJECT_BASIS)
string(FIND "${TX_CPP}" "ConstructionTransformBasisSystem::AssemblyLocal(tx.before,true)" MIRRORED_OBJECT_BASIS)
if(ORIGINAL_OBJECT_BASIS EQUAL -1 AND MIRRORED_OBJECT_BASIS EQUAL -1)
  message(FATAL_ERROR "R43-R52 missing OBJECT movement basis (original or R82R1 mirror-aware)")
endif()
require_token(GIZMO "ShipyardTransformSpacePolicy::Effective" "single effective gizmo policy")
require_token(GIZMO "StudioTransformViewBasis::Build(camera)" "real VIEW gizmo basis")
require_token(VIEW_BASIS "X = screen right, Y = screen up, Z = away from the viewer" "VIEW axis contract")
require_token(RENDERER "cycle PARENT, OBJECT, and VIEW orientations. Scale always uses OBJECT W/L/H." "visible transform-space help")
require_token(APP "StudioTransformMoveDelta::AssemblyAuthored" "assembly move/gizmo basis parity")
require_token(APP "StudioTransformMoveDelta::ModelAuthored" "geometry move/gizmo basis parity")
require_token(APP "TranslateSelectedResolvedParent" "resolved parent-coordinate transaction")
require_token(MOVE_DELTA "AssemblyAuthored" "assembly orientation delta resolver")
require_token(MOVE_DELTA "ModelAuthored" "model orientation delta resolver")

# Retired startup behavior must not return.
string(FIND "${BUILDER_H}" "transformSpace = ShipyardTransformSpace::View" OLD_DEFAULT)
if(NOT OLD_DEFAULT EQUAL -1)
  message(FATAL_ERROR "R43-R52 retired VIEW startup default returned")
endif()
message(STATUS "R43-R52 transform authority source gate PASS")
