cmake_minimum_required(VERSION 3.20)
if(NOT DEFINED ROOT)
  get_filename_component(ROOT "${CMAKE_CURRENT_LIST_DIR}/../../.." ABSOLUTE)
endif()

function(require_text path token label)
  file(READ "${path}" content)
  string(FIND "${content}" "${token}" found)
  if(found EQUAL -1)
    message(FATAL_ERROR "PASS1440 missing ${label}: ${token} in ${path}")
  endif()
endfunction()

set(role_h "${ROOT}/include/ships/ShipClassRoleSystem.h")
set(role_cpp "${ROOT}/src/ships/ShipClassRoleSystem.cpp")
set(gen_h "${ROOT}/include/ships/ShipClassGenerationAuthoritySystem.h")
set(gen_cpp "${ROOT}/src/ships/ShipClassGenerationAuthoritySystem.cpp")
set(doc "${ROOT}/../docs/design/SHIP_CLASS_HULL_TOPOLOGY_AUTHORITY.md")
set(authority "${ROOT}/../content/architecture/ship_class_hull_topology_v1.json")

require_text("${role_h}" "ShipHullTopologyProfile" "hull topology profile")
require_text("${role_h}" "IsCapitalClass" "capital predicate")
require_text("${role_h}" "HullTopology" "hull topology resolver")
require_text("${role_h}" "NominalClassJumpRatio" "class jump metric")
require_text("${role_cpp}" "return {c,true,2,3,4};" "Carrier multi-hull profile")
require_text("${role_cpp}" "return {c,true,3,4,6};" "Dreadnought multi-hull profile")
require_text("${role_cpp}" "return {c,false,1,1,1};" "single-hull non-capital profile")
require_text("${role_cpp}" "900.0f,1450.0f,1125.0f" "capital jump beyond Battleship")
require_text("${gen_h}" "primaryHullCount" "generation hull count diagnostics")
require_text("${gen_h}" "hullTopologyValid" "generation topology validity")
require_text("${gen_cpp}" "non-capital ship classes require exactly one certified primary hull" "single-hull enforcement")
require_text("${gen_cpp}" "capital class requires multiple certified primary hull roots" "multi-hull capital enforcement")
require_text("${gen_cpp}" "if(!report.hullTopologyValid)return false;" "invalid hull topology excluded from safe drafts")
require_text("${gen_cpp}" "CLASS_HULL_TOPOLOGY_V4" "new lineage authority")
require_text("${role_h}" "static std::string ClassName" "PASS1439R1 MSVC string fix carried forward")
require_text("${doc}" "Frigate — exactly 1 primary hull" "design authority standard hull rule")
require_text("${doc}" "Capital construction begins beyond Battleship" "capital transition authority")
require_text("${authority}" "\"schema\": \"subspace.ship-hull-topology.v1\"" "machine-readable hull topology authority")

message(STATUS "PASS1440 single-hull standard / multi-hull capital authority PASS")
