cmake_minimum_required(VERSION 3.20)
get_filename_component(PROJECT_ROOT "${CMAKE_CURRENT_LIST_DIR}/../../.." ABSOLUTE)
function(require_text rel token)
  set(path "${PROJECT_ROOT}/${rel}")
  if(NOT EXISTS "${path}")
    message(FATAL_ERROR "R53-R62 missing source: ${rel}")
  endif()
  file(READ "${path}" text)
  string(FIND "${text}" "${token}" pos)
  if(pos EQUAL -1)
    message(FATAL_ERROR "R53-R62 ${rel} missing token: ${token}")
  endif()
endfunction()
require_text("engine/include/input/InputState.h" "DccCycleTransformSpace")
require_text("engine/src/platform/NativeWindow.cpp" "VK_OEM_COMMA")
require_text("engine/src/studio/StudioApplication.cpp" "InputAction::DccCycleTransformSpace")
require_text("engine/include/studio/StudioAxisGizmo.h" "selectedSpace")
require_text("engine/include/studio/StudioAxisGizmo.h" "effectiveSpace")
require_text("engine/src/studio/StudioAxisGizmo.cpp" "out.selectedSpace=model.transformSpace")
require_text("engine/src/studio/StudioGizmoOverlay.cpp" "SPACE")
require_text("engine/src/studio/StudioGizmoOverlay.cpp" "USE")
require_text("engine/src/ship_editor/ShipyardBuilderSystem.cpp" "Transform space changed; transient axis/local constraint cleared")
require_text("engine/include/studio/StudioOverlayPlacementPolicy.h" "kHudHeight=130.0f")
require_text("engine/include/ship_editor/ShipyardTransformSpacePolicy.h" "return \"PARENT\"")
message(STATUS "R53-R62 Studio transform UI/hygiene source gate PASS")
