cmake_minimum_required(VERSION 3.20)
get_filename_component(ROOT "${CMAKE_CURRENT_LIST_DIR}/../../.." ABSOLUTE)
function(req file token)
  file(READ "${ROOT}/${file}" txt)
  string(FIND "${txt}" "${token}" at)
  if(at EQUAL -1)
    message(FATAL_ERROR "R82R1 missing ${token} in ${file}")
  endif()
endfunction()
req("engine/include/ship_editor/ShipyardTransformSpacePolicy.h" "tool==ShipyardTransformTool::Rotate)return ShipyardTransformSpace::Ship")
req("engine/include/studio/StudioTransformStatusPolicy.h" "tool==ShipyardTransformTool::Rotate ? \"EULER\"")
req("engine/src/ship_editor/ShipyardTransformSystem.cpp" "ConstructionTransformBasisSystem::AssemblyLocal(tx.before,true)")
req("engine/src/ship_editor/ShipyardBuilderSystem.cpp" "ROTATE / EULER components")
req("engine/src/studio/StudioAxisGizmo.cpp" "StudioTransformStatusPolicy::HasEffectiveOverride")
req("engine/src/studio/StudioGizmoOverlay.cpp" "EffectiveSpaceName(snapshot.transformTool,snapshot.effectiveSpace)")
req("SubspaceTools.ps1" "Studio R82R1 corrective audit")
message(STATUS "Subspace R82R1 corrective convergence authority PASS")
