cmake_minimum_required(VERSION 3.20)
get_filename_component(PROJECT_ROOT "${CMAKE_CURRENT_LIST_DIR}/../../.." ABSOLUTE)
set(ENG "${PROJECT_ROOT}/engine")
file(READ "${ENG}/CMakeLists.txt" CMAKE_SRC)
file(READ "${ENG}/tests/studio_axis_contract_r34_tests.cpp" AXIS)
file(READ "${ENG}/tests/pass735_744_shipyard_dev_pcc_tests.cpp" HIST_TEST)
file(READ "${PROJECT_ROOT}/tools/control/static-gates/pass1268_1292_visible_professional_shipyard_cutover.cmake" HIST_GATE)
file(READ "${PROJECT_ROOT}/SubspaceTools.ps1" PCC)
foreach(TOKEN "SubspaceStudioR82R2GateRepairSourceGate" "SubspaceStudioR82R4FourFailureRecoverySourceGate")
  string(FIND "${CMAKE_SRC}" "${TOKEN}" IDX)
  if(IDX EQUAL -1)
    message(FATAL_ERROR "R82R4 missing CTest registration: ${TOKEN}")
  endif()
endforeach()
string(FIND "${AXIS}" "assert(" RAW_ASSERT)
if(NOT RAW_ASSERT EQUAL -1)
  message(FATAL_ERROR "R82R4: R34 still has modal assert() calls")
endif()
foreach(TOKEN "tx.snap=false;" "snapping 20-degree requested roll to 15 degrees is intentional")
  string(FIND "${AXIS}" "${TOKEN}" IDX)
  if(IDX EQUAL -1)
    message(FATAL_ERROR "R82R4 missing corrected axis/snap fixture: ${TOKEN}")
  endif()
endforeach()
string(FIND "${HIST_TEST}" "functional authoring workspaces remain reachable" HIST_POS)
if(HIST_POS EQUAL -1)
  message(FATAL_ERROR "R82R4 historical Pass735 test does not certify actual workspace commands")
endif()
string(FIND "${HIST_GATE}" "historical PAINT is now the Appearance domain" GATE_POS)
if(GATE_POS EQUAL -1)
  message(FATAL_ERROR "R82R4 historical visible gate still demands obsolete PAINT peer tab")
endif()
foreach(TOKEN "Invoke-StudioR82R2GateRepairIfRequired" "SubspaceStudioR82R2GateRepairSourceGate")
  string(FIND "${PCC}" "${TOKEN}" IDX)
  if(IDX EQUAL -1)
    message(FATAL_ERROR "R82R4 PCC re-entry missing: ${TOKEN}")
  endif()
endforeach()
message(STATUS "Subspace R82R4 four-failure recovery source contract PASS")
