# Pass1340-1439: cumulative Blender-DCC Shipyard authority gate.
file(READ "${ROOT}/include/application/SubspaceBuildIdentity.h" BUILD_ID)
file(READ "${ROOT}/include/ship_editor/ShipyardDccUiSystem.h" DCC_H)
file(READ "${ROOT}/src/ship_editor/ShipyardDccUiSystem.cpp" DCC_CPP)
file(READ "${ROOT}/src/ship_editor/ShipyardProfessionalVisibleCutover.cpp" CUTOVER)
file(READ "${ROOT}/src/application/NativeBattlefieldRenderer.cpp" RENDERER)
file(READ "${ROOT}/src/application/NativeGameApplication.cpp" APP)
file(READ "${ROOT}/src/platform/NativeWindow.cpp" WINDOW)
file(READ "${ROOT}/include/input/InputState.h" INPUT)
file(READ "${ROOT}/../docs/design/SHIPYARD_BLENDER_DCC_100_PASS_ROLLUP.md" LEDGER)
file(READ "${ROOT}/../content/architecture/shipyard_blender_dcc_100pass_authority_v1.json" CONTRACT)

foreach(TOKEN "BLENDER-DCC-100" "PASS1439" "PASS1340-1439" "SUBSPACE-SHIPYARD-BLENDER-DCC-1439")
    if(NOT BUILD_ID MATCHES "${TOKEN}")
        message(FATAL_ERROR "Pass1340-1439 missing build identity token: ${TOKEN}")
    endif()
endforeach()
foreach(TOKEN "ShipyardDccUiState" "ShipyardDccOutlinerMode" "ShipyardDccViewportShading" "CommandPalette" "AssetPresetName")
    if(NOT DCC_H MATCHES "${TOKEN}" AND NOT DCC_CPP MATCHES "${TOKEN}")
        message(FATAL_ERROR "Pass1340-1439 missing DCC state token: ${TOKEN}")
    endif()
endforeach()
foreach(TOKEN "DccToggleMaximizeViewport" "DccCycleAssetDensity" "DccToggleFavoriteSelected" "DccWorkspaceNext" "VisibleCatalogIndices")
    if(NOT CUTOVER MATCHES "${TOKEN}")
        message(FATAL_ERROR "Pass1340-1439 missing visible cutover token: ${TOKEN}")
    endif()
endforeach()
# PASS1454+ first-class DCC keeps the PASS1439 functionality while normalizing
# visible labels/chrome. Accept either the historical Asset Browser/Scene Collection
# wording or the successor compact ASSETS + hierarchy presentation.
foreach(TOKEN "OUTLINER" "PROPERTIES" "COMMAND SEARCH" "WIREFRAME" "showShieldPreview" "build_identity::kShipyardUiProfile")
    if(NOT RENDERER MATCHES "${TOKEN}")
        message(FATAL_ERROR "Pass1340-1439 missing renderer token: ${TOKEN}")
    endif()
endforeach()
if(NOT RENDERER MATCHES "ASSET BROWSER" AND NOT RENDERER MATCHES "ASSETS")
    message(FATAL_ERROR "Pass1340-1439 missing historical/successor asset browser authority")
endif()
if(NOT DCC_H MATCHES "ShipyardDccOutlinerMode" AND NOT DCC_CPP MATCHES "HIERARCHY")
    message(FATAL_ERROR "Pass1340-1439 missing historical/successor outliner hierarchy authority")
endif()
foreach(TOKEN "DccToggleToolbar" "DccToggleSidebar" "DccMaximizeArea" "DccCommandSearch" "DccWorkspacePrevious" "DccWorkspaceNext" "DccCycleAssetFilter")
    if(NOT INPUT MATCHES "${TOKEN}" OR NOT APP MATCHES "${TOKEN}" OR NOT WINDOW MATCHES "${TOKEN}")
        message(FATAL_ERROR "Pass1340-1439 missing input/application token: ${TOKEN}")
    endif()
endforeach()
foreach(TOKEN "case 'G'" "case 'R'" "case 'S'" "case 'T'" "case 'N'" "VK_F3" "VK_SPACE")
    if(NOT WINDOW MATCHES "${TOKEN}")
        message(FATAL_ERROR "Pass1340-1439 missing Blender keymap source token: ${TOKEN}")
    endif()
endforeach()
if(NOT LEDGER MATCHES "Pass1340" OR NOT LEDGER MATCHES "Pass1439")
    message(FATAL_ERROR "Pass1340-1439 cumulative ledger endpoints missing")
endif()
if(NOT CONTRACT MATCHES "shipyard.blender-dcc" OR NOT CONTRACT MATCHES "BLENDER-DCC-100")
    message(FATAL_ERROR "Pass1340-1439 machine-readable DCC authority missing")
endif()
message(STATUS "Pass1340-1439 cumulative Shipyard Blender DCC source authority PASS")
