if(NOT DEFINED ROOT)
  message(FATAL_ERROR "ROOT is required")
endif()
get_filename_component(PROJECT_ROOT "${ROOT}/.." ABSOLUTE)
file(READ "${ROOT}/src/core/Engine.cpp" ENGINE_CPP)
file(READ "${ROOT}/include/procedural/GalaxyGenerator.h" GALAXY_H)
file(READ "${ROOT}/src/procedural/GalaxyGenerator.cpp" GALAXY_CPP)
file(READ "${ROOT}/include/input/PlayerControlSystem.h" CONTROL_H)
file(READ "${ROOT}/CMakeLists.txt" ENGINE_CMAKE)
file(READ "${PROJECT_ROOT}/tools/control/SubspaceControlCenter.ps1" PCC)

if(ENGINE_CPP MATCHES "RegisterSystem\\(std::make_unique<NavigationSystem")
  message(FATAL_ERROR "Legacy NavigationSystem is still registered in production runtime")
endif()
if(GALAXY_H MATCHES "gameplay remains on X/Y" OR GALAXY_H MATCHES "ships do not land")
  message(FATAL_ERROR "Old 2D/no-landing authority remains in GalaxyGenerator")
endif()
if(NOT GALAXY_CPP MATCHES "planet.landable = planet.type != PlanetType::GasGiant")
  message(FATAL_ERROR "Solid-world landing capability rule missing")
endif()
if(NOT CONTROL_H MATCHES "FlightAuthorityMode.*Full3D")
  message(FATAL_ERROR "Explicit full-3D flight authority missing")
endif()
if(NOT ENGINE_CMAKE MATCHES "HomeSystemSaveGame")
  message(FATAL_ERROR "Legacy HomeSystemSaveGame quarantine missing from build graph")
endif()
if(NOT EXISTS "${PROJECT_ROOT}/content/architecture/performance_reference_baseline_v1.json")
  message(FATAL_ERROR "P921 performance reference contract missing")
endif()
if(NOT EXISTS "${PROJECT_ROOT}/content/architecture/foundation_convergence_contract_v1.json")
  message(FATAL_ERROR "Foundation convergence contract missing")
endif()
if(NOT PCC MATCHES "Certified fingerprint" OR NOT PCC MATCHES "Current fingerprint")
  message(FATAL_ERROR "Commit-GREEN fingerprint mismatch diagnostics missing")
endif()
message(STATUS "Pass922-931 foundation convergence static gate PASS")
