file(READ "${ROOT}/include/ship_editor/ShipyardBuilderMigrationSystem.h" MIGRATION_H)
file(READ "${ROOT}/src/ship_editor/ShipyardBuilderMigrationSystem.cpp" MIGRATION)
file(READ "${ROOT}/src/ship_editor/ShipyardProfessionalController.cpp" CONTROLLER)
file(READ "${ROOT}/include/ship_editor/ShipyardPanelModelSystem.h" PANEL_H)
file(READ "${ROOT}/src/ship_editor/ShipyardPanelModelSystem.cpp" PANEL)
file(READ "${ROOT}/include/ship_editor/ShipyardJobSystem.h" JOB_H)
file(READ "${ROOT}/src/ship_editor/ShipyardCommandSystem.cpp" COMMANDS)
file(READ "${ROOT}/src/ship_editor/ShipyardProfessionalUiSystem.cpp" UI)

foreach(TOKEN "ShipyardBuilderMigrationState" "ShipyardDocument" "ShipyardSession" "SyncSelectionFromLegacy")
  if(NOT MIGRATION_H MATCHES "${TOKEN}" AND NOT MIGRATION MATCHES "${TOKEN}")
    message(FATAL_ERROR "PASS1223-1242 migration authority missing token: ${TOKEN}")
  endif()
endforeach()

if(NOT CONTROLLER MATCHES "generator.new-seed-generate" OR NOT CONTROLLER MATCHES "PcgReroll" OR NOT CONTROLLER MATCHES "GenerateVariant")
  message(FATAL_ERROR "PASS1223-1242 New Seed + Generate does not compose the deterministic generator")
endif()
if(CONTROLLER MATCHES "workspace.test.*DevWorld")
  message(FATAL_ERROR "PASS1223-1242 Test workspace aliases Dev World")
endif()
if(NOT PANEL_H MATCHES "ShipyardOutlinerNode" OR NOT PANEL_H MATCHES "EditorPropertySection" OR NOT PANEL MATCHES "Primary Mount")
  message(FATAL_ERROR "PASS1223-1242 Outliner / Properties separation missing")
endif()
if(NOT JOB_H MATCHES "ShipyardJobStatus" OR NOT JOB_H MATCHES "ShipyardJobRecord")
  message(FATAL_ERROR "PASS1223-1242 Activity / Jobs authority missing")
endif()
foreach(TOKEN "view.toggle-advanced" "generator.generate" "generator.new-seed-generate" "generator.explain" "validation.run")
  if(NOT COMMANDS MATCHES "${TOKEN}")
    message(FATAL_ERROR "PASS1223-1242 command registry missing ${TOKEN}")
  endif()
endforeach()
if(NOT COMMANDS MATCHES "const std::string key = descriptor.id")
  message(FATAL_ERROR "PASS1223-1242 command registry must capture key before moving descriptor")
endif()
if(NOT UI MATCHES "Activity / Jobs" OR NOT UI MATCHES "ShipyardWorkspaceMode::Character")
  message(FATAL_ERROR "PASS1223-1242 professional panel/workspace registry incomplete")
endif()
message(STATUS "PASS1223-1242 professional Shipyard runtime migration certified")
