get_filename_component(PROJECT_ROOT "${ROOT}/.." ABSOLUTE)
set(HISTORICAL "${ROOT}/tests/pass746r4_projectops_tree_stage_git_flow_source_gate.cmake")
set(ROOT_TOOL "${PROJECT_ROOT}/SubspaceTools.ps1")
set(PUBLISHER "${PROJECT_ROOT}/tools/control/NormalizeGitHubAuthority.ps1")
set(CONTRACT "${PROJECT_ROOT}/project.control.json")

foreach(PATH IN ITEMS "${HISTORICAL}" "${ROOT_TOOL}" "${PUBLISHER}" "${CONTRACT}")
  if(NOT EXISTS "${PATH}")
    message(FATAL_ERROR "R6R14 static gate missing file: ${PATH}")
  endif()
endforeach()

file(READ "${HISTORICAL}" HISTORICAL_TEXT)
file(READ "${ROOT_TOOL}" ROOT_TEXT)
file(READ "${PUBLISHER}" PUBLISHER_TEXT)
file(READ "${CONTRACT}" CONTRACT_TEXT)

function(r6r14_require TEXT_VALUE NEEDLE)
  string(FIND "${TEXT_VALUE}" "${NEEDLE}" FOUND_AT)
  if(FOUND_AT EQUAL -1)
    message(FATAL_ERROR "R6R14 static gate missing: ${NEEDLE}")
  endif()
endfunction()

# PASS_CLEANCLONE_REPOSITORY_LIFECYCLE_STATIC_GATE_NORMALIZATION_R5
r6r14_require("${ROOT_TEXT}" "function Show-SourceControlMenu")
r6r14_require("${ROOT_TEXT}" "repo-authority-prepare")
r6r14_require("${ROOT_TEXT}" "git-commit-green")
r6r14_require("${ROOT_TEXT}" "git-push")
r6r14_require("${ROOT_TEXT}" "repo-authority-audit")
r6r14_require("${ROOT_TEXT}" "git-repair")
r6r14_require("${ROOT_TEXT}" "repo-authority-publish")
r6r14_require("${PUBLISHER_TEXT}" "Repository authority PREPARED.")
r6r14_require("${PUBLISHER_TEXT}" "Publish last GREEN normalized main.")
r6r14_require("${CONTRACT_TEXT}" "\"key\": \"repo.prepare\"")
r6r14_require("${CONTRACT_TEXT}" "\"key\": \"repo.publish\"")
r6r14_require("${CONTRACT_TEXT}" "\"repo-authority-prepare\"")
r6r14_require("${CONTRACT_TEXT}" "\"repo-authority-publish\"")
r6r14_require("${HISTORICAL_TEXT}" "PASS_CLEANCLONE_REPOSITORY_LIFECYCLE_GATE_NORMALIZATION_R5")

string(FIND "${HISTORICAL_TEXT}" "require_text(\"${TOOLS_TEXT}\" \"function Show-RepositoryLifecycleMenu\")" STALE_HELPER_ASSERT)
if(NOT STALE_HELPER_ASSERT EQUAL -1)
  message(FATAL_ERROR "R6R14 rejected stale Pass746R4 repository-lifecycle helper assertion")
endif()

message(STATUS "Pass746R6R14 historical guided repository-flow migration static gate PASS")
