file(READ "${ROOT}/include/ship_editor/ShipyardAssetBrowserSystem.h" ASSET_H)
file(READ "${ROOT}/src/ship_editor/ShipyardAssetBrowserSystem.cpp" ASSET)
file(READ "${ROOT}/include/ship_editor/ShipyardUniversalSearchSystem.h" SEARCH_H)
file(READ "${ROOT}/include/ship_editor/ShipyardActivityDockSystem.h" ACTIVITY_H)
file(READ "${ROOT}/include/ship_editor/ShipyardWorkspaceLayoutSystem.h" LAYOUT_H)
file(READ "${ROOT}/include/ship_editor/ShipyardConstructionGuideSystem.h" GUIDES_H)
file(READ "${ROOT}/include/ship_editor/ShipyardProfessionalShellSystem.h" SHELL_H)
file(READ "${ROOT}/src/ship_editor/ShipyardProfessionalController.cpp" CONTROLLER)
file(READ "${ROOT}/src/ship_editor/ShipyardProfessionalUiSystem.cpp" UI)
file(READ "${ROOT}/src/ship_editor/ShipyardCommandSystem.cpp" COMMANDS)
file(READ "${ROOT}/src/ship_editor/ShipyardPanelModelSystem.cpp" PANEL)

foreach(TOKEN "savedFilters" "favorites" "recent" "compatibleOnly" "thumbnailScale")
  if(NOT ASSET_H MATCHES "${TOKEN}")
    message(FATAL_ERROR "PASS1243-1267 Asset Browser missing ${TOKEN}")
  endif()
endforeach()
if(NOT ASSET MATCHES "CanMate" OR NOT ASSET MATCHES "GENERATOR ELIGIBLE")
  message(FATAL_ERROR "PASS1243-1267 Asset Browser compatibility/tag authority missing")
endif()

foreach(TOKEN "Command" "Asset" "ShipObject" "Property" "Panel" "Validation" "Developer")
  if(NOT SEARCH_H MATCHES "${TOKEN}")
    message(FATAL_ERROR "PASS1243-1267 universal search missing group ${TOKEN}")
  endif()
endforeach()

foreach(TOKEN "Activity" "Validation" "History" "Console" "Search" "Build" "Pcc")
  if(NOT ACTIVITY_H MATCHES "${TOKEN}")
    message(FATAL_ERROR "PASS1243-1267 Activity Dock missing ${TOKEN}")
  endif()
endforeach()

if(NOT LAYOUT_H MATCHES "auxiliaryDocksCollapsed" OR NOT LAYOUT_H MATCHES "maximizedPanelId" OR NOT LAYOUT_H MATCHES "ResetCurrent")
  message(FATAL_ERROR "PASS1243-1267 layout authority incomplete")
endif()
if(NOT GUIDES_H MATCHES "MountPlane" OR NOT GUIDES_H MATCHES "Clearance" OR NOT GUIDES_H MATCHES "PlayerScale" OR NOT GUIDES_H MATCHES "Distance")
  message(FATAL_ERROR "PASS1243-1267 construction guide authority incomplete")
endif()
if(NOT SHELL_H MATCHES "ShipyardProfessionalShellState" OR NOT CONTROLLER MATCHES "RebuildShell")
  message(FATAL_ERROR "PASS1243-1267 render-facing professional shell projection missing")
endif()

foreach(TOKEN "search.open" "F3" "view.toggle-aux-docks" "F12" "view.maximize-hovered" "Ctrl+Space" "generator.new-seed-generate")
  string(FIND "${COMMANDS}" "${TOKEN}" TOKEN_POS)
  if(TOKEN_POS EQUAL -1)
    message(FATAL_ERROR "PASS1243-1267 command registry missing ${TOKEN}")
  endif()
endforeach()

if(NOT PANEL MATCHES "Editing Scope" OR NOT PANEL MATCHES "INSTANCE" OR NOT PANEL MATCHES "Open Definition")
  message(FATAL_ERROR "PASS1243-1267 INSTANCE / DEFINITION property boundary missing")
endif()
string(FIND "${UI}" "New Seed + Generate" NEW_SEED_POS)
if(NEW_SEED_POS EQUAL -1 OR NOT UI MATCHES "ShipyardWorkspaceMode::Test")
  message(FATAL_ERROR "PASS1243-1267 professional quick actions/workspace strip incomplete")
endif()
if(NOT UI MATCHES "Asset Browser" OR NOT UI MATCHES "Outliner" OR NOT UI MATCHES "Properties")
  message(FATAL_ERROR "PASS1243-1267 professional shell panel separation missing")
endif()

message(STATUS "PASS1243-1267 GameMaker-inspired professional Shipyard GUI normalization certified")
