cmake_minimum_required(VERSION 3.20)
get_filename_component(PROJECT_ROOT "${CMAKE_CURRENT_LIST_DIR}/../../.." ABSOLUTE)
function(require_text rel token)
  set(path "${PROJECT_ROOT}/${rel}")
  if(NOT EXISTS "${path}")
    message(FATAL_ERROR "R63-R72 missing source: ${rel}")
  endif()
  file(READ "${path}" text)
  string(FIND "${text}" "${token}" pos)
  if(pos EQUAL -1)
    message(FATAL_ERROR "R63-R72 ${rel} missing token: ${token}")
  endif()
endfunction()
require_text("engine/include/input/InputState.h" "DccDuplicateSelection")
require_text("engine/src/platform/NativeWindow.cpp" "InputAction::DccDuplicateSelection")
require_text("engine/include/ship_editor/ShipyardBuilderSystem.h" "DuplicateSelection")
require_text("engine/include/ship_editor/ShipyardBuilderSystem.h" "DeleteSelectionSafe")
require_text("engine/src/ship_editor/ShipyardBuilderSystem.cpp" "BeginDuplicateSelectedPlacement()")
require_text("engine/src/ship_editor/ShipyardBuilderSystem.cpp" "RemoveSelectedModulePreserveDescendants()")
require_text("engine/src/ship_editor/ShipyardBuilderSystem.cpp" "stagedAddCommit")
require_text("engine/include/ship_editor/ShipyardDragDropSystem.h" "suppressLiveSymmetry")
require_text("engine/src/studio/StudioApplication.cpp" "DccDuplicateSelection")
require_text("engine/src/studio/StudioApplication.cpp" "DeleteSelectionSafe")
require_text("engine/src/studio/StudioApplication.cpp" "ShipyardInspectorTab::Sockets)RouteControl(ShipyardBuilderCommand::RemoveSocket)")
require_text("engine/src/ship_editor/ShipyardProfessionalVisibleCutover.cpp" "DELETE SELECTED")
require_text("engine/src/ship_editor/ShipyardProfessionalVisibleCutover.cpp" "ShipyardBuilderCommand::DuplicateSelection")
require_text("engine/include/studio/StudioPlacementWorkflowPolicy.h" "NormalDeletePreservesDescendants")
message(STATUS "R63-R72 Studio selection/placement source gate PASS")
