cmake_minimum_required(VERSION 3.20)
get_filename_component(PROJECT_ROOT "${CMAKE_CURRENT_LIST_DIR}/../../.." ABSOLUTE)

function(require_text rel token)
  set(path "${PROJECT_ROOT}/${rel}")
  if(NOT EXISTS "${path}")
    message(FATAL_ERROR "PASS1509 missing required source: ${rel}")
  endif()
  file(READ "${path}" text)
  string(FIND "${text}" "${token}" pos)
  if(pos EQUAL -1)
    message(FATAL_ERROR "PASS1509 ${rel} missing required token: ${token}")
  endif()
endfunction()

require_text("engine/src/ship_editor/ShipyardBuilderSystem.cpp" "ConstructionScalePivotSystem.h")
require_text("engine/src/ship_editor/ShipyardBuilderSystem.cpp" "Modeled shape scaled / opposite face anchored")
# R82R7: the R43-R62 refactor moved the public space vocabulary from
# temporary builder status messages into the shared policy and HUD adapter.
# Certify the actual authority instead of requiring deleted legacy literals.
require_text("engine/include/ship_editor/ShipyardTransformSpacePolicy.h" "case ShipyardTransformSpace::View:return \"VIEW\";")
require_text("engine/include/ship_editor/ShipyardTransformSpacePolicy.h" "case ShipyardTransformSpace::Ship:return \"PARENT\";")
require_text("engine/include/ship_editor/ShipyardTransformSpacePolicy.h" "case ShipyardTransformSpace::Local:return \"OBJECT\";")
require_text("engine/src/ship_editor/ShipyardBuilderSystem.cpp" "ShipyardTransformSpacePolicy::Next")
require_text("engine/src/ship_editor/ShipyardBuilderSystem.cpp" "Transform space changed; transient axis/local constraint cleared")
require_text("engine/include/studio/StudioTransformStatusPolicy.h" "ShipyardTransformSpacePolicy::Name(space)")
require_text("engine/src/ship_editor/ShipyardProfessionalVisibleCutover.cpp" "one authoritative workspace strip")
require_text("engine/src/ship_editor/ShipyardProfessionalVisibleCutover.cpp" "ConstructionUiLayoutPolicy::TabWidth")
require_text("engine/src/ship_editor/ShipyardProfessionalVisibleCutover.cpp" "ConstructionUiLayoutPolicy::ShowAssetSecondaryActions")
require_text("engine/src/ship_editor/ShipyardWorkspaceSystem.cpp" "case ShipyardWorkspaceMode::Build:return\"CONSTRUCT\";")
require_text("engine/src/ship_editor/ShipyardWorkspaceSystem.cpp" "case ShipyardWorkspaceMode::Model:return\"GEOMETRY\";")
require_text("engine/src/ship_editor/ShipyardWorkspaceSystem.cpp" "add(\"tool_rail\",\"Tools\",\"tool_left\",true,1.0f,48,420,false,false,false);")
require_text("engine/src/modeling/ShipyardModelingSystem.cpp" "Coordinate contract is context-neutral +Y forward.")

file(READ "${PROJECT_ROOT}/engine/src/ship_editor/ShipyardProfessionalVisibleCutover.cpp" visible)
string(FIND "${visible}" "const float y=l.workspaceBarY+l.workspaceBarHeight+3.0f*s;" old_second_row)
if(NOT old_second_row EQUAL -1)
  message(FATAL_ERROR "PASS1509 retired DEV second-row overlap path is still present")
endif()
string(FIND "${visible}" "tab(ShipyardBuilderCommand::WorkspaceModel,\"MODEL\"" old_model_tab)
if(NOT old_model_tab EQUAL -1)
  message(FATAL_ERROR "PASS1509 retired top-level MODEL workspace tab is still present")
endif()

file(READ "${PROJECT_ROOT}/engine/src/ship_editor/ShipyardWorkspaceSystem.cpp" workspace)
string(FIND "${workspace}" "ShipyardWorkspaceSystem::PrimaryWorkspaces(){return {ShipyardWorkspaceMode::Build,ShipyardWorkspaceMode::Model," old_primary)
if(NOT old_primary EQUAL -1)
  message(FATAL_ERROR "PASS1509 MODEL remains a peer public workspace")
endif()

message(STATUS "PASS1509 Studio Construct cutover/current transform-space authority PASS")
