# Pass1339R2 - source artifacts are not update handoffs.
# Resolve from this gate's own location so script-mode/CTest working directories cannot corrupt authority paths.
get_filename_component(_project_root "${CMAKE_CURRENT_LIST_DIR}/../../.." ABSOLUTE)
set(_standalone "${_project_root}/tools/control/StandaloneProjectControlCenter.ps1")
set(_tools "${_project_root}/SubspaceTools.ps1")
foreach(_f IN ITEMS "${_standalone}" "${_tools}")
  if(NOT EXISTS "${_f}")
    message(FATAL_ERROR "PASS1339R2 missing ${_f}")
  endif()
endforeach()
file(READ "${_standalone}" _pcc)
file(READ "${_tools}" _root)
foreach(_token IN ITEMS "Test-LegacyZipPatchManifest" "PATCH_MANIFEST.json" "CumulativeSource" "SourceSnapshot")
  string(FIND "${_pcc}" "${_token}" _idx)
  if(_idx EQUAL -1)
    message(FATAL_ERROR "PASS1339R2 standalone PCC missing token: ${_token}")
  endif()
endforeach()
foreach(_token IN ITEMS "Test-ZipContainsRootPatchManifest" "Test-IsPatchHandoffFile" "PATCH_MANIFEST.json" "CumulativeSource" "SourceSnapshot")
  string(FIND "${_root}" "${_token}" _idx)
  if(_idx EQUAL -1)
    message(FATAL_ERROR "PASS1339R2 SubspaceTools missing token: ${_token}")
  endif()
endforeach()
message(STATUS "PASS1339R2 source-artifact handoff classification gate passed")
