get_filename_component(PROJECT_ROOT "${ROOT}/.." ABSOLUTE)
set(TOOLS "${PROJECT_ROOT}/SubspaceTools.ps1")
set(COMMON "${PROJECT_ROOT}/tools/control/ProjectOpsCommon.psm1")
set(CONTROL "${PROJECT_ROOT}/tools/control/SubspaceControlCenter.ps1")
set(INBOX "${PROJECT_ROOT}/scripts/subspace_apply_update_inbox.ps1")
set(CONTRACT "${PROJECT_ROOT}/project.control.json")
foreach(P IN ITEMS "${TOOLS}" "${COMMON}" "${CONTROL}" "${INBOX}" "${CONTRACT}")
  if(NOT EXISTS "${P}")
    message(FATAL_ERROR "Pass961-964 required file missing: ${P}")
  endif()
endforeach()
file(READ "${TOOLS}" TOOLS_TEXT)
file(READ "${COMMON}" COMMON_TEXT)
file(READ "${CONTROL}" CONTROL_TEXT)
file(READ "${INBOX}" INBOX_TEXT)
file(READ "${CONTRACT}" CONTRACT_TEXT)
function(req TEXT NEEDLE)
  string(FIND "${TEXT}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Pass961-964 missing required authority text: ${NEEDLE}")
  endif()
endfunction()
req("${COMMON_TEXT}" "System.StringComparer]::Ordinal")
req("${COMMON_TEXT}" "CERTIFIABLE-WORKTREE-MANIFEST-V3")
req("${COMMON_TEXT}" "fingerprintScope = 'worktree-path-state-bytes-sha256'")
req("${CONTROL_TEXT}" "deterministic certifiable worktree manifest v3")
req("${CONTROL_TEXT}" "Git HEAD changed after the GREEN gate")
req("${TOOLS_TEXT}" "extension-first and manifest-authoritative")
req("${INBOX_TEXT}" "forge.patch.v1 root discovery is extension-first")
req("${INBOX_TEXT}" "TARGET_MISMATCH")
req("${CONTRACT_TEXT}" "\"discoveryMode\": \"extension-first-manifest-authoritative\"")
req("${CONTRACT_TEXT}" "\"filenameCarriesAuthority\": false")
req("${CONTRACT_TEXT}" "\"schemaVersion\": 3")
message(STATUS "Pass961-964 Forge/PCC deterministic update authority source gate PASS")
