get_filename_component(PROJECT_ROOT "${ROOT}/.." ABSOLUTE)
set(HISTORICAL "${ROOT}/tests/pass746r6r4_historical_root_audit_unborn_git_source_gate.cmake")
set(R6R7 "${PROJECT_ROOT}/tools/control/static-gates/pass746r6r7_git_probe_certification_authority.cmake")
set(R6R9 "${PROJECT_ROOT}/tools/control/static-gates/pass746r6r9_historical_unborn_git_probe_migration.cmake")
set(R6R10 "${PROJECT_ROOT}/tools/control/static-gates/pass746r6r10_windows_powershell_git_probe_compat.cmake")
set(COMMON "${PROJECT_ROOT}/tools/control/ProjectOpsCommon.psm1")

foreach(PATH IN ITEMS "${HISTORICAL}" "${R6R7}" "${R6R9}" "${R6R10}" "${COMMON}")
  if(NOT EXISTS "${PATH}")
    message(FATAL_ERROR "R6R11 static gate missing file: ${PATH}")
  endif()
endforeach()

file(READ "${HISTORICAL}" HISTORICAL_TEXT)
file(READ "${R6R7}" R6R7_TEXT)
file(READ "${R6R9}" R6R9_TEXT)
file(READ "${R6R10}" R6R10_TEXT)
file(READ "${COMMON}" COMMON_TEXT)

function(r6r11_require TEXT_VALUE NEEDLE)
  string(FIND "${TEXT_VALUE}" "${NEEDLE}" FOUND_AT)
  if(FOUND_AT EQUAL -1)
    message(FATAL_ERROR "R6R11 static gate missing: ${NEEDLE}")
  endif()
endfunction()

foreach(TEXT_VALUE IN ITEMS "${HISTORICAL_TEXT}" "${R6R7_TEXT}" "${R6R9_TEXT}")
  r6r11_require("${TEXT_VALUE}" "System.Diagnostics.ProcessStartInfo")
endforeach()

r6r11_require("${COMMON_TEXT}" "function Invoke-ProjectOpsGitProbe")
r6r11_require("${COMMON_TEXT}" "$psi.PSObject.Properties['ArgumentList']")
r6r11_require("${COMMON_TEXT}" "$psi.Arguments = ($encodedArguments -join ' ')")
r6r11_require("${COMMON_TEXT}" "RedirectStandardOutput = $true")
r6r11_require("${COMMON_TEXT}" "RedirectStandardError = $true")
r6r11_require("${R6R10_TEXT}" "Windows PowerShell 5.1 / .NET Framework does not")

foreach(TEXT_VALUE IN ITEMS "${HISTORICAL_TEXT}" "${R6R7_TEXT}" "${R6R9_TEXT}")
  string(FIND "${TEXT_VALUE}" "[System.Diagnostics.ProcessStartInfo]::new()" OLD_CTOR)
  if(NOT OLD_CTOR EQUAL -1)
    message(FATAL_ERROR "R6R11 rejected constructor-specific ProjectOps Git-probe assertion")
  endif()
endforeach()

message(STATUS "Pass746R6R11 ProjectOps Git-probe validator normalization static gate PASS")
