# PASS1444-1453 - universal DCC asset-workbench visual normalization.
get_filename_component(P1453_ROOT "${CMAKE_CURRENT_LIST_DIR}/../../.." ABSOLUTE)

function(p1453_require rel token)
  set(path "${P1453_ROOT}/${rel}")
  if(NOT EXISTS "${path}")
    message(FATAL_ERROR "PASS1444-1453 missing required file: ${rel}")
  endif()
  file(READ "${path}" body)
  string(FIND "${body}" "${token}" pos)
  if(pos EQUAL -1)
    message(FATAL_ERROR "PASS1444-1453 missing token '${token}' in ${rel}")
  endif()
endfunction()

p1453_require("engine/include/application/SubspaceBuildIdentity.h" "DCC-ASSET-SHELL")
p1453_require("engine/include/application/SubspaceBuildIdentity.h" "PASS1453")
p1453_require("engine/include/editor/EditorDccShellLayoutSystem.h" "EditorDccShellLayout")
p1453_require("engine/src/editor/EditorDccShellLayoutSystem.cpp" "out.assetShelf")
p1453_require("engine/include/editor/EditorAssetWorkbenchSystem.h" "EditorAssetDomain")
p1453_require("engine/src/editor/EditorAssetWorkbenchSystem.cpp" "SHIP MODULES")
p1453_require("engine/src/ship_editor/ShipyardProfessionalVisibleCutover.cpp" "EditorDccShellLayoutSystem::Compute")
p1453_require("engine/src/ship_editor/ShipyardProfessionalVisibleCutover.cpp" "l.assetShelfY=dcc.assetShelf.y")
p1453_require("engine/src/application/NativeBattlefieldRenderer.cpp" "a neutral DCC canvas replaces the black in-game-space")
p1453_require("engine/src/application/NativeBattlefieldRenderer.cpp" "perspective floor grid")
p1453_require("engine/src/application/NativeBattlefieldRenderer.cpp" "ASSET WORKBENCH / ")
p1453_require("engine/src/application/NativeBattlefieldRenderer.cpp" "Compact viewport axis gizmo")
p1453_require("engine/src/application/NativeBattlefieldRenderer.cpp" "if(frame.standaloneShipyard){")
p1453_require("engine/src/application/NativeGameApplication.cpp" "kPreviewScale=0.30f")
p1453_require("engine/include/ship_editor/ShipyardDccUiSystem.h" "showSocketOverlay = false")
p1453_require("engine/include/ship_editor/ShipyardDccUiSystem.h" "showShieldPreview = false")
p1453_require("content/architecture/universal_dcc_asset_workspace_v1.json" "FIRST_WORKING_CONSUMER")
p1453_require("content/architecture/universal_dcc_asset_workspace_v1.json" "ADAPTER_PENDING")
p1453_require("docs/design/SUBSPACE_DCC_ASSET_WORKBENCH.md" "viewport-first")

message(STATUS "PASS1444-1453 universal DCC asset-workbench shell authority PASS")
