cmake_minimum_required(VERSION 3.20)
get_filename_component(P_ROOT "${CMAKE_CURRENT_LIST_DIR}/../../.." ABSOLUTE)
file(READ "${P_ROOT}/engine/tests/studio_duplicate_snap_preservation_r73_tests.cpp" TEST_SRC)
foreach(TOKEN "const auto expected=" "const auto staged=g;" "if(!validCandidate)return 1;" "confirmed placement exactly matches staged geometry and identity")
    string(FIND "${TEST_SRC}" "${TOKEN}" P)
    if(P EQUAL -1)
        message(FATAL_ERROR "R82R5 duplicate-snap lifetime proof missing: ${TOKEN}")
    endif()
endforeach()
string(FIND "${TEST_SRC}" "const auto& expected=" STALE_REFERENCE)
if(NOT STALE_REFERENCE EQUAL -1)
    message(FATAL_ERROR "R82R5 duplicate-snap test retains dangling candidate reference")
endif()
file(READ "${P_ROOT}/engine/src/ship_editor/ShipyardBuilderSystem.cpp" BUILDER)
string(FIND "${BUILDER}" "model_.recipe.modules.push_back(preview.ghost);" GHOST_COMMIT)
if(GHOST_COMMIT EQUAL -1)
    message(FATAL_ERROR "R82R5 committed placement must use staged ghost")
endif()
file(READ "${P_ROOT}/engine/tests/pass735_744_shipyard_dev_pcc_tests.cpp" HIST)
foreach(TOKEN "functional authoring workspaces remain reachable" "WorkspaceSystems" "WorkspaceAppearance" "WorkspaceBuild")
    string(FIND "${HIST}" "${TOKEN}" P)
    if(P EQUAL -1)
        message(FATAL_ERROR "R82R5 historical runtime test lacks actual command proof: ${TOKEN}")
    endif()
endforeach()
file(READ "${P_ROOT}/tools/control/static-gates/pass1466_1505_shipyard_foundry.cmake" OLD_GATE)
string(FIND "${OLD_GATE}" "p1505_require(\"engine/src/ship_editor/ShipyardBuilderSystem.cpp\" \"GLOBAL-SHIP (press again for LOCAL)\")" STALE_GATE)
if(NOT STALE_GATE EQUAL -1)
    message(FATAL_ERROR "R82R5 obsolete transform status literal still required by historical static gate")
endif()
foreach(TOKEN "bool ShipyardBuilderSystem::SetTransformConstraint(" "model_.transformConstraintLocal=true;" "void ShipyardBuilderSystem::ClearTransformConstraint()")
    string(FIND "${OLD_GATE}" "${TOKEN}" P)
    if(P EQUAL -1)
        message(FATAL_ERROR "R82R5 historical constraint gate missing functional proof: ${TOKEN}")
    endif()
endforeach()
message(STATUS "Subspace R82R5 stable snapshot and historical command/constraint source contract PASS")
