get_filename_component(PROJECT_ROOT "${ROOT}/.." ABSOLUTE)
set(TOOLS "${PROJECT_ROOT}/SubspaceTools.ps1")
set(QG "${PROJECT_ROOT}/tools/control/WriteQualityGateRecord.ps1")
set(PROJECT_CONTROL "${PROJECT_ROOT}/project.control.json")
set(INSTALLER "${PROJECT_ROOT}/scripts/install_subspace_root_utility.ps1")
set(RUNNER "${PROJECT_ROOT}/tools/control/ProjectOpsStaticCertification.cmake")

foreach(PATH IN ITEMS "${TOOLS}" "${QG}" "${PROJECT_CONTROL}" "${INSTALLER}" "${RUNNER}")
  if(NOT EXISTS "${PATH}")
    message(FATAL_ERROR "R6R8 static gate missing file: ${PATH}")
  endif()
endforeach()

file(READ "${TOOLS}" TOOLS_TEXT)
file(READ "${QG}" QG_TEXT)
file(READ "${PROJECT_CONTROL}" PROJECT_TEXT)
file(READ "${INSTALLER}" INSTALLER_TEXT)
file(READ "${RUNNER}" RUNNER_TEXT)

function(r6r8_require TEXT_VALUE NEEDLE)
  string(FIND "${TEXT_VALUE}" "${NEEDLE}" FOUND_AT)
  if(FOUND_AT EQUAL -1)
    message(FATAL_ERROR "R6R8 static gate missing: ${NEEDLE}")
  endif()
endfunction()

r6r8_require("${TOOLS_TEXT}" "incremental-authoritative")
r6r8_require("${TOOLS_TEXT}" "clean-full-gate")
r6r8_require("${TOOLS_TEXT}" "Invoke-CMakeBuild -CleanFirst:$CleanRoom")
r6r8_require("${TOOLS_TEXT}" "\"--parallel\", $parallelJobs")
r6r8_require("${TOOLS_TEXT}" "\"--parallel\", $parallelJobs,")
r6r8_require("${TOOLS_TEXT}" "GREEN gate: full debug ZIP suppressed for speed")
r6r8_require("${TOOLS_TEXT}" "Full quality gate / certify GREEN (incremental authoritative)")
r6r8_require("${QG_TEXT}" "executionMode=$ExecutionMode")
r6r8_require("${PROJECT_TEXT}" "\"certificationAcceleration\"")
r6r8_require("${PROJECT_TEXT}" "\"cleanRoomAction\": \"clean-full-gate\"")
r6r8_require("${INSTALLER_TEXT}" "ProjectOpsStaticCertification.cmake")
r6r8_require("${INSTALLER_TEXT}" "static-gates")
r6r8_require("${RUNNER_TEXT}" "file(GLOB STATIC_GATES")

string(FIND "${TOOLS_TEXT}" "forcing clean render rebuild" OLD_FORCE_CLEAN)
if(NOT OLD_FORCE_CLEAN EQUAL -1)
  message(FATAL_ERROR "R6R8 rejected unconditional clean Full Gate")
endif()

message(STATUS "Pass746R6R8 fast authoritative Full GREEN static gate PASS")
