cmake_minimum_required(VERSION 3.20)
get_filename_component(PROJECT_ROOT "${CMAKE_CURRENT_LIST_DIR}/../../.." ABSOLUTE)
function(require_text rel token)
  set(path "${PROJECT_ROOT}/${rel}")
  if(NOT EXISTS "${path}")
    message(FATAL_ERROR "R73-R82 missing source: ${rel}")
  endif()
  file(READ "${path}" text)
  string(FIND "${text}" "${token}" pos)
  if(pos EQUAL -1)
    message(FATAL_ERROR "R73-R82 ${rel} missing token: ${token}")
  endif()
endfunction()
function(forbid_text rel token)
  set(path "${PROJECT_ROOT}/${rel}")
  if(NOT EXISTS "${path}")
    message(FATAL_ERROR "R73-R82 missing source: ${rel}")
  endif()
  file(READ "${path}" text)
  string(FIND "${text}" "${token}" pos)
  if(NOT pos EQUAL -1)
    message(FATAL_ERROR "R73-R82 ${rel} retains forbidden stale token: ${token}")
  endif()
endfunction()
require_text("engine/include/studio/StudioPlacementWorkflowPolicy.h" "PreserveDuplicateAuthoredTraits")
require_text("engine/src/ship_editor/ShipyardBuilderSystem.cpp" "PreserveDuplicateAuthoredTraits(authoredBeforeSnap,model_.dragPreview.ghost)")
require_text("engine/src/application/NativeBattlefieldRenderer.cpp" "DrawStudioModelScene")
require_text("engine/src/application/NativeBattlefieldRenderer.cpp" "GEOMETRY DRAFT")
require_text("engine/src/application/NativeBattlefieldRenderer.cpp" "Live geometry preview - catalog publish pending")
require_text("engine/src/application/NativeBattlefieldRenderer.cpp" "BAKE DRAFT; catalog publication remains pending")
require_text("engine/src/ship_editor/ShipyardProfessionalVisibleCutover.cpp" "\"BAKE DRAFT\"")
require_text("engine/src/ship_editor/ShipyardBuilderSystem.cpp" "save/persistence bridge follows")
require_text("engine/src/ship_editor/ShipyardBuilderSystem.cpp" "Duplicate is unavailable in SOCKETS")
require_text("engine/src/ship_editor/ShipyardBuilderSystem.cpp" "if(model_.inspectorTab==ShipyardInspectorTab::Sockets)return RemoveSocket();")
require_text("engine/src/ship_editor/ShipyardProfessionalVisibleCutover.cpp" "const bool socketSelection=")
forbid_text("engine/src/application/NativeBattlefieldRenderer.cpp" "Shape preview and publish are not yet wired")
forbid_text("engine/src/application/NativeBattlefieldRenderer.cpp" "3D preview / publish not wired")
forbid_text("engine/src/ship_editor/ShipyardProfessionalVisibleCutover.cpp" "PUBLISH UNWIRED")
message(STATUS "R73-R82 Studio convergence-audit source gate PASS")
