# PASS1454-1465 - first-class Shipyard / ForgeGUI convergence authority.
get_filename_component(P1465_ROOT "${CMAKE_CURRENT_LIST_DIR}/../../.." ABSOLUTE)

function(p1465_require rel token)
  set(path "${P1465_ROOT}/${rel}")
  if(NOT EXISTS "${path}")
    message(FATAL_ERROR "PASS1454-1465 missing required file: ${rel}")
  endif()
  file(READ "${path}" body)
  string(FIND "${body}" "${token}" pos)
  if(pos EQUAL -1)
    message(FATAL_ERROR "PASS1454-1465 missing token '${token}' in ${rel}")
  endif()
endfunction()

p1465_require("engine/include/application/SubspaceBuildIdentity.h" "FIRST-CLASS-DCC")
p1465_require("engine/include/application/SubspaceBuildIdentity.h" "PASS1465")
p1465_require("engine/include/application/SubspaceBuildIdentity.h" "PASS1454-1465")
p1465_require("engine/include/editor/EditorForgeGuiStyleSystem.h" "532f7e1")
p1465_require("engine/include/editor/EditorForgeGuiStyleSystem.h" "panelHeaderHeight = 27.0f")
p1465_require("engine/include/editor/EditorForgeGuiStyleSystem.h" "propertyRowHeight = 27.0f")
p1465_require("engine/include/editor/EditorForgeGuiStyleSystem.h" "splitterWidth = 3.0f")
p1465_require("engine/include/editor/EditorForgeGuiStyleSystem.h" "ForgeGUI_Core 0.4.8 / Creator Studio")
p1465_require("engine/src/editor/EditorDccShellLayoutSystem.cpp" "EditorForgeGuiStyleSystem::Metrics")
p1465_require("engine/src/ship_editor/ShipyardProfessionalVisibleCutover.cpp" "A narrow context rail selects the workflow")
p1465_require("engine/src/ship_editor/ShipyardProfessionalVisibleCutover.cpp" "SAVE BLUEPRINT")
p1465_require("engine/src/ship_editor/ShipyardProfessionalVisibleCutover.cpp" "SAVE SOCKETS")
p1465_require("engine/src/ship_editor/ShipyardProfessionalVisibleCutover.cpp" "SAVE DEFINITION")
p1465_require("engine/src/application/NativeBattlefieldRenderer.cpp" "EditorForgeGuiStyleSystem::Palette")
p1465_require("engine/src/application/NativeBattlefieldRenderer.cpp" "ASSETS")
p1465_require("engine/src/application/NativeBattlefieldRenderer.cpp" "OUTLINER")
p1465_require("engine/src/application/NativeBattlefieldRenderer.cpp" "PROPERTIES")
p1465_require("engine/src/application/NativeBattlefieldRenderer.cpp" "fitText")
p1465_require("engine/src/platform/NativeWindow.cpp" "DwmSetWindowAttribute")
p1465_require("engine/src/platform/NativeWindow.cpp" "DWMWA_USE_IMMERSIVE_DARK_MODE")
p1465_require("engine/src/application/NativeGameApplication.cpp" "Codename: Subspace - Shipyard Editor")
p1465_require("content/architecture/shipyard_first_class_editor_v1.json" "FORGEGUI_DONOR")
p1465_require("docs/design/SHIPYARD_FIRST_CLASS_EDITOR_FORGEGUI_CONVERGENCE.md" "PASS1454-1465")

message(STATUS "PASS1454-1465 first-class Shipyard / ForgeGUI convergence authority PASS")
