# Gizmo G1: verify drawing, selection, drag and undo share one native authority.
# Historical UI-text assertions must never stand in for actual pointer routing.
get_filename_component(G1_ROOT "${CMAKE_CURRENT_LIST_DIR}/../../.." ABSOLUTE)
function(g1_require rel token)
    set(path "${G1_ROOT}/${rel}")
    if(NOT EXISTS "${path}")
        message(FATAL_ERROR "G1 missing source: ${rel}")
    endif()
    file(READ "${path}" body)
    string(FIND "${body}" "${token}" found)
    if(found EQUAL -1)
        message(FATAL_ERROR "G1 missing '${token}' in ${rel}")
    endif()
endfunction()
g1_require("engine/include/editor/EditorGizmoSystem.h" "enum class EditorGizmoAxis")
g1_require("engine/src/editor/EditorGizmoSystem.cpp" "EditorGizmoSystem::BuildModule")
g1_require("engine/src/editor/EditorGizmoSystem.cpp" "EditorGizmoSystem::Pick")
g1_require("engine/src/application/NativeBattlefieldRenderer.cpp" "EditorGizmoSystem::BuildModule(placement,m.recipe")
g1_require("engine/src/application/NativeGameApplication.cpp" "EditorGizmoSystem::BuildModule(selected,m.recipe")
g1_require("engine/src/application/NativeGameApplication.cpp" "ShipyardPanelCompositorSystem::Contains(panel.rect,x,y)")
g1_require("engine/src/application/NativeGameApplication.cpp" "ApplyShipyardGizmoDrag(dragX,dragY,fine,camera)")
g1_require("engine/src/application/NativeGameApplication.cpp" "ApplyShipyardGizmoDrag(dx,dy,fine,activeCamera)")
g1_require("engine/src/application/NativeGameApplication.cpp" "_shipBuilder.CancelTransform();_shipyardGizmoHandle={};")
g1_require("engine/src/ship_editor/ShipyardBuilderSystem.cpp" "ResetSelectedTransformPreview()")
g1_require("engine/src/ship_editor/ShipyardBuilderSystem.cpp" "static_cast<int>(ModelingPrimitiveType::Pipe)+1")
g1_require("engine/tests/shipyard_unified_gizmo_g1_tests.cpp" "EditorGizmoSystem::Pick")
message(STATUS "Subspace G1 shared selected-module XYZ gizmo authority PASS")
