# Studio G2: verify main-menu authoring is empty and live gameplay remains intact.
get_filename_component(G2_ROOT "${CMAKE_CURRENT_LIST_DIR}/../../.." ABSOLUTE)
function(g2_require rel token)
    file(READ "${G2_ROOT}/${rel}" body)
    string(FIND "${body}" index "${token}")
    if(index EQUAL -1)
        message(FATAL_ERROR "G2 missing ${token} in ${rel}")
    endif()
endfunction()
g2_require("engine/src/application/NativeGameApplication.cpp" "SelectInitialDocument(")
g2_require("engine/src/application/NativeGameApplication.cpp" "const auto starter=standalone?ShipyardDocumentStartupSystem::EmptyDocument()")
g2_require("engine/src/ship_editor/ShipyardBuilderSystem.cpp" "case ShipyardBuilderCommand::NewEmptyDocument:")
g2_require("engine/src/ship_editor/ShipyardBuilderSystem.cpp" "Unsaved changes: SAVE DRAFT first")
g2_require("engine/src/ship_editor/ShipyardBuilderSystem.cpp" "authoringUndo_.clear();authoringRedo_.clear();")
g2_require("engine/src/application/NativeBattlefieldRenderer.cpp" "if(frame.standaloneShipyard&&frame.shipBuilderRecipe)")
g2_require("engine/src/application/NativeBattlefieldRenderer.cpp" "if(frame.playerPhysics&&!frame.standaloneShipyard)")
g2_require("engine/src/ship_editor/ShipyardProfessionalVisibleCutover.cpp" "NEW EMPTY")
g2_require("engine/src/application/NativeBattlefieldRenderer.cpp" "EMPTY SHIP DOCUMENT")
g2_require("engine/src/application/NativeBattlefieldRenderer.cpp" "A first module must still appear as a drag preview")
g2_require("engine/src/ship_editor/ShipyardProfessionalVisibleCutover.cpp" "387.0f*s<=vx-4.0f*s")
g2_require("engine/src/application/NativeBattlefieldRenderer.cpp" "const float bx=cx+t*(right-left)*.5f")
message(STATUS "G2 blank-document and viewport-width source authority PASS")
