get_filename_component(root "${CMAKE_CURRENT_LIST_DIR}/../../.." ABSOLUTE)
function(require_source relative token)
    file(READ "${root}/${relative}" source)
    string(FIND "${source}" "${token}" found)
    if(found EQUAL -1)
        message(FATAL_ERROR "Studio G3 missing ${token} in ${relative}")
    endif()
endfunction()
require_source("engine/src/platform/NativeWindow.cpp" "_editorNavigationMode&&!_shiftDown")
require_source("engine/src/application/NativeGameApplication.cpp" "_window.SetEditorNavigationMode(true)")
require_source("engine/src/application/NativeGameApplication.cpp" "_window.SetEditorNavigationMode(false)")
require_source("engine/src/ship_editor/ShipyardProfessionalVisibleCutover.cpp" "ShipyardBuilderCommand::MenuFile")
require_source("engine/src/ship_editor/ShipyardProfessionalVisibleCutover.cpp" "ShipyardBuilderCommand::DccCycleStudioView")
require_source("engine/src/application/NativeBattlefieldRenderer.cpp" "DrawStudioInteriorShell(frame,previewRole)")
require_source("engine/src/application/NativeGameApplication.cpp" "ShipInteriorLayoutSystem{}.Plan(0,_shipBuilder.Model().catalog,recipe)")
require_source("engine/src/ship_editor/ShipyardProfessionalVisibleCutover.cpp" "currentPanelId=\"studio_menu\"")
require_source("engine/src/ship_editor/ShipyardProfessionalVisibleCutover.cpp" "ShipyardBuilderCommand::InteriorAddDoor")
require_source("engine/src/ship_editor/ShipyardProfessionalVisibleCutover.cpp" "ShipyardBuilderCommand::NextPrimaryFinish")
require_source("engine/src/application/NativeBattlefieldRenderer.cpp" "c.panelId==\"studio_menu\"")
require_source("engine/src/ship_editor/ShipyardBuilderSystem.cpp" "generation blocked to prevent losing them")
require_source("engine/src/ship_editor/ShipyardBuilderSystem.cpp" "Blueprint save failed")
message(STATUS "Studio G3 editor workflow source contract PASS")
