# Studio foundation R3: source authority only; live WGL acceptance is separate.
function(required path marker)
    file(READ "${CMAKE_CURRENT_LIST_DIR}/../../../${path}" source)
    string(FIND "${source}" "${marker}" position)
    if(position EQUAL -1)
        message(FATAL_ERROR "Null Harbor R3 Studio foundation authority missing: ${path} :: ${marker}")
    endif()
endfunction()
required("engine/src/studio/StudioApplication.cpp" "const StudioOverlayProgramScope overlayProgramScope;")
required("engine/src/studio/StudioAxisGizmo.cpp" "StudioGizmoProjectionPolicy::Direction")
required("engine/src/studio/StudioAxisGizmo.cpp" "(assemblyMode&&model.inspectorTab==ShipyardInspectorTab::Sockets)")
required("engine/include/studio/StudioOverlayProgramScope.h" "use_(static_cast<GLuint>(previous_))")
required("engine/include/studio/StudioOverlayProgramScope.h" "if (previous_ != 0) use_(0);")
message(STATUS "Null Harbor Studio foundation R3 widget/overlay authority PASS")
