function(req path needle)
  file(READ "${CMAKE_CURRENT_LIST_DIR}/../../../${path}" text)
  string(FIND "${text}" "${needle}" at)
  if(at EQUAL -1)
    message(FATAL_ERROR "Studio modeling closure missing authority: ${path} :: ${needle}")
  endif()
endfunction()
req("engine/src/studio/StudioApplication.cpp" "PickModelPrimitive")
req("engine/src/studio/StudioApplication.cpp" "ModelSelectPrimitive")
req("engine/src/studio/StudioApplication.cpp" "HasUnsavedModeling")
req("engine/src/studio/StudioAxisGizmo.cpp" "modelMode")
req("engine/src/application/NativeBattlefieldRenderer.cpp" "DrawStudioModelScene")
req("engine/src/ship_editor/ShipyardBuilderSystem.cpp" "modelTransformActive_")
req("engine/src/ship_editor/ShipyardBuilderSystem.cpp" "MarkModelingSaved")
req("engine/src/studio/StudioDocumentStore.cpp" "StudioModelDocumentCodec")
req("engine/src/ship_editor/ShipyardProfessionalVisibleCutover.cpp" "ModelSelectPrimitive")
message(STATUS "Subspace Studio object-modeling closure authority PASS")
